### ISSUE TITLE
bbb-install.sh for ubuntu18.04

### ISSUE THREAD

**Issue by asd51731** [bigbluebutton/bbb-install#102]
hi ,Ｉ want to install bigbluebutton on ubuntu18.04, and I found the bionic parameter is for ubuntu18.04. But is 'boinic' is the correct parameter, or like 'xenial-220' is for ubuntu16.04. Can you give me some suggest. Thanks.

**Comment by ffdixon** [comment]
Yes, we are currently extending [bbb-install.sh](https://github.com/bigbluebutton/bbb-install) to be ready for installing the next version of BigBlueButton on Ubuntu 18.04; however, that next version is still in development.  

When we have a beta released, you'll be able to install it right away with `bbb-install.sh`.  We'll update this issue when it's ready to test ou.

**Comment by matinzd** [comment]
> Yes, we are currently extending [bbb-install.sh](https://github.com/bigbluebutton/bbb-install) to be ready for installing the next version of BigBlueButton on Ubuntu 18.04; however, that next version is still in development.
> 
> When we have a beta released, you'll be able to install it right away with `bbb-install.sh`. We'll update this issue when it's ready to test ou.

Is that ready in v2.2.2?

**Comment by ffdixon** [comment]
BigBlueButton 2.3 (next version) will be on Ubuntu 18.04.  We'll announce when we have the first beta available for testing to the bigbluebutton-dev mailing list.

**Comment by nadavkav** [comment]
Can we workaround this script, somehow, to install the current BBB 2.2 on Ubuntu Bionic 18.04 ?
(As I do not wish to wait for the beta version)

**Comment by jfederico** [comment]
Hi @nadavkav 
No, there is no way. The packaging and dependences in 2.2 are for Ubuntu 16.04 only.

**Comment by nadavkav** [comment]
Thank you @jfederico . 
I installed the Ubuntu Xenial OS with BBB xenial-220 version and everything works great!
