### ISSUE TITLE
The installer fails every time

### ISSUE THREAD

**Issue by byGits** [bigbluebutton/bbb-install#106]
Hello,

Thank you for making this, but I've been trying this installer since last night for about 9 times, and every time there is something wrong.

I create a fresh VPS on Hetzner, 4 CPU vcores + 16GB Ram every time,  some times I ran the script like this:
`wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v xenial-220 -s test.mydomain.xyz -e info@mydomain.xyz -g`
But every time I tried to access `https://test.mydomain.xyz`, it was redirected to `https://test.mydomain.xyz/b` (notice the b at the end) and showed 404 not found.

Other times I ran it without `-g` and tried to manually install Greenlight afterwards, but then when I run the `sudo bbb-conf --secret` command to get BBB credentials for GL, it shows this BIGBLUEBUTTON_ENDPOINT: 
`https://test.mydomain.xyz/bigbluebutton`

But even though I can access `https://test.mydomain.xyz` the `/bigbluebutton/` directory throws 404 Not Found error, and cannot be connected to Greenlight.

I have tried this a lot of times (at least 9 times) with a fresh VPS, for example once I upgraded Kernel to 4.15 (from 4.4) and rebooted and then tried to install, other times I didn't touch anything and just installed, no matter what I do, this always fails for some reason.

Even when I try to install the demo with `-a` I get the following error and then the process is stuck: 

> Errors were encountered while processing:
> tomcat7
> bbb-demo

Any help is greatly appreciated.

I'm going to continue trying, and will update if I find a fix.

**Comment by ffdixon** [comment]
We're debugging an issue with the newer version of Greenlight where `bbb-install.sh` is not properly configuring its startup.  

We'll update this ticket as we progress.

**Comment by ffdixon** [comment]
Can you try the following commands

~~~
cd greenlight
PGPASSWORD=$(openssl rand -hex 8)
sed -i "s/POSTGRES_PASSWORD=password/POSTGRES_PASSWORD=$PGPASSWORD/g" ~/greenlight/docker-compose.yml
sed -i "s/DB_PASSWORD=password/DB_PASSWORD=$PGPASSWORD/g" ~/greenlight/.
docker-compose down
docker-compose up -d
~~~

**Comment by ffdixon** [comment]
For more details see https://github.com/bigbluebutton/greenlight/issues/981

**Comment by iCodeAtNight** [comment]
> For more details see [bigbluebutton/greenlight#981](https://github.com/bigbluebutton/greenlight/issues/981)

Thank you very much for replying, 
I will try the command soon, but I just wanted to point out that even when I install it without Greenlight, the `sudo bbb-conf --secret` command displays this BIGBLUEBUTTON_ENDPOINT:
`https://test.mydomain.xyz/bigbluebutton`

But the `/bigbluebutton` directory throws "404 Not Found" error, hope this is also a known issue that will be fixed.

Thanks again, and have a wonderful day/night!

**Comment by GremL1N** [comment]
I think proble is like this #98 
Show for us `bbb-conf --check` output
Try this
```
sudo apt-get install openjdk-8-jdk
sudo apt-get remove openjdk-9-jre-headless
update-alternatives --config java
```

**Comment by byGits** [comment]
> I think problem is like this #98
> Show for us `bbb-conf --check` output
> Try this
> 
> ```
> sudo apt-get install openjdk-8-jdk
> sudo apt-get remove openjdk-9-jre-headless
> update-alternatives --config java
> bbb-conf --restart
> ```

WOW! Thank you very much!
I simply ran `sudo apt-get install openjdk-8-jdk` before installing on a fresh server, and everything worked perfectly!

I think this should be in the installation guide or bbb-install script!

**Comment by ffdixon** [comment]
It seems like some hosting providers have a later version of Java installed by default.  Added a section to the troubleshooting guide

  http://docs.bigbluebutton.org/2.2/troubleshooting.html#404-error-when-loading-the-client

and updated `bbb-install.sh` to install `openjdk-8-jre` before installing BigBlueButton.

**Comment by byGits** [comment]
> It seems like some hosting providers have a later version of Java installed by default. Added a section to the troubleshooting guide
> 
> http://docs.bigbluebutton.org/2.2/troubleshooting.html#404-error-when-loading-the-client
> 
> and updated `bbb-install.sh` to install `openjdk-8-jre` before installing BigBlueButton.

Thank you, since this is an open source project I had no hope of getting any help that fixes the issue this quickly!

You guys are the best!

**Comment by ffdixon** [comment]
Send that out as a tweet to @bigbluebutton!
