### ISSUE TITLE
Performance Details / Stress Testing

### ISSUE THREAD

**Issue by danhardman** [bigbluebutton/bbb-install#107]
Does anyone have any detail on the expected performance achievable out of the minimum server requirements suggested on the docs? 

It'd be great to know how many simultaneous lessons or connected users I can expect a minimal server to handle before considering load balancing. Would be great to add to the docs too!

Thanks

**Comment by ffdixon** [comment]
It depends on what your users are doing.  If a single instructor is sharing their audio and webcam, then you can get 100's of users on the server.

If you have sessions of 25 people all sharing webcams (not recommended), then you will very likely hit a bottleneck with bandwidth first.

For references for others reading this issue, see http://docs.bigbluebutton.org/support/faq.html#how-many-simultaneous-users-can-bigbluebutton-support

**Comment by danhardman** [comment]
That's perfect, thank you. Looking at that I can see degradation of quality starts to occur at ~80% CPU usage so we can always setup autoscaling rules based on that. 

Thanks!
