### ISSUE TITLE
Server Error - Invalid BigBlueButton Endpoint and Secret

### ISSUE THREAD

**Issue by CrazyOptimist** [bigbluebutton/bbb-install#110]
Hi Fred, I need your help! I am getting the error just like the title of this issue. :(
```
root@G-MainServer:~/greenlight# docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check

Checking environment: Passed
Checking Connection: Failed
Could not get a valid response from BigBlueButton server - <html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.10.3 (Ubuntu)</center>
</body>
</html>
```
Thank you in advance!

**Comment by CrazyOptimist** [comment]
Solved after I replaced the secret and 
```
docker-compose down
docker-compose up -d
```
Thank you opensource contributors!

**Comment by CrazyOptimist** [comment]
I got this error this time.
Could you give me an advice asap?
![image](https://user-images.githubusercontent.com/55074937/76184297-72ac3380-6199-11ea-9361-8a93fa6b8c53.png)

**Comment by CrazyOptimist** [comment]
I have figure it out myself. Fred's response takes forever... :)
I purged everything following [this](https://groups.google.com/forum/#!topic/bigbluebutton-setup/1jmxUhNHzhA).
And installed the system again using correct command:
```bash
$bash bbb-install.sh -v xenial -s domain.com -e me@email.com -g
```
Worked like a charm..
Thanks for your hard work Fred and all contributors.
I am impressed.

**Comment by ffdixon** [comment]
Glad to hear you got it running.  If you like our project, tweet some love to @bigbluebutton.
