### ISSUE TITLE
customize landing page

### ISSUE THREAD

**Issue by fferraro87** [bigbluebutton/bbb-install#113]
Hi,

i've customized localization inside greenlight container but if i do this command inside greenlight directory : 
`
./scripts/image_build.sh bigbluebutton/greenlight:v2 release-v2
`
image_build.sh doesn't exist (also scripts folder), i'm trying to search that file on entire file system and there is only inside containers : 
`
root@meet2u:~/greenlight# find / -name "image_build.sh"
/var/lib/docker/overlay2/b9afc50b2d08572e56ece62a18822669cd37e1880f3d3db8c389fba7eccdc128/diff/usr/src/app/scripts/image_build.sh
/var/lib/docker/overlay2/86f7f151d34a916239ab8c1a14227656df94747d830519ebca2a8b39cae0b340/merged/usr/src/app/scripts/image_build.sh
`
So how can i apply my editing?
Thanks

**Comment by fferraro87** [comment]
i've done

**Comment by Samanosuke2020** [comment]
How you did will you please explain i m a noob
