### ISSUE TITLE
bbb-freeswitch-core.postinst command not found

### ISSUE THREAD

**Issue by aogilvie** [bigbluebutton/bbb-install#115]
installing via xenial-220-rc6 see this error in the logs:

```
Setting up bbb-freeswitch-core (2:2.2.0-82) ...
/var/lib/dpkg/info/bbb-freeswitch-core.postinst: line 323: -f: command not found
Adding freeswitch.service to autostart using systemd
```

Install continues without errors.

Not sure if this is a real problem or not.

**Comment by kepstin** [comment]
This issue applied to an old version of bigbluebutton packaging, and was not related to bbb-install. It has been fixed in current bigbluebutton versions.
