### ISSUE TITLE
isntalling via bbb-install.sh issue

### ISSUE THREAD

**Issue by tehseensagar** [bigbluebutton/bbb-install#116]
Greetings to All,

I want to install bigbluebutting on my local machine in lan . I've added dns entry localy on my dns server which is local and as well as hosts  file .I've generated the self signed certificate / key already. Kindly let me know how do go with local dns and self signed cert installation along with greenlisght.

Regards

**Comment by jfederico** [comment]
I would recommend you no to use self signed certificates. You should better go with Let's encrypt ones.

The script has been modified so if you use the `-x` parameter, it will give you instructions on how to proceed to validate the Let's Encrypt Challenge manually through DNS.

```
    ./bbb-install.sh -v xenial-220 -s bbb.example.com -e info@example.com -x
```

Now, keep in mind that Let's encrypt certificates are valid for 3 months only. They are meant to be for servers on the cloud (which the script also covers by default), but in your case you are going to have to renew manually through the console. 

See https://certbot.eff.org/docs/using.html#manual
