### ISSUE TITLE
Error instalation 1.1

### ISSUE THREAD

**Issue by clecioantao** [bigbluebutton/bbb-install#12]
Hello, Is not installing version 1.1 working any more? There are errors:

echo "deb https://ubuntu.bigbluebutton.org/xenial-110/ bigbluebutton-xenial main" | sudo tee /etc/apt/sources.list.d/bigbluebutton.list

**Comment by ffdixon** [comment]
Hi there,

The `bbb-install.sh` script only works with BigBlueButton 2.0-beta.  If your setting up a new server, we recommend you setup BigBlueButton 2.0-beta.  It's been in beta for quite some time and is quite solid.  It will soon replace 1.1.

**Comment by clecioantao** [comment]
Hi Fred!

First of all congratulations for the script bbb-install, it was a work of art!

I'm doing a BigBlueButton training, and I would like to show the installation steps of version 1.1, until the students know the processes, but I am incorporating the installation of version 2.0 with the script as well.

However, in the installation of 1.1 I found a problem and I already discovered the reason, it would be in step 2. Install apt-get key for BigBlueButton repository - where the inclusion in the list is working:

$ echo "deb https://ubuntu.bigbluebutton.org/xenial-110/ bigbluebutton-xenial main" | sudo tee /etc/apt/sources.list.d/bigbluebutton.list

But testing without SSL works:

$ echo "deb http://ubuntu.bigbluebutton.org/xenial-110/ bigbluebutton-xenial main" | sudo tee /etc/apt/sources.list.d/bigbluebutton.list

This step worked perfectly before the script, maybe some change made.

Regards!

**Comment by ffdixon** [comment]
Hi,

Just tested

$ echo "deb https://ubuntu.bigbluebutton.org/xenial-110/ bigbluebutton-xenial main" | sudo tee /etc/apt/sources.list.d/bigbluebutton.list

on a clean server and it works.  Are you by chance using an apt-get proxy (such as apt-cacher-ng)?  Look in `/etc/apt/apt.conf.d/` and see if you have a file with the word `proxy` in it. 

We recommend installing BigBlueButton 2.0-beta as we've not tested `bbb-install.sh` with 1.1.  It might work, but we'll soon be releasing 2.0-beta as a release candidate.

**Comment by clecioantao** [comment]
Hi Fred, 

There is no proxy, this server I always use for testing and always installed without problems.

But do not worry, I'll use version 2.0, I'm performing Setup 1.1 just to elucidate the steps for students, more for the purpose of knowledge.

I'm doing video lessons, in Portuguese at first, then I want to do in English.

Thank you.

Regards!
