### ISSUE TITLE
Missing Greenlight installation

### ISSUE THREAD

**Issue by lonesomewalker** [bigbluebutton/bbb-install#120]
When installing with bbb-install and adding the option -g i expect to have at least docker installed and kind of preconfigured.

When the installation has finished, the default start page is still BigBlueButton, and docker -v also tells me that it is not installed.

How to debug?

**Comment by KevinPayravi** [comment]
Looks like the check for -g flag in `bbb-install.sh` was accidentally removed at some point, and then restored in https://github.com/bigbluebutton/bbb-install/commit/63b468bdf80f866f5ec7333e4afcc3d3a201b3b0. Unfortunately the version of `bbb-install.sh` at https://ubuntu.bigbluebutton.org/bbb-install.sh is still outdated and missing the -g flag.

If you replace the wget URL with https://raw.githubusercontent.com/bigbluebutton/bbb-install/master/bbb-install.sh it should work.

CC @ffdixon need to update the version of `bbb-install.sh` hosted at bigbluebutton.org. Thank you!

**Comment by ricubuntu** [comment]
Hello @KevinPayravi !
It worked for me but it seems like with the new url the SSLcertificate step is missing. i have now a greenlight v2 running but the website is "not secure". Can you help me to fix?
Thank you very much!

**Comment by lonesomewalker** [comment]
Please DON'T hijack issues...
Okay, i already saw the "removed -g by accident" at git, but thought this was fixed already. :-)
Thanks :+1:

**Comment by ffdixon** [comment]
@KevinPayravi Thanks -- updated `bbb-install.sh` at bigbluebutton.org with latest version.
