### ISSUE TITLE
Can't open new room

### ISSUE THREAD

**Issue by beforeusa** [bigbluebutton/bbb-install#125]
I received 500 error when open new room.

_I use cloudflare._

<img width="1233" alt="Screen Shot 2020-03-20 at 2 12 48 AM" src="https://user-images.githubusercontent.com/22252984/77105519-61441080-6a50-11ea-9fe3-10222f9e0761.png">

Please help me. Thank you so much.

```
BigBlueButton Server 2.2.2 (1786)
                    Kernel version: 4.4.0-174-generic
                      Distribution: Ubuntu 16.04.6 LTS (64-bit)
                            Memory: 8174 MB
                         CPU cores: 4

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://streaming.hodi.vn
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: streaming.hodi.vn
                              port: 80, [::]:80
                    bbb-client dir: /var/www/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://streaming.hodi.vn
                              red5: streaming.hodi.vn
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 45.76.191.40
                   external_rtp_ip: stun:stun.freeswitch.org
                   external_sip_ip: stun:stun.freeswitch.org

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: :5066
                       wss-binding: :7443

/var/www/bigbluebutton/check/conf/config.xml (client check)
                      client check: streaming.hodi.vn

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: streaming.hodi.vn
                 playback_protocol: https
                            ffmpeg: 4.2.2-1bbb1~ubuntu16.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: 45.76.191.40

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: 45.76.191.40
                       kurento.url: ws://127.0.0.1:8888/kurento
                    localIpAddress: 45.76.191.40
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 862
                        kurentoUrl: ws://streaming.hodi.vn/bbb-webrtc-sfu
                  enableListenOnly: true


# Potential problems described below
# IP does not match:
#                           IP from ifconfig: 45.76.191.40
#   /etc/nginx/sites-available/bigbluebutton: streaming.hodi.vn
# Warning: API URL IPs do not match host:
#
#                                IP from ifconfig: 45.76.191.40
#  /var/lib/tomcat7/demo/bbb_api_conf.jsp: streaming.hodi.vn


# Error: Unable to connect to port 1935 (RTMP) on streaming.hodi.vn

# Warning: The API demos are installed and accessible from:
#
#    https://streaming.hodi.vn
#
# and
#
#    https://streaming.hodi.vn/demo/demo1.jsp
#
# These API demos allow anyone to access your server without authentication
# to create/manage meetings and recordings. They are for testing purposes only.
# If you are running a production system, remove them by running:
#
#    apt-get purge bbb-demo

# Warning: The client self check is installed and accessible from:
#
#    https://streaming.hodi.vn/check
#

# Warning: You have this server defined for https, but in
#
#   /etc/bigbluebutton/nginx/sip.nginx
#
#  did not find the use of https in definition for proxy_pass
#
#            proxy_pass http://45.76.191.40:5066;
#

# Warning: You have this server defined for https, but in
#
#   /etc/bigbluebutton/nginx/sip.nginx
#
#  did not find the use of port 7443 in definition for proxy_pass
#
#            proxy_pass http://45.76.191.40:5066;
```

**Comment by ffdixon** [comment]
> I use cloudflare.

Can you explain more what you mean.

**Comment by beforeusa** [comment]
Hello @ffdixon, I make a metting throught api and now it's working.
But I can't turn on microphone, I recived this message

> could not make websocket connection 1002.


`# Warning: The API demos are installed and accessible from:
#
#    https://streaming.hodi.vn
#
# and
#
#    https://streaming.hodi.vn/demo/demo1.jsp
#
# These API demos allow anyone to access your server without authentication
# to create/manage meetings and recordings. They are for testing purposes only.
# If you are running a production system, remove them by running:
#
#    apt-get purge bbb-demo


# Warning: You have this server defined for https, but in
#
#   /etc/bigbluebutton/nginx/sip.nginx
#
#  did not find the use of port 7443 in definition for proxy_pass
#
#            proxy_pass https://139.180.152.34:7433;
#
root@streaming:/var/lib/tomcat7/webapps/demo# clear
root@streaming:/var/lib/tomcat7/webapps/demo# sudo bbb-conf --check

BigBlueButton Server 2.2.2 (1781)
                    Kernel version: 4.4.0-174-generic
                      Distribution: Ubuntu 16.04.6 LTS (64-bit)
                            Memory: 8174 MB
                         CPU cores: 4

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://streaming.hodi.vn
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: streaming.hodi.vn
                              port: 80, [::]:80
                              port: 443 ssl
                    bbb-client dir: /var/www/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://streaming.hodi.vn
                              red5: streaming.hodi.vn
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 139.180.152.34
                   external_rtp_ip: stun:stun.freeswitch.org
                   external_sip_ip: stun:stun.freeswitch.org

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: :5066
                       wss-binding: :7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: streaming.hodi.vn
                 playback_protocol: https
                            ffmpeg: 4.2.2-1bbb1~ubuntu16.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: 139.180.152.34

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: 139.180.152.34
                       kurento.url: ws://127.0.0.1:8888/kurento
                    localIpAddress: 139.180.152.34
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 862
                        kurentoUrl: wss://streaming.hodi.vn/bbb-webrtc-sfu
                  enableListenOnly: true


# Potential problems described below
# IP does not match:
#                           IP from ifconfig: 139.180.152.34
#   /etc/nginx/sites-available/bigbluebutton: streaming.hodi.vn
# Warning: API URL IPs do not match host:
#
#                                IP from ifconfig: 139.180.152.34
#  /var/lib/tomcat7/demo/bbb_api_conf.jsp: streaming.hodi.vn


# Error: Unable to connect to port 1935 (RTMP) on streaming.hodi.vn

# Warning: The API demos are installed and accessible from:
#
#    https://streaming.hodi.vn
#
# and
#
#    https://streaming.hodi.vn/demo/demo1.jsp
#
# These API demos allow anyone to access your server without authentication
# to create/manage meetings and recordings. They are for testing purposes only.
# If you are running a production system, remove them by running:
#
#    apt-get purge bbb-demo


# Warning: You have this server defined for https, but in
#
#   /etc/bigbluebutton/nginx/sip.nginx
#
#  did not find the use of port 7443 in definition for proxy_pass
#
#            proxy_pass https://139.180.152.34:7433;`

nginx —————————————————► [✔ - active]
freeswitch ————————————► [✔ - active]
redis-server ——————————► [✔ - active]
bbb-apps-akka —————————► [✔ - active]
bbb-transcode-akka ————► [✔ - active]
bbb-fsesl-akka ————————► [✔ - active]
red5 ——————————————————► [✔ - active]
tomcat7 ———————————————► [✔ - active]
mongod ————————————————► [✔ - active]
bbb-html5 —————————————► [✔ - active]
bbb-webrtc-sfu ————————► [✔ - active]
kurento-media-server ——► [✔ - active]
etherpad ——————————————► [✔ - active]
bbb-web ———————————————► [✔ - active]

**Comment by beforeusa** [comment]
@ffdixon Oh. I had a wrong in 

> /etc/bigbluebutton/nginx/sip.nginx

Just edited port to 7443 and working now. Thank you.
