### ISSUE TITLE
Issue Install 

### ISSUE THREAD

**Issue by wrxcharger** [bigbluebutton/bbb-install#140]
Hi everyone is my first post  install with  script "wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v xenial-220 -a" and say error...  

Preparing to unpack .../bbb-etherpad_1%3a2.2.0-49_amd64.deb ...
/var/lib/dpkg/tmp.ci/preinst: line 282: /usr/share/etherpad-lite/APIKEY.txt: No such file or directory
dpkg: error processing archive /var/cache/apt/archives/bbb-etherpad_1%3a2.2.0-49_amd64.deb (--unpack):
 subprocess new pre-installation script returned error exit status 1
Selecting previously unselected package bbb-html5.
Preparing to unpack .../bbb-html5_1%3a2.2.0-870_amd64.deb ...
Unpacking bbb-html5 (1:2.2.0-870) ...
Processing triggers for man-db (2.7.5-1) ...
Errors were encountered while processing:
 /var/cache/apt/archives/bbb-etherpad_1%3a2.2.0-49_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
Reading package lists...
Building dependency tree...
Reading state information...
You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies:
 bbb-demo : Depends: tomcat7 but it is not going to be installed
 bbb-html5 : Depends: bbb-etherpad but it is not going to be installed
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).
......................................................./var/lib/dpkg/tmp.ci/preinst: line 282: /usr/share/etherpad-lite/APIKEY.txt: No such file or directory
dpkg: error processing archive /var/cache/apt/archives/bbb-etherpad_1%3a2.2.0-49_amd64.deb (--unpack):
 subprocess new pre-installation script returned error exit status 1
.../var/lib/dpkg/tmp.ci/preinst: line 282: /usr/share/etherpad-lite/APIKEY.txt: No such file or directory
dpkg: error processing archive /var/cache/apt/archives/bbb-etherpad_1%3a2.2.0-49_amd64.deb (--unpack):
 subprocess new pre-installation script returned error exit statu

**Comment by ffdixon** [comment]
Can you run the install again -- we just fixed this issue and it should now work.

**Comment by wrxcharger** [comment]
Thank you very much for your work. I was able to finish the installation, but it has bug in the mic test Say..... 

"Did you authorize the use of your microphone? Note that when you try to log in to the audio, you should be shown a dialog box in which your authorization is requested. If it didn’t happen try changing the permissions of your microphone in the configuration area of your browser."

Thanks Again!
Note : sorry for my english is very bad.. :(

**Comment by ffdixon** [comment]
Are you able to access your microphone on 

  https://test.bigbluebutton.org/

**Comment by wrxcharger** [comment]
Thanks Fred for ur answer....I don’t know what happened, I couldn’t do the
echo test with the mic, I didn’t call it, and today I try it again and it
works, I think it had some kind of delay in its processes.. send log for
you to see.. Thanks again.
