### ISSUE TITLE
500 internal error

### ISSUE THREAD

**Issue by WizardKid** [bigbluebutton/bbb-install#144]
Hi,
I was changing the logo in the UI and entered an incorrect url (http:example.com/path_to_image) and the application crashed. Can you point to the file where i can correct the (http:example.com/path_to_image)?

**Comment by WizardKid** [comment]
let me add that I have a customized greenlight

**Comment by GhaziTriki** [comment]
Please seek help in the forums https://groups.google.com/g/bigbluebutton-greenlight
