### ISSUE TITLE
Error 1006 on joining room

### ISSUE THREAD

**Issue by TriBallscom** [bigbluebutton/bbb-install#146]
I tried setup BBB several times on different platforms but every time I get stuck that when joining a room the Echo test fails with an error 1006.
Did another reinstall yesterday on a new server with the same result.
Installation with bbb-install.sh followed by Greenlight.
Everything checks out oke and no errors detected except audio not working. I tried to connect to the online BBB test environment and then it works so it's not my client computer.

**Comment by lakano** [comment]
Same problem here since the upgrade this w/e, we're stuck.
Could you help us please @TriBallscom ?

**Comment by caiado** [comment]
https://github.com/bigbluebutton/bigbluebutton/issues/8514#issuecomment-629802636

**Comment by caiado** [comment]
https://docs.bigbluebutton.org/2.2/troubleshooting.html#freeswitch-fails-to-bind-to-ipv4
