### ISSUE TITLE
kill $nc_PID  > /dev/null 2>&1; terminated with error

### ISSUE THREAD

**Issue by JoeShi** [bigbluebutton/bbb-install#151]
I have some issues when trying to use the script. And the issue occurs in the following part.
```
nc -l -p 443 > /dev/null 2>&1 &
nc_PID=$!
    
# Check if we can reach the server through it's external IP address
if nc -zvw3 $external_ip 443  > /dev/null 2>&1; then
    INTERNAL_IP=$IP
    IP=$external_ip
fi

kill $nc_PID  > /dev/null 2>&1;
```

The script first launch an `nc` listen process at the background and then launch the `nc` process to connect. My script exits at `kill $nc_PID  > /dev/null 2>&1;` with error. And I did a bit of test manually.

1. Open two terminals
1. run `nc -l -p 443` on one terminal
1. run `nc -zvw3 $external_ip 443` on the other terminal

I found the `nc -l -p 443` process exits immediately after one connection, so when it comes to kill the process by `kill $nc_PID `, we will have an error. 

cat /etc/os-release
```
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

nc -h
```
OpenBSD netcat (Debian patchlevel 1.187-1ubuntu0.1)
```

**Comment by GhaziTriki** [comment]
BigBlueButton moved to Ubuntu 20.04
