### ISSUE TITLE
Unable to locate packages for xenial

### ISSUE THREAD

**Issue by Denis30160** [bigbluebutton/bbb-install#152]
Is the ubuntu repo alive?
When i'm tying to start the script, i've got error message "Unable to locate packages for xenial-220 at ubuntu.bigbluebutton.org."
It seems that 80 and 443 ports is open on ubuntu.bigbluebutton.org
But no response there.
I've try different ISP (3 actually) and got same problem.

**Comment by MarwanSdeek** [comment]
I am facing the same problem on Ubuntu 16.04 LTS

**Comment by toto4ds** [comment]
read https://github.com/bigbluebutton/bbb-install Troubleshooting
Packaging server is blocked

**Comment by Denis30160** [comment]
I've solve this trouble. Its not bbb issue. Its problem with bbb hosting ISP. Some ISP block traffic from there. The solution is to use VPN or proxy .
