### ISSUE TITLE
BBB cluster using ScaleLite with Nginx-proxy

### ISSUE THREAD

**Issue by IamLuksha** [bigbluebutton/bbb-install#155]
Hello!

We are trying to deploy a BBB cluster using ScaleLite. Now each BBB server has an external ip address. But the number of servers is not enough for us now. It is necessary to increase their number. I would like to use the least number of external ip addresses.

The diagram below shows an example of what we want to do.
Let the external ip-addresses 20.20.20. * And the internal 172.16.2. *

Using
https://docs.bigbluebutton.org/2.2/setup-turn-server.html
https://docs.bigbluebutton.org/2.2/configure-firewall.html
https://github.com/bigbluebutton/bbb-install/issues/133
and other...

Nothing succeeded. TCP packets work, UDP not.

Please help configure BBB for such a scheme.
And is it even possible?
4 days trying to configure but nothing works. Web works, but no voice, webcams and screenshare.
In short, "Error during WebSocket handshake: Unexpected response code: 400"

Ready to report any current settings that are needed for help

![Untitled Diagram (1)](https://user-images.githubusercontent.com/18416207/79028351-52a4d100-7b98-11ea-95e3-1e8dfb277631.png)

**Comment by GhaziTriki** [comment]
Please use the forums for technical questions related to the core product [groups.google.com/forum/#!forum/bigbluebutton-dev](https://groups.google.com/forum/#!forum/bigbluebutton-dev)
