### ISSUE TITLE
[SOLVED] HTTP Status 404 error despite all bbb services running.

### ISSUE THREAD

**Issue by zenny** [bigbluebutton/bbb-install#16]
Hi,

Installed BBB with this script. 

```
# bbb-conf --status
red5: active
tomcat7: active
nginx: active
freeswitch: active
redis-server.service: active
bbb-apps-akka: active
bbb-transcode-akka: active
bbb-fsesl-akka: active
mongod: active
bbb-html5: active
bbb-webrtc-sfu: active
kurento-media-server: active
```

 But when I tried to connect to bbb-server from drupal bbb connector, the configuration were alright and drupal confirms connection to the server, but gives 404 error:

```
HTTP Status 404 - /bigbluebutton//api/join
type Status report

message /bigbluebutton//api/join

description The requested resource is not available.

Apache Tomcat/7.0.68 (Ubuntu)
```

However, I can reach bbb-demo instance without a problem.

Cheers,
/z

**Comment by zenny** [comment]
Seems like the back slash (/) at the end of the bbb URl needed ommision to solve problem:

```
https://bbb.example.com/bigbluebutton
```

**Comment by jacq0123** [comment]
Hello,
I'm having the same exact error described above. But, I don't know where is the url with the double back slash (//). 
Please advise,
Thanks!

**Comment by ffdixon** [comment]
On your server, enter the command

~~~
bbb-conf --secret
~~~

And use the URL to Mconf's excellent APImate to test your server.  Are you able to make API calls to the server with APImate?

**Comment by jacq0123** [comment]
Hello,
The server that I'm using for the testings is actually your server: URL: http://test-install.blindsidenetworks.com/bigbluebutton/. Could you please check on that?
Thanks!

**Comment by ffdixon** [comment]
@jacq0123 This issue tracker is for items related to installing BigBlueButton using `bbb-install.sh`.  Can you try setting up your own server using this script and let us know if it works with your front-end.
