### ISSUE TITLE
Uninstall script

### ISSUE THREAD

**Issue by ratondeau** [bigbluebutton/bbb-install#165]
I messed up two bbb servers. Original cause was that there was an wrong DNS-Entry for one of the server where I ran the install-script. It stopped while trying to verify certificate. After the correction of the DNS-Entry the script finished, but there were still wrong ip-Adresses in the configuration. Even after bbb-config --setip and restarts etc I get weird errors and the conference stops working after a couple of minutes.

**Comment by Entretoize** [comment]
I agree an uninstall script would bee cool, if you need to change the ip, the -setip doesn't change the ip everywhere and you need a fresh server !

**Comment by greenycat** [comment]
Joining issue. 
How to remove it completely for fresh installation?
