### ISSUE TITLE
greenlight installed with -g option but no ~/greenlight directory created

### ISSUE THREAD

**Issue by codegeek1001** [bigbluebutton/bbb-install#169]
I have a weird issue and wondering if anyone has any insights. I ran the bbb-install script exactly as this:

    wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v xenial-220 -s mydomain.com -e dev@mydomain.com -c coturn-server.mydomain.net:mypassword -g

Everything is working fine and I am able to launch greenlight correctly. however, I realized I need to edit the .env file for greenlight to make some changes but for some reason, the ~/greenlight directory was never created. What do I do to troubleshoot this ?

**Comment by codegeek1001** [comment]
Oops. Never mind. I was not logged in as "root" user. I did:

su -

then the directory showed up.

**Comment by mahdiyar1107** [comment]
whereis directories such app , bin , lib , tmp , vendor ,...???
