### ISSUE TITLE
greenlight without docker?

### ISSUE THREAD

**Issue by zenny** [bigbluebutton/bbb-install#17]
Hi,

I could not figure out to install greenlight without docker like in lxc containers?

Any inputs? Thanks.

Cheers,
/z

**Comment by ffdixon** [comment]
See

  http://docs.bigbluebutton.org/install/green-light.html#installing-greenlight-without-docker

**Comment by zenny** [comment]
@ffdixon  the above link is dead, however further referral at http://docs.bigbluebutton.org/install/greenlight-v2.html states that 
```
You can install Greenlight without Docker, however we don’t provide steps for doing this.
```
:(

Being vendor-specific (in this case docker) may not be the good symptom of a well-documented (next to FreeBSD and ArchLinux) open source project like bbb.

**Comment by ffdixon** [comment]
Updated the link in the v2 GreenLight docs:

  http://docs.bigbluebutton.org/install/greenlight-v2.html#greenlight-without-docker
