### ISSUE TITLE
Selecting -v xenial-225 returns an error

### ISSUE THREAD

**Issue by HakamSaffour** [bigbluebutton/bbb-install#170]
I want to install the latest version (2.2.5) of bbb using the following command:
 
`wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v xenial-225 -a`

Running the command with -v xenial-225 returns an error

> bbb-install: Unable to locate packages for xenial-225 at ubuntu.bigbluebutton.org.

I also tried from
`  -v xenial-221 to-v xenial-225 `
with the same error message

It seems that only the V 2.2.2 is uploaded to ubuntu.bigbluebutton.org

Any explanation?

**Comment by musznik** [comment]
try with **xenial-220-beta**

**Comment by HakamSaffour** [comment]
This is with
`wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v xenial-220 -a`

![image](https://user-images.githubusercontent.com/11553465/80308287-683c0c80-87ce-11ea-910a-cd7a9bf3cdf5.png)

And this is with
`wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v xenial-220-beta -a`

![image](https://user-images.githubusercontent.com/11553465/80308332-b81ad380-87ce-11ea-81c6-268be2c2270e.png)

**Comment by ffdixon** [comment]
Can you run 

~~~
wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v xenial-220 -a
~~~

again -- we just released BigBlueButton 2.2.6 yesterday, so you should get the same results for both commands.

**Comment by mtelgkamp** [comment]
I figured out you need to use `bbb-conf --check` on the server to show the current version number. The version given by `bbb-conf --version` is not the real version number in terms of `2.2.6`, for  `bbb-conf --version` the numbers after the `-` count the one before the dash only seem reference to the release 2.2 part and the 0 is never changed.

**Comment by HakamSaffour** [comment]
You are right @mtelgkamp  ... Thanks
![image](https://user-images.githubusercontent.com/11553465/80338719-56557a80-885d-11ea-8e1b-ee95dab8dd45.png)

By the way the greenlight is not updated (current Version 2.5.4 is 4 days old, but still it is not updated to V2.5.3)
![image](https://user-images.githubusercontent.com/11553465/80338764-738a4900-885d-11ea-8911-b9c4d2a6afdc.png)
any idea?

**Comment by HakamSaffour** [comment]
I updated the docker image of GreenLight using the following commands

```
cd ~/greenlight
docker pull bigbluebutton/greenlight:v2
docker-compose down
docker-compose up -d
```

Reference: http://docs.bigbluebutton.org/greenlight/gl-install.html#installing-on-a-bigbluebutton-server
