### ISSUE TITLE
blank default presentation

### ISSUE THREAD

**Issue by knnaveen007** [bigbluebutton/bbb-install#172]
so i downloaded my own presentation as a pdf file from google drive and overwrite the default.pdf file with my new file using following commad
mv -i starting.pdf default.pdf

after restarting bbb-conf there is no default presentation when I open the conference room.

please help.

**Comment by GremL1N** [comment]
check file permission to default.pdf

**Comment by GhaziTriki** [comment]
Please use the forums https://groups.google.com/forum/#!forum/bigbluebutton-dev
