### ISSUE TITLE
favicon.ico

### ISSUE THREAD

**Issue by knnaveen007** [bigbluebutton/bbb-install#173]
I replaced the favicon.ico file in /var/www/bigbluebutton-default/ with my own icon under the same name. but it is still showing the same icon. what else do I need to do after replacing it.

**Comment by GremL1N** [comment]
this is not install script issue.
If you use greenlight as frontend you need change favicon there.
changing `/var/www/bigbluebutton-default/` ypu may see when  join to room (html5-clinet)

**Comment by testprepturkey** [comment]
Hi,
I am using html5 client only, not the greenlight. I have the same problem too.

**Comment by shubhi903** [comment]
I replaced the favicon.ico file in /var/www/bigbluebutton-default/ with my own icon under the same name. but it is still showing the same icon. what else I need to do after replacing it.

**Comment by testprepturkey** [comment]
> I replaced the favicon.ico file in /var/www/bigbluebutton-default/ with my own icon under the same name. but it is still showing the same icon. what else I need to do after replacing it.

I am facing the same issue
