### ISSUE TITLE
Fresh installation of xenial-22 not starting up

### ISSUE THREAD

**Issue by kendrickluong** [bigbluebutton/bbb-install#180]
Hi,

Fresh installation of xenial-22 does not start up

# Potential problems described below never comes to and end
...............................................

/var/log/bigbluebutton/bbb-web.log:2020-04-27T09:40:40.619+10:00 WARN  i.l.c.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:6379
/var/log/bigbluebutton/bbb-web.log:2020-04-27T09:40:40.622+10:00 WARN  i.l.c.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:6379

**Comment by ffdixon** [comment]
Here's the documentation on how to best troubleshoot your installation issue:

  http://docs.bigbluebutton.org/2.2/troubleshooting.html#help-installing-bigbluebutton

**Comment by kendrickluong** [comment]
Sorry lots of head banging combination of issues

**Comment by ffdixon** [comment]
Just curious what were the issues (it might help others)?

**Comment by kendrickluong** [comment]
- I'm pretty sure the redis error is a false positive
- The fresh installation potential problems .... issue does not look like it goes away until you finish configuring it, in my case it was /opt/freeswitch/conf/vars.xml  <param name="ext-rtp-ip" value="$${external_rtp_ip}"/> <param name="ext-sip-ip" value="$${external_sip_ip}"/> after that bbb-conf --check would finally work and the start restart commands actually finish
- The more confusing part was bbb-conf --status showed that everything was online and bbb-conf --watch/--debug did not show significantly much
- In my previous installation i did not need to do hair pin nat, but i encountered an issue in this installation were https://domain/default.pdf could not be accessed
