### ISSUE TITLE
change to /usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml

### ISSUE THREAD

**Issue by PatrickHurley75** [bigbluebutton/bbb-install#182]
Hi,
Not sure if my own doing or a genuine error,  but lines 197-198 on that file seem to be contradictions. 
Mine has 197 uncommented but
I have a #- at the start of line 198. Should that be just <ipv4|ipv6> ?

**Comment by ffdixon** [comment]
Closing as not related to `bbb-install.sh`.  

Recommend posting to our bigbluebutton-dev mailing list for help.  See https://bigbluebutton.org/support.
