### ISSUE TITLE
 Unable to locate packages for xenial-22

### ISSUE THREAD

**Issue by rkhyd** [bigbluebutton/bbb-install#183]
hello
After this commit 9f685bce3bf94a7322bde33fb207bffcf0d1132f, the package was changed to 22 and i get this error now..
` Unable to locate packages for xenial-22 at ubuntu.bigbluebutton.org.`
Please fix it..

**Comment by to-kn** [comment]
i can second that - the repositories seem to be broken (since the "old" one does not work either...)

**Comment by Hannibal42** [comment]
Its the same for me.

**Comment by SamuelWei** [comment]
Having the same problem, with xenial-22 or xenial-220

**Comment by Darkensen** [comment]
Hello,

Same problem here

**Comment by pigman-84** [comment]
Same issue here.

**Comment by FPrefect42** [comment]
pls use 
` sudo wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -r packages-eu.bigbluebutton.org -v xenial-22 -a`
instead. its working for me

**Comment by Meth0d007** [comment]
bbb-install: Unable to locate packages for xenial-22 at packages-eu.bigbluebutton.org

**Comment by kabitk** [comment]
Please give a fix to update the repo - not only for installing. I don't want to break my current installation including modifications, setups, configs etc. Please give also an update for already installed instances that want to upgrade via apt-get update/upgrade.

**Comment by MudrekaBohra** [comment]
> pls use
> ` sudo wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -r packages-eu.bigbluebutton.org -v xenial-22 -a`
> instead. its working for me

this worked for me thank you

**Comment by FPrefect42** [comment]
> Please give a fix to update the repo - not only for installing. I don't want to break my current installation including modifications, setups, configs etc. Please give also an update for already installed instances that want to upgrade via apt-get update/upgrade.

maybe you can try to update the source-lsit under /etc/apt/ with the repository mentioened [here](url)

**Comment by kabitk** [comment]
xenial-220 as well as xenial-22 gives error 404
`E: Failed to fetch https://ubuntu.bigbluebutton.org/xenial-22/dists/bigbluebutton-xenial/main/binary-amd64/Packages  404  Not Found`

**Comment by julijane** [comment]
Hint: You also need to fetch the skript from packages-eu to get it running (at least that worked for me).

`sudo wget -qO- https://packages-eu.bigbluebutton.org/bbb-install.sh | bash -s -- -r packages-eu.bigbluebutton.org -v xenial-22 -a`

**Comment by ffdixon** [comment]
The `xenial-22` repository at `ubuntu.bigbluebutton.org` is now available again.

**Comment by chstappert** [comment]
still have the issue, that xenial-22 and xenial-220-beta is not available. It do not work for https://ubuntu.bigbluebutton.org or https://packages-eu.bigbluebutton.org... 

Is there an issue again?

**Comment by chanukyarajurs** [comment]
Hi

I am trying to install bigbluebutton on Ubuntu 16.4LTS external host using **bbb-install.sh**
Once the installation reaches the below lines, stays there doing thing forever..
Please let me know if am missing any dependencies.

> jsonpath@1.0.2 postinstall /usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/jsonpath
> node lib/aesprim.js > generated/aesprim-browser.js

> bufferutil@4.0.1 install /usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/bufferutil
> node-gyp-build

**> ws@0.4.32 install /usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/websocket-stream/node_modules/ws
**> (node-gyp rebuild 2> builderror.log) || (exit 0)****


Thanks
Chanu

**Comment by khunteebwar** [comment]
> 
> 
> The `xenial-22` repository at `ubuntu.bigbluebutton.org` is now available again.

still not working here. :( 
-------------------------
Err:15 https://ubuntu.bigbluebutton.org/xenial-220 bigbluebutton-xenial InRelease
  Connection timed out after 120000 milliseconds
Reading package lists...
W: Failed to fetch https://ubuntu.bigbluebutton.org/xenial-220/dists/bigbluebutton-xenial/InRelease  Connection timed out after 120000 milliseconds
W: Some index files failed to download. They have been ignored, or old ones used instead.
-------------------------

**Comment by ffdixon** [comment]
Are you by chance accessing from Russia?  Are you able to download it at the command line. 

```
wget  https://ubuntu.bigbluebutton.org/xenial-220/dists/bigbluebutton-xenial/InRelease
--2021-04-25 21:50:33--  https://ubuntu.bigbluebutton.org/xenial-220/dists/bigbluebutton-xenial/InRelease
Resolving ubuntu.bigbluebutton.org (ubuntu.bigbluebutton.org)... 167.99.180.121
Connecting to ubuntu.bigbluebutton.org (ubuntu.bigbluebutton.org)|167.99.180.121|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2533 (2.5K) [application/octet-stream]
Saving to: ‘InRelease’

InRelease                                          100%[==============================================================================================================>]   2.47K  --.-KB/s    in 0s      

2021-04-25 21:50:33 (209 MB/s) - ‘InRelease’ saved [2533/2533]
```
