### ISSUE TITLE
Issue with BBB 2.2.8 (1880). Non-writable area in the middle.

### ISSUE THREAD

**Issue by harishvasireddi** [bigbluebutton/bbb-install#186]
I had just installed BBB through install shell script and it installed BBB 2.2.8. I noticed that I am not able to start writing on presentation slide at the mid portion. I am including a snap highlighting the portion that I could not write on to. But there is no issue when I use full screen. Any solution for this problem. I didn't do any customization.

Is there a way I can go to BBB 2.2.6. That was working great.

![Not Able to Write Region](https://user-images.githubusercontent.com/26327312/80675987-64accc00-8ad3-11ea-9ced-69e6937bc712.png)

Thanks in advance
Harish

**Comment by ffdixon** [comment]
Fixed in BigBlueButton 2.2.9.  

 https://github.com/bigbluebutton/bigbluebutton/releases/tag/v2.2.9
