### ISSUE TITLE
TURN server not available

### ISSUE THREAD

**Issue by moan0s** [bigbluebutton/bbb-install#187]
I wanted to install a TURN server with the script. I executed 
`wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -c turn.hyteck.de:notsosecret -e certbot@hyteck.de`
on a fresh installed Ubuntu 18.04 V-Server from [Strato](https://www.strato.de/) as root.

The process finished with
```
# This TURN server is ready.  To configure your BigBlueButton server to use this TURN server, 
# add the option

```

But when I want to check if the TURN server is working I get nothing (also there seems to be no process running).

My BBB-installation does not use this TURN server correctly.

This is how I check if the TURN server is working (as TURN also shuld implement STUN in my understanding?):
```
$ stun turn.hyteck.de
STUN client version 0.97
Primary: Blocked or could not reach STUN server	
Return value is 0x00001c
```

I am looking for any advice on how to debug this.

Please feel also free to check the server with the given credentials.

PS: Additional information:

UFW is not (yet) installed

This is the log of journalctl -xe after systemctl restart coturn
```
-- Subject: Unit coturn.service has begun shutting down
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit coturn.service has begun shutting down.
Apr 30 16:47:57 h2875483.stratoserver.net coturn[4660]:  * Stopping coturn turnserver
Apr 30 16:47:57 h2875483.stratoserver.net coturn[4660]:    ...done.
Apr 30 16:47:57 h2875483.stratoserver.net systemd[1]: Stopped LSB: coturn TURN Server.
-- Subject: Unit coturn.service has finished shutting down
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit coturn.service has finished shutting down.
Apr 30 16:47:57 h2875483.stratoserver.net systemd[1]: Starting LSB: coturn TURN Server...
-- Subject: Unit coturn.service has begun start-up
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit coturn.service has begun starting up.
Apr 30 16:47:57 h2875483.stratoserver.net coturn[4666]:  * Starting coturn  turnserver
Apr 30 16:47:57 h2875483.stratoserver.net coturn[4666]:    ...done.
Apr 30 16:47:57 h2875483.stratoserver.net systemd[1]: Started LSB: coturn TURN Server.
-- Subject: Unit coturn.service has finished start-up
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit coturn.service has finished starting up.
-- 
-- The start-up result is RESULT.

```

```
$ nmap turn.hyteck.de
Nmap scan report for turn.hyteck.de (81.169.166.60)
Host is up (0.041s latency).
Other addresses for turn.hyteck.de (not scanned): 2a01:238:42d8:3600:e83e:7585:d850:6399
rDNS record for 81.169.166.60: h2875483.stratoserver.net
Not shown: 995 closed ports
PORT     STATE    SERVICE
22/tcp   open     ssh
25/tcp   filtered smtp
139/tcp  filtered netbios-ssn
445/tcp  filtered microsoft-ds
9876/tcp filtered sd
```

**Comment by GerJuli** [comment]
Manually starting the server fails too:
The log says:
```
0: turn server id=14 created
socket: Protocol not supported
socket: Protocol not supported
bind: Address already in use
0: Trying to bind fd 45 to <127.0.0.1:443>: errno=98
Cannot bind local socket to addr: Address already in use
0: Cannot bind TLS/TCP listener socket to addr 127.0.0.1:443
0: Trying to bind TLS/TCP listener socket to addr 127.0.0.1:443, again...
Cannot create relay thread
: Resource temporarily unavailable

```
Full log:
https://pastebin.com/uvFPh1yF

**Comment by lonesomewalker** [comment]
Maybe you should realize that the turn server can't run on the same machine as the BBB server?

**Comment by GerJuli** [comment]
As described in the issue I tried to install coturn on a fresh ubuntu 18.04 server. There was nothing else installed on this server (so also no BBB server)
The only thing I changed was the support of IPv6 that was missing:
New log of a manual coturn start is here: https://pastebin.com/YZ4TZbgT

**Comment by lonesomewalker** [comment]
I recommend that you shouldn't just copy stuff, instead use a REAL/dedicated TURN server.
This can be achieved as shown on the docs page (not like you did...)
https://docs.bigbluebutton.org/2.2/setup-turn-server.html#setup-a-turn-server

**Comment by GerJuli** [comment]
The bbb-install script offers the option to set up a TURN server. What I try to do is to report an issue, that this does not work for me. I hope to improve the bbb-install script by reporting this and describing what my problems are.
Of course I work with other solutions to set up a (co-)turn server and I already did that. But that is not the point of the issue.

**Comment by mabras** [comment]
Hi @moan0s,

I am having the same problem. Did you manage to solve it.

Thanks,

**Comment by michi-80337** [comment]
Fresh server instances from hosters often have a web server like Apache httpd or Nginx preinstalled. The easiest way to check is to issue a
```
$ netstat -eanp --ip
```
and look, if TCP ports 80 and/or 443 are already occupied by another process.

The current version of the install script already has a check for Apache2 built in, but it fails for other web servers.

**Comment by moan0s** [comment]
Hi I did not solve it sadly and do not run a turn (or BBB) server anymore. Sorry. As I will not be providing any feedback I will close this issue
