### ISSUE TITLE
Unhandled curl error: SSL: no alternative certificate subject name matches target host name

### ISSUE THREAD

**Issue by Entretoize** [bigbluebutton/bbb-install#190]
I changed my domain name and re-ran the bbb-install script now I receive that error when trying to use the php api:

Fatal error: Uncaught RuntimeException: Unhandled curl error: SSL: no alternative certificate subject name matches target host name 'olddomain.tld' in /var/www/vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php:480 Stack trace: #0 /var/www/vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php(108): BigBlueButton\BigBlueButton->processXmlResponse('https://classev...', '') #1 /var/www/bigbluebutton-default/test.php(22): BigBlueButton\BigBlueButton->createMeeting(Object(BigBlueButton\Parameters\CreateMeetingParameters)) #2 {main} thrown in /var/www/vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php on line 480

I tried to run certbot --nginx and it recreated a certificate but I still have the same error.

**Comment by tykayn** [comment]
hi, i am running on the same error, can you explain how you solved it ?
BBB requires to setup a local IP such as 192.168.1.10, so how can i set it up to have a nice certificate working also for my public ip bbb.mydomain.org ?

**Comment by Entretoize** [comment]
I'm very sorry I don't remember, maybe I cleared everything and retried from scratch...
