### ISSUE TITLE
Some ubuntu 16.04 images dont have "dig" 

### ISSUE THREAD

**Issue by hostbbb** [bigbluebutton/bbb-install#2]
script failed on base distro, unable to find dig command.

needed to run 

sudo apt-get install dnsutils

then script started fine.

should check for dig and install.

this is neat utility :)

**Comment by ffdixon** [comment]
Thanks for pointing this out.  Fixed
  
  https://github.com/bigbluebutton/bbb-install/commit/01acc2b3a743847cab31a6291e70b9d21cf37602
