### ISSUE TITLE
Install html5 without ssl in the virtualbox

### ISSUE THREAD

**Issue by bijism** [bigbluebutton/bbb-install#20]
Hi can i install html5 version with BBB-install without SSL?
Because I want to install BBB on Virtualbox and do not need to set up Domain or ssl.

**Comment by ffdixon** [comment]
You can try removing the check for SSL here

  https://github.com/bigbluebutton/bbb-install/blob/master/bbb-install.sh#L147

We recommend using SSL as that's what you need for WebRTC audio/video on Chrome.

**Comment by bijism** [comment]
Thank you for your reply
We want to use BBB on an organization that does not have Internet access.
And we need to install it on a Virtualbox
That is why we can not use ssl for this scenario.
Yes, we are aware that one of the requirements is to use ssl in chrome
Please help us if you have any suggestions for the above scenario
Thank you

**Comment by ffdixon** [comment]
You need to download the bbb-install.sh script first, edit it, and then run it locally.  You can also edit the first line

~~~
#!/bin/bash -ex
~~~

and try running it locally

~~~
./bbb-install.sh -v xenial-200 -t
~~~

and you'll see each of the command as they are executed (and where it stops).

**Comment by ffdixon** [comment]
Closing -- don't hesitate to reach out if you need any more help.
