### ISSUE TITLE
bbb-install: You must run this command on Ubuntu 16.04 server.

### ISSUE THREAD

**Issue by anandcomputergyaan** [bigbluebutton/bbb-install#203]
root@vmi382632:~# wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v xenial-220-beta
Warning: apt-key output should not be parsed (stdout is not a terminal)
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
SSH_CONNECTION=49.15.67.42 7079 95.111.237.217 22
LESSCLOSE=/usr/bin/lesspipe %s %s
LANG=en_US.UTF-8
XDG_SESSION_ID=30
USER=root
PWD=/root
HOME=/root
SSH_CLIENT=49.15.67.42 7079 22
DEBIAN_FRONTEND=noninteractive
SSH_TTY=/dev/pts/0
MAIL=/var/mail/root
SHELL=/bin/bash
TERM=xterm
SHLVL=2
LOGNAME=root
XDG_RUNTIME_DIR=/run/user/0
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
LESSOPEN=| /usr/bin/lesspipe %s
_=/usr/bin/env
bbb-install: You must run this command on Ubuntu 16.04 server.

**Comment by basisbit** [comment]
a) use Ubuntu 16.04, other distributions are not supported yet
b) don't try to install the 2.2.x beta. Please read the README.md of this repository on how to use the script.

**Comment by vlasov01** [comment]
Hi,

I've got the same error on 18.04. Is it supported?

_=/usr/bin/env
+ '[' xenial == xenial ']'
+ check_ubuntu 16.04
++ lsb_release -r
++ sed 's/^[^0-9]*//g'
+ RELEASE=18.04
+ '[' 18.04 '!=' 16.04 ']'
+ err 'You must run this command on Ubuntu 16.04 server.'
+ say 'You must run this command on Ubuntu 16.04 server.'
+ echo 'bbb-install: You must run this command on Ubuntu 16.04 server.'
bbb-install: You must run this command on Ubuntu 16.04 server.
+ exit 1

**Comment by vlasov01** [comment]
OK. Ubuntu 18.04 is not yet supported as of May 14th 2020..

**Comment by ffdixon** [comment]
We're working towards making an early beta of BigBlueButton 2.3 (on Ubuntu 18.04) available soon.  It will still be under active development, not recommended for production, but will enable us to tap into the community to help test it earlier and give us feedback.

We'll announce to bigbluebutton-dev when we BigBlueButton 2.3 beta ready for others to try out.

**Comment by YonelaNuba** [comment]
I am also getting the same problem:

When I try `xenial-22` it shows that I should run this command on Ubuntu 16.04 server.

When I try `bionic-23` It shows that I would run this command on Ubuntu 18.04 server.

I am using Ubuntu 20.04 I want to check if it is supported?

**Comment by ffdixon** [comment]
We don't support Ubuntu 20.04 yet on BigBlueButton.   The upcoming 2.4 will require 18.04.  We expect to move to 20.04 in a future version.

Closing this issue.  Please follow https://github.com/bigbluebutton/bbb-install/issues/244.
