### ISSUE TITLE
Instaling Bbb-install With VPS

### ISSUE THREAD

**Issue by sigittechno** [bigbluebutton/bbb-install#206]
Hello i am a new to install bigbluebutton

Please let me know
I have Vps, does that need to install Panel again? Or don't install anything Panel?

Example : i was install Webuzo Cpanel on my Vps n then i install bbb-instal.sh with Ssh , 

does it problem?
Let me know,

Thanks so much

**Comment by basisbit** [comment]
Please do not install BBB on a VPS. It will only work with bad quality and low users numbers. Trust me, you'll just make your users annoyed when using a VPS for this. Instead, consider renting a bare metal / dedicated server or at least a server for latency-sensitive applications with dedicated CPU cores. It should have between 4 to 12 physical CPU cores (Hyper Threading cores don't count) and between 8 to 32 GB RAM. see https://docs.bigbluebutton.org/2.2/install.html#minimum-server-requirements

The Server has to run Ubuntu 16.04 and thus, nothing CPanel or similar. I hope this answers your question or helps you.

For further install support questions, please use the forum / mailing list at https://groups.google.com/forum/#!forum/bigbluebutton-setup

**Comment by sigittechno** [comment]
thanks very much for your information, let me guess for RAM , that is
enough for 4GB or 8 GB? thanks

**Comment by TheNomad11** [comment]
it works fine with 4GB and 2 CPU cores on a VPS for small groups.

**Comment by ha3ant** [comment]
> Please do not install BBB on a VPS. It will only work with bad quality and low users numbers. Trust me, you'll just make your users annoyed when using a VPS for this. Instead, consider renting a bare metal / dedicated server or at least a server for latency-sensitive applications with dedicated CPU cores. It should have between 4 to 12 physical CPU cores (Hyper Threading cores don't count) and between 8 to 32 GB RAM. see https://docs.bigbluebutton.org/2.2/install.html#minimum-server-requirements
> 
> The Server has to run Ubuntu 16.04 and thus, nothing CPanel or similar. I hope this answers your question or helps you.
> 
> For further install support questions, please use the forum / mailing list at https://groups.google.com/forum/#!forum/bigbluebutton-setup

Dear basisbit,
I have one greater physical server with 48 Intel 2650 cores CPU and 128 Gb Ram. I had installed BBB on it, when the concurrent users reach to ~250 the errors come! the user kicked out of meetings and the new users waiting to join and the others get 401 unauthorized!
So I decide to: divide my machine resources into 3 VM like this:
16 core CPU Intel 2650 and 41GB Ram, when I have 10 meetings with 25 people on each (total concurrent users 250) the users get the error and waiting much time to enter rooms, the current users just kicked out of meetings, and audio gets reduce quality and like robots!
smoothly and almost the same result just with ~50 users difference!
I checked Nginx log files and see this error:
connect() failed (111: Connection refused) while connecting to upstream, client:
(I had 1 GB Network card on this machine)
Is there any extra config for Nginx or Esxi virtualization or other things?!

**Comment by ha3ant** [comment]
Thank you for your replay, how about to enable hyperthreading? is there any difference?

**Comment by basisbit** [comment]
yes, hyperthreading will make it slightly worse, because less CPU time for the single-threaded event-handling

**Comment by ha3ant** [comment]
Oh, on-time advice :)
And what's your idea about Intel 2620 with 24 cores? split it to two VMs can get more concurrent users?
And finally, what's your idea about these Nginx.log errors:
"connect() failed (111: Connection refused) while connecting to upstream, client: ..."
We don't need any Nginx config for getting better performance?

**Comment by basisbit** [comment]
stop it, use the forum for support, not the issue tracker. Your questions is not about a technical issue in bbb-install script.

**Comment by ffdixon** [comment]
Please open a thread in [bigbluebutton-setup](https://groups.google.com/forum/#!forum/bigbluebutton-setup) as you'll get a wider audience for this discussion.

If we find in the discussion there is an problem/feature with BigBlueButting that needs to be implemented, we can open an issue here to track it.

**Comment by ha3ant** [comment]
Would you please let me join Group, request sent.

**Comment by shivam5th** [comment]
Hi, 
Current minimum system requirement for installing BigBlueButton on Ubuntu VPS
4 CPU cores/8 GB of memory
Installation on a local VM container
50G of disk space
IPV4 address only

You can check [this tutorial](https://technoracle.com/install-bigbluebutton-on-ubuntu-20-04/), it may helps

**Comment by ffdixon** [comment]
We would recommend checking the official docs

  https://docs.bigbluebutton.org/administration/install
