### ISSUE TITLE
ERROR :: Gem::ConfigMap

### ISSUE THREAD

**Issue by pbdco** [bigbluebutton/bbb-install#208]
Getting this error during install. After this, this will be shown in every BBB log. Seems a major issue

Installing ri documentation for builder-3.2.4
Done installing documentation for builder after 1 seconds
1 gem installed
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.

**Comment by pbdco** [comment]
As you can see here ( bbb-record --watch )

timers listed.
--
    bbb-rap-archive-worker.service - BigBlueButton recording and playback archive worker
   Loaded: loaded (/usr/lib/systemd/system/bbb-rap-archive-worker.service; static; vendor preset: enabled)
   Active: inactive (dead) since Tue 2020-05-12 17:23:49 UTC; 19s ago
  Process: 6215 ExecStart=/usr/local/bigbluebutton/core/scripts/rap-archive-worker.rb (code=exited, status=0/SUCCESS)
 Main PID: 6215 (code=exited, status=0/SUCCESS)

May 12 17:23:48 web rap-archive-worker.rb[6215]: /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
May 12 17:23:48 web rap-archive-worker.rb[6215]: /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated
May 12 17:23:48 web rap-archive-worker.rb[6215]: /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: constant Gem::ConfigMap is deprecated
May 12 17:23:48 web rap-archive-worker.rb[6215]: /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
May 12 17:23:48 web rap-archive-worker.rb[6215]: /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
May 12 17:23:48 web rap-archive-worker.rb[6215]: /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
May 12 17:23:48 web rap-archive-worker.rb[6215]: /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
May 12 17:23:48 web rap-archive-worker.rb[6215]: /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
May 12 17:23:48 web rap-archive-worker.rb[6215]: /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
May 12 17:23:48 web rap-archive-worker.rb[6215]: /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated

    bbb-rap-sanity-worker.service - BigBlueButton recording and playback sanity check worker
   Loaded: loaded (/usr/lib/systemd/system/bbb-rap-sanity-worker.service; static; vendor preset: enabled)
   Active: inactive (dead) since Tue 2020-05-12 17:22:43 UTC; 1min 25s ago
Condition: start condition failed at Tue 2020-05-12 17:23:48 UTC; 21s ago
           ConditionPathExistsGlob=/var/bigbluebutton/recording/status/archived/*.done was not met
  Process: 4832 ExecStart=/usr/local/bigbluebutton/core/scripts/rap-sanity-worker.rb (code=exited, status=0/SUCCESS)
 Main PID: 4832 (code=exited, status=0/SUCCESS)

May 12 17:22:43 web rap-sanity-worker.rb[4832]: /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
May 12 17:22:43 web rap-sanity-worker.rb[4832]: /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated
May 12 17:22:43 web rap-sanity-worker.rb[4832]: /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: constant Gem::ConfigMap is deprecated
May 12 17:22:43 web rap-sanity-worker.rb[4832]: /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
May 12 17:22:43 web rap-sanity-worker.rb[4832]: /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
May 12 17:22:43 web rap-sanity-worker.rb[4832]: /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
May 12 17:22:43 web rap-sanity-worker.rb[4832]: /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
May 12 17:22:43 web rap-sanity-worker.rb[4832]: /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
May 12 17:22:43 web rap-sanity-worker.rb[4832]: /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
May 12 17:22:43 web rap-sanity-worker.rb[4832]: /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated

    bbb-rap-process-worker.service - BigBlueButton recording and playback process worker
   Loaded: loaded (/usr/lib/systemd/system/bbb-rap-process-worker.service; static; vendor preset: enabled)
   Active: inactive (dead) since Tue 2020-05-12 17:23:22 UTC; 46s ago
Condition: start condition failed at Tue 2020-05-12 17:23:48 UTC; 21s ago
           ConditionPathExistsGlob=/var/bigbluebutton/recording/status/sanity/*.done was not met
  Process: 4868 ExecStart=/usr/local/bigbluebutton/core/scripts/rap-process-worker.rb (code=exited, status=0/SUCCESS)
 Main PID: 4868 (code=exited, status=0/SUCCESS)

May 12 17:23:16 web rap-process-worker.rb[4868]: /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
May 12 17:23:16 web rap-process-worker.rb[4868]: /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated

**Comment by ffdixon** [comment]
You can ignore the warnings.  They will go away in BigBlueButton 2.3 (ubuntu 18.04).
