### ISSUE TITLE
Does not pass from the local network through a proxy

### ISSUE THREAD

**Issue by maxlavr83** [bigbluebutton/bbb-install#21]
Installed BigBlueButton with all the add-ons in the automatic mode through your script.
As a result, the server works and you can connect to it without problems from the external network, but you can not connect from computers from the company's local network.
The local network is going to the Internet through the Forefront TMG proxy and apparently the problem is in the proxy, since 1) if you connect without it, there are no problems and 2) when you try to connect, the answer is about the timeout of waiting from it.
We set up a rule for the Forefront TMG test to skip "everything and everything" (all ports, all sites) - still does not let BigBlueButton pass to the server.
Tell me, please, in which direction to dig? How to configure a proxy or the server itself to end up on the server from a local network through Forefront TMG?

**Comment by ffdixon** [comment]
When connecting from within a lan, you need to use the external fully qualified domain name. 

However, we don't have a lot of experience running BigBlueButton behind a proxy.  We have detailed steps of running BigBlueButton behind a firewall, see

   http://docs.bigbluebutton.org/install/install.html#configuring-bigbluebutton-behind-a-firewall

Recommend you post this message our bigbluebutton-setup mailing list, see https://bigbluebutton.org/support.  There is a good chance there are others in the forum that may have setup BigBlueButton for access behind a firewall as well.
