### ISSUE TITLE
Do not have static IP

### ISSUE THREAD

**Issue by tushrkhrbkr** [bigbluebutton/bbb-install#212]
I do not have static external IP. On every change to IP, everything goes wrong. I have to do complete setup every time. Is there any way to change external IP through script or something like that

**Comment by evanmn** [comment]
This is not possible. You mention external IP, so I assume you are trying to host either at home behind a NAT or on GCP. If you are at home, there is nothing you can do about this directly. Your external IP is assigned by your ISP. You could contact your ISP (mine have given me a free static IP) but there are no guarantees. When your external IP changes, your FQDN will no longer point to your server. Hosting anything on a dynamic IP **is a bad idea and should be avoided at all costs** unless you are prepared to take extra precautions to avoid downtime, which there will be.

**Comment by chrishdx** [comment]
I also had the problem and solved it with a python script.

first i create a virtual adapter in 

/etc/network/interfaces

auto ens160:1
iface ens160:1 inet static
        address 187.255.216.185
        netmask 255.255.255.248

then I installed netifaces & requests with pip install and then simply run the script via crontab every 5 minutes as soon as the WAN IP changes, it changes all IPs and restarts the server

My Script:

#!/usr/bin/env python

import netifaces as ni
import os
import time

ni.ifaddresses('ens160:1')
lokal = ni.ifaddresses('ens160:1')[ni.AF_INET][0]['addr']

import requests
wan = requests.get('http://ipinfo.io/json').json()['ip']

def bearbeiten(lokaleip, wanip, datei):

        fin = open(datei, "rt")
        #read file contents to string
        data = fin.read()
        #replace all occurrences of the required string
        data = data.replace(lokaleip, wanip)
        #close the input file
        fin.close()
        #open the input file in write mode
        fin = open(datei, "wt")
        #overrite the input file with the resulting data
        fin.write(data)
        #close the file
        fin.close()


if lokal != wan:
        bearbeiten(lokal,wan,"/etc/network/interfaces")
        bearbeiten(lokal,wan,"/opt/freeswitch/etc/freeswitch/vars.xml")
        bearbeiten(lokal,wan,"/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml")
        bearbeiten(lokal,wan,"/etc/bigbluebutton/nginx/sip.nginx")
        bearbeiten(lokal,wan,"/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml")
        bearbeiten(lokal,wan,"/etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini")
        bearbeiten(lokal,wan,"/lib/systemd/system/dummy-nic.service")
        print time.strftime("%d.%m.%Y %H:%M:%S") + 'IP Adressen wurden geeandert'
        os.system('reboot')
else:
        print time.strftime("%d.%m.%Y %H:%M:%S") + ' keine Aenderungen erfoderlich'
