### ISSUE TITLE
bbb-install installs approx. 90 kernel packages

### ISSUE THREAD

**Issue by bitmuster** [bigbluebutton/bbb-install#218]
Hi all,
on one of my test systems, probably all 4.4.0-* kernels got installed from the script.

e.g. these and others:
linux-image-4.4.0-83-generic
linux-image-4.4.0-87-generic
linux-image-4.4.0-9019-euclid
linux-image-4.4.0-9020-euclid
linux-image-4.4.0-9021-euclid
linux-image-4.4.0-9022-euclid    
...
root@***server.de:~# dpkg -l | grep linux | wc
    198    2985   31786

In the script in line 638 see a line that calls apt-get install with linux-image-extra-$(uname -r).
That line probably causes all the kernels to be selected by apt.

The server is hosted at 1blu.de and has Ubuntu 16.04.6 LTS installed.

A difference, that I've observed compared to a server at another hoster is that that 'uname -r' responds with 4.4.0 and not with e.g. 4.4.0-179-generic. Apart from that I'm still trying to figure out what is going wrong here.

Here is the output of uname:
root@***server.de:~# uname -r
4.4.0
root@***server.de:~# uname -a
Linux ***-server.de 4.4.0 #1 SMP Mon Mar 16 15:39:59 MSK 2020 x86_64 x86_64 x86_64 GNU/Linux

Any ideas what is going wrong here?

**Comment by iam-TJ** [comment]
This is likely due to the hosting environment using either:

1) A custom-built kernel built by the hosting company for their virtual machines
2) A container-based deployment where all containers share the host kernel, which is built by the hosting company

**Comment by bitmuster** [comment]
sorry for the long answer delay.
I had to reinstall the machine and stumbled on that issue again. Indeed, the regex selects far too many images.
Also, the output of uname -r seems to differ sometimes.

I've added some code to bbb-install.sh to detect the issue and ask the user have a look
["https://github.com/bigbluebutton/bbb-install/compare/master...bitmuster:virtual-1blu"](https://github.com/bigbluebutton/bbb-install/compare/master...bitmuster:virtual-1blu)

This worked for me:

Change in bbb-install.sh:
    #PATTERN=$(uname -r)
    PATTERN="4.4.0-142-generic"

Install
    $ wget https://raw.githubusercontent.com/bitmuster/bbb-install/virtual-1blu/bbb-install.sh
    $ ./bbb-install.sh -w -a -v xenial-22 -s bbb.example.com -e

**Comment by kepstin** [comment]
Current versions of bbb-install no longer attempt to install any "linux-image" packages.
