### ISSUE TITLE
bbb-install check_host fails with CNAME dns entry

### ISSUE THREAD

**Issue by pielonet** [bigbluebutton/bbb-install#23]
Hi,
in bbb-install.sh the function check_host checks if ifconfig IP address matches dns entry for the host.

This test fails if the DNS entry is a CNAME since `dig -short my.domain.tld` returns two lines, the first one being the cnamed domain and the second one the IP.

Cheers,
Thierry

**Comment by ffdixon** [comment]
Thanks @pielonet for the feedback.  We only tested it with A Names.  Need to enhance the script so it does not fail with a CNAME.

**Comment by ffdixon** [comment]
We made some updates to the script dig only extracts the IP address. 

  https://github.com/bigbluebutton/bbb-install/blob/master/bbb-install.sh#L262

Let us know if you run into any further issues.
