### ISSUE TITLE
BBB install on Ubuntu 18.04 it is possible ? or no 

### ISSUE THREAD

**Issue by Inv0k-er** [bigbluebutton/bbb-install#232]
BBB install on Ubuntu 18.04 it is possible ? or no I don't understand when i reded guide i have not found some information and guide.
[https://docs.bigbluebutton.org/support/faq.html#process](url)
Just Ubuntu 16.04 no one line  how to install on Ubuntu 18.04. 
And I want to ask about html version. Do you have a some guide ?

**Comment by ffdixon** [comment]
We're working on releasing BigBlueButton 2.3-beta which will run on Ubuntu 18.04.  Look for the announcement in our [bigbluebutton-dev](https://groups.google.com/g/bigbluebutton-dev) mailing list.

**Comment by Inv0k-er** [comment]
Thank for your answer.
But maybe you can help me. What in docker file need to add for use BBB in html mod.

**Comment by Krautmaster** [comment]
16.04 minimal install is not even working any more, no idea why but even the standard packages are broken. Its time to shift towards 18.04, wondering when we will se ethe 2.3 beta finally...

**Comment by pyloor** [comment]
@Krautmaster please provide the error you got.

**Comment by Krautmaster** [comment]
its solved. The ubuntu wegsite links an old and buggy mini.iso image for 16.04. There is a new one in the web out there which installes seemless.

**Comment by wdfee** [comment]
In the google group discussion list I read that moving to 20.04 straight forward is already discussed. I really hope that the 2.3 release will target Ubuntu 20.04. #244

**Comment by ffdixon** [comment]
We're targeting 18.04 for 2.3-dev.  See: https://docs.bigbluebutton.org/dev/dev23.html
