### ISSUE TITLE
bbb-install: Did not detect nodejs 8.x candidate for installation

### ISSUE THREAD

**Issue by TheDiversity** [bigbluebutton/bbb-install#233]
I tryed to install a test client in a vm and a fresh ubuntu installation. I use your bbb-install.sh but it lead to the error message from title. It seems for me nodejs 8.x is to old to get installed in this way.

Here the Pre-installation checks (if needed)

cat /etc/default/locale -> LANG="en_US.UTF-8" LANGUAGE="en_US:"
sudo systemctl show-environment -> LANG=en_US.UTF-8

cat /etc/lsb-release -> DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"
uname -m -> x86_64

ip addr | grep inet6 - > IP is fine
uname -r -> 4.4.0-142-generic

**Comment by TheDiversity** [comment]
I try to do run [ curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash ] - and create the file "/etc/apt/sources.list.d/nodesource.list"  with folowing content:

deb https://deb.nodesource.com/node_8.x xenial main
deb-src https://deb.nodesource.com/node_8.x xenial main

But its bring an new error now "E: There were unauthenticated packages and -y was used without --allow-unauthenticated" and after that a lot of dots for a long time. Or maybe its  a normal behavior?

**Comment by voicerecordist** [comment]
after this, i get SSL error
I checked my domain SSL's and its ok. any idea?

**Comment by matinwd** [comment]
Same here
Any idea

**Comment by GhaziTriki** [comment]
Outdated as nodejs 8 is no more maintained.
