### ISSUE TITLE
Load Balancing using scalelite [help]

### ISSUE THREAD

**Issue by siddhartha-lal** [bigbluebutton/bbb-install#234]
Do all the BBB servers being serviced by a load balancer need to have public IP addresses? Or is it possible to set up the system using just one public IP for the load balancer?

Any help would be appreciated. Thanks.

**Comment by lonesomewalker** [comment]
If the BBB servers are accessible from Scalelite AND users, there should be no problem.
Scalelite checks for availability, and your clients need to be able to connect DIRECTLY to a BBB server.

**Comment by GhaziTriki** [comment]
A public IP address is required for WAN or LAN.
