### ISSUE TITLE
bbb-install doesn't upgrade from 2.2.3 to latest (2.2.20).

### ISSUE THREAD

**Issue by lonesomewalker** [bigbluebutton/bbb-install#243]
Is there a known issue why it won't upgrade directly from 2.2.3 to 2.2.20?

**Comment by ffdixon** [comment]
It should -- can you share more information on what issues you encountered?

**Comment by lonesomewalker** [comment]
Sorry for the delayed answer.

Basic install as always, upgrade done by bbb-install.sh
After upgrade (without errors) still 2.2.3 instead of 2.2.20.

Tried it several times, finally installed a fresh machine.
Next time we'll save a debug log, i promise!

**Comment by lonesomewalker** [comment]
Finally able to reproduce :-)

For all the people who have the same issue:
```dpkg --configure -a```

This rarely happens when there was a broken installation before.
So there is a package missing configuration, which can be done simply manually.
After this, updates work as expected.

**Comment by ffdixon** [comment]
Thanks for sharing this -- added it to the end of the README.md in case others run into this issue.
