### ISSUE TITLE
Support for 20.04?

### ISSUE THREAD

**Issue by greavette** [bigbluebutton/bbb-install#244]
Hello Team,

Thanks very much for making this script available.  Is there any roadmap to have this script support Ubuntu 20.04?

Thank you.

**Comment by pgenderson** [comment]
Make a feature request. I thought I already did that but apparently not.

**Comment by ffdixon** [comment]
We do plan to make BigBlueButton run on 20.04, but we'll get 2.3-dev running on 18.04 first.

**Comment by Kreijstal** [comment]
Following this thread now.

**Comment by Re3os** [comment]
root@conference:/home# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.4 LTS"


Error: bbb-install: You must run this command on Ubuntu 18.04 server.
Config:  root@conference:/home# wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v bionic-24 -s domen.com -e example.com

**Comment by ffdixon** [comment]
You need to use `bbb-install-2.5.sh`, see https://docs.bigbluebutton.org/2.5/install.html#install.
