### ISSUE TITLE
net-tools missing for 2.3-dev (fresh 18.04LTS)

### ISSUE THREAD

**Issue by maron2000** [bigbluebutton/bbb-install#248]
I installed bbb 2.3 dev using bbb-install.
bbb-conf complains that ifconfig is missing, therefore it would be better that the script installs net-tools.

**Comment by maron2000** [comment]
Since I find no improvements, I'd like to clarify the above-mentioned problem.

Problem: `ifconfig` command missing when executing `bbb-install.sh` or `bbb-conf --check` on Ubuntu 18.04LTS.

Suggestion: `ifconfig` is not installed on 18.04LTS by default, therefore, add a line in bbb-install.sh to install net-tools package.

**Comment by ffdixon** [comment]
Can you send us a pull request for this -- thanks!

**Comment by maron2000** [comment]
@ffdixon 
I managed to send a pull request.
It was my first time to do so, so please tell me if there is something wrong in sending a request.

> Can you send us a pull request for this -- thanks!

**Comment by pgenderson** [comment]
I thought bbb-install.sh refused to install if you're not on Ubuntu Server 16.
