### ISSUE TITLE
How to install bigbluebutton v2.2.2x (v2.2.20) from bbb-install.sh? #10168

### ISSUE THREAD

**Issue by longlnk** [bigbluebutton/bbb-install#249]
Hello,
Can I install bigbluebutton v2.2.20 from bbb-install.sh?
I currently install it from the software to the latest version v2.2.21
![install](https://user-images.githubusercontent.com/15074179/89029645-1a005180-d359-11ea-8307-bed2ec20f931.png)
I'm developing on and using version 2.2.20, because it's stable
Please help me.

**Comment by sreegithck** [comment]
to downgrade to 2.2.20 the following command can be used

apt-get purge bbb-apps bbb-apps-akka bbb-apps-screenshare bbb-apps-sip bbb-apps-video bbb-apps-video-broadcast bbb-client bbb-config bbb-freeswitch-core bbb-freeswitch-sounds bbb-fsesl-akka bbb-html5 bbb-mkclean bbb-playback-presentation bbb-record-core bbb-red5 bbb-swftools bbb-transcode-akka bbb-web bbb-webrtc-sfu bigbluebutton
wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v xenial-220-2.2.20 -s yourdomainname.com -e youremail@yourdomain.com -a -w

Please note the API Shared Secret will change and you need to take care.

Thank you

**Comment by ffdixon** [comment]
We would recommend you develop against the latest release of BigBlueButton.

**Comment by longlnk** [comment]
> to downgrade to 2.2.20 the following command can be used
> 
> apt-get purge bbb-apps bbb-apps-akka bbb-apps-screenshare bbb-apps-sip bbb-apps-video bbb-apps-video-broadcast bbb-client bbb-config bbb-freeswitch-core bbb-freeswitch-sounds bbb-fsesl-akka bbb-html5 bbb-mkclean bbb-playback-presentation bbb-record-core bbb-red5 bbb-swftools bbb-transcode-akka bbb-web bbb-webrtc-sfu bigbluebutton
> wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v xenial-220-2.2.20 -s yourdomainname.com -e [youremail@yourdomain.com](mailto:youremail@yourdomain.com) -a -w
> 
> Please note the API Shared Secret will change and you need to take care.
> 
> Thank you

Thanks, It worked
