### ISSUE TITLE
"errorCode":1007,"cause":"ICE negotiation failed

### ISSUE THREAD

**Issue by daniboy82** [bigbluebutton/bbb-install#255]
My bbb is behind a firewall and We are using NAT.

We follow all instructions informed on:
https://docs.bigbluebutton.org/2.2/configure-firewall.html

And the follow error persists:

{"errorCode":1007,"cause":"ICE negotiation failed. Current state - failed","validUser":"valid"},

Any sugestion on how we do the troubleshooting?

**Comment by daniboy82** [comment]
other point I found on log is:

/var/log/bigbluebutton/bbb-web.log:2020-08-13T12:47:20.890-03:00 WARN  i.l.c.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Conexão recusada: /127.0.0.1:6379

**Comment by daniboy82** [comment]
root@webconf-ead:/etc# bbb-conf --check

BigBlueButton Server 2.2.19 (2025)
                    Kernel version: 4.4.0-116-generic
                      Distribution: Ubuntu 16.04.6 LTS (64-bit)
                            Memory: 8166 MB
                         CPU cores: 1

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://webconf-ead.sebrae.com.br
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: webconf-ead.sebrae.com.br
                              port: 80, [::]:80
                              port: 443 ssl
                    bbb-client dir: /var/www/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://webconf-ead.sebrae.com.br
                              red5: webconf-ead.sebrae.com.br
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 191.6.145.238
                   external_rtp_ip: 191.6.145.238
                   external_sip_ip: 191.6.145.238

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${external_rtp_ip}
                        ext-sip-ip: $${external_sip_ip}
                        ws-binding: :5066
                       wss-binding: 191.6.145.238:7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: webconf-ead.sebrae.com.br
                 playback_protocol: https
                            ffmpeg: 4.2.2-1bbb1~ubuntu16.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: 191.6.145.238

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: 10.1.140.5
                       kurento.url: ws://127.0.0.1:8888/kurento
                    kurento.sip_ip: 10.1.140.5
                    localIpAddress: 10.1.140.5
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 960
                        kurentoUrl: wss://webconf-ead.sebrae.com.br/bbb-webrtc-sfu
                  enableListenOnly: true


# Potential problems described below
# Warning: The voice application may not have registered with the sip server.
#   Try running:
#
#      bbb-conf --clean
#


# Error: FreeSWITCH is listening on IP address 191.6.145.238 for SIP calls, but
# The IP address (10.1.140.5) set bbb.sip.app.ip.
#

# Warning: The setting of 191.6.145.238 for proxy_pass in
#
#    /etc/bigbluebutton/nginx/sip.nginx
#
# does not match the local IP address (10.1.140.5).
# (This is OK if you've manually changed the values)

# Warning: The setting of 191.6.145.238 for local_ip_v4 in
#
#    /opt/freeswitch/etc/freeswitch/vars.xml
#
# does not match the local IP address (10.1.140.5).
# (This is OK if you've manually changed the values)

# Warning: found only 1 cores, whereas this server should have (at least) 4 CPU cores
# to run BigBlueButton in production.
#
#   https://docs.bigbluebutton.org/install/install.html#minimum-server-requirements
#
root@webconf-ead:/etc#

**Comment by daniboy82** [comment]
Is there a way to reinstall everything with automate install script?

**Comment by lonesomewalker** [comment]
Whoa, are you sure you want to have this running with 1 CPU? :-)

**Comment by daniboy82** [comment]
I have installed bbb in AWS cloud and bbb worked then I compared each configuration between both envs and I figured out what was wrong. thanks anyway.

**Comment by daniboy82** [comment]
I have installed bbb in AWS cloud and bbb worked then I compared each configuration between both envs and I figured out what was wrong. thanks anyway.

**Comment by maychine-fatima** [comment]
Hello @daniboy82  , i have the same issue can you tell me what was wrong, because i updated the version of BBB to 2.2.27 where the sip is updated too and i got the same error. Thanks.

**Comment by daniboy82** [comment]
Hello, my problem was due to existing 2 IPs, the internal and pub IP.
I had to check all config files and use the correct one depending if this property is local or external. 
Besides that, sysadmin had to assign pub IP to the local interface with the follow example command:

ip addr add 192.168.50.5 dev eth1
