### ISSUE TITLE
ascii gets replaced wrong after an upgrade run

### ISSUE THREAD

**Issue by lonesomewalker** [bigbluebutton/bbb-install#257]
Used text in defaultWelcomeMessage which contains converted native2ascii text gets wrong replaced.

Example: f\u00fcr
After update to newer version: fu00fcr

Seems the regex is broken for this case.

**Comment by GhaziTriki** [comment]
Since BigBlueButton is still using JDK8 you need to convert the character encoding. Just do this:

```bash
sudo apt-get install -y openjdk-8-jdk-headless
sudo native2ascii "bbb-web.properties"
```

**Comment by GhaziTriki** [comment]
Should no more be an issue since JVM11 is now being used.
