### ISSUE TITLE
Switch to low latency kernel

### ISSUE THREAD

**Issue by rasos** [bigbluebutton/bbb-install#260]
We have very good performance / avoid jitter experience with several BBB and Jitsi instances when applying a low latency kernel. For a short comparison see https://unix.stackexchange.com/a/573736

`apt-get install linux-lowlatency linux-headers-lowlatency`

**Comment by defnull** [comment]
I commented in https://github.com/bigbluebutton/bbb-install/pull/262 why I think this may actually make things worse. Did you measure any benefits or is the perceived improvement more a subjective observation?

**Comment by basisbit** [comment]
I agree that this should not be default. For a use case like current version of bbb, a low latency kernel should almost only reduce performance, not increase it. I'd suggest closing this old pull request.

**Comment by ffdixon** [comment]
@basisbit Agreed.  We tried the low-latency kernel ourselves and didn't see an improvement.
