### ISSUE TITLE
Blank blue screen after fresh setup of BigBlueButton

### ISSUE THREAD

**Issue by jgharehchamani** [bigbluebutton/bbb-install#263]
Hi,

I installed bigbluebutton using the install procedure in https://github.com/bigbluebutton/bbb-install and step-by-step procedure in https://docs.bigbluebutton.org/2.2/install.html on multiple fresh ubuntu server 16.04 machines on VM and AWS. But in all cases, after the installation, when I enter my name to join the demo meeting I get a blue blank screen. It is the same for the demo page as well (http://IP_ADDRESS/demo/demo1.jsp).

Do you know what is the issue?

**Comment by DocStem** [comment]
Same issue. Clean 16 install used the install-bbb.sh script. Bare Metal 16 GB Memory 4 Core CPUs. Also notice the HTML Client is unrecognized. No errors on install, no errors on status check. I too made no config changes.
A shove in the right direction would be handy...


![Screenshot from 2020-08-25 22-39-57](https://user-images.githubusercontent.com/70248232/91249073-242d2a00-e724-11ea-83cb-cb122eca4c33.png)
![Screenshot from 2020-08-25 22-40-42](https://user-images.githubusercontent.com/70248232/91249077-24c5c080-e724-11ea-8b04-75265915db74.png)

**Comment by liuhetongzi** [comment]
Same issue.  The browser console has error ‘Uncaught TypeError: Cannot set property 'ondevicechange' of undefined’。
![image](https://user-images.githubusercontent.com/23496061/91398855-7a5ab400-e86f-11ea-8aa6-05977ddc7aac.png)

**Comment by liuhetongzi** [comment]
I solved this problem by set bbb ssl

**Comment by DocStem** [comment]
So you are saying you did the install again but used the SSL Options on the install script?

**Comment by jgharehchamani** [comment]
I fixed it too. You have to use SSL with a valid IP address and DNS otherwise it will not work. E.g., use AWS and assign an elastic IP to that. You cannot use AWS dns. When you have both these prerequisits, execute the following command:

wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v xenial-22 -s INSTANCE.DOMAIN -e info@DOMAIN -w -a -g

where INSTANCE should be replaced by host name and DOMAIN with your domain name

**Comment by DocStem** [comment]
Thank you for the information jgharehchamani you sir are a Rock Star..... 
I am going to keep mine behind a Firewall and VPN so I might have to play with the Certificate but This should give me something to go on.

**Comment by SoumenChowdhury** [comment]
The same thing is for me also. Tried several times either by "step-by-step" installation, or directly running the script for "Install and configure with an IP address only", got the same blank blue screen. Used the command **wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v xenial-22**.

**Comment by ffdixon** [comment]
We're going to modify the docs/script to disallow installation with an IP address only -- the browsers have evolved where they won't run any WebRTC-related application without an SSL certificate.

**Comment by praka07** [comment]
i do face same issue today.. please do something as soon as possible

**Comment by ffdixon** [comment]
We need to update the docs -- you *must* setup an SSL certificate for BigBlueButton or it won't load.   **If you see "Not Secure" on your browser URL, BigBlueButton will not load.**

**Comment by praka07** [comment]
Thanks for information, worked after SSL certificate

**Comment by ffdixon** [comment]
Updated `bbb-install.sh` docs to make clear that a SSL certificate is required to run BigBlueButton.

**Comment by adi0311** [comment]
@ffdixon can we run it on older version of BigBlueButton on IP address(without SSL)?

**Comment by mesuttalebi** [comment]
what about development environment on a vm? am I also need ssl? and how

**Comment by neerajrath** [comment]
I am still getting blue screen. Could you please help. I need this urgently as my customer waiting and asking me to do RnD.
my email neerajrath@gmail.com  , will respond quickly on email
Pls help me.

**Comment by ffdixon** [comment]
This is a very old issue.  Recommend you post to bigbluebutton-setup or, if time is of the essence, reach out to some of the companies providing commercial support.  See https://bigbluebutton.org/commercial-support/.
