### ISSUE TITLE
Starting microphone : could not make a WebSocket connection (Error 1002)

### ISSUE THREAD

**Issue by Thatoo** [bigbluebutton/bbb-install#275]
I have installed BBB 2.2 on an ubuntu 16.04 server with an external static IPv4 (no NAT, no firewall) using the script install.sh like that
wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -v xenial-22 -s mydomain.com -e technique@mydomain.com -w -g

It worked fine without error. I can connect to BBB, register an account, launch a room, invite a friend, start the video, share a presentation...

However, when one of us want to start his/her microphone, it doesn't work. We get this error :
> Could not make a WebSocket connection (Error 1002)

What can I do to solve the problem?

**Comment by ffdixon** [comment]
Check the contents of `/etc/bigbluebutton/nginx/sip.nginx`.  It should have `proxy_pass` resolve to the external IP address of your server.

**Comment by mjencabh** [comment]
After a new install i get same errors after having the server running for about 6 months with updates through install script.
Im now trying to install without the -w to see if thats where the problem lays in script installing.

**Comment by mjencabh** [comment]
Well without the -w it still gives ice 1007 its like its not configuring as it use to :(

**Comment by assodefis** [comment]
> Check the contents of `/etc/bigbluebutton/nginx/sip.nginx`. It should have `proxy_pass` resolve to the external IP address of your server.

It was properly set indeed so the problem is from somewhere else....

**Comment by Thatoo** [comment]
> Check the contents of `/etc/bigbluebutton/nginx/sip.nginx`. It should have `proxy_pass` resolve to the external IP address of your server.

It was properly set indeed so the problem is from somewhere else....

**Comment by Thatoo** [comment]
I found an error in two of the config files that I can't explain.
The IPv4 was wrong, not the external but the internal Ipv4...
/usr/share/red5/webapps/sip/WEB-INF/bigbluebutton-sip.properties
/opt/freeswitch/etc/freeswitch/vars.xml

I have checked other config files and it was fine. Why did these two files was set with the local ip and not the external ip?
Anyway, after correcting that, BBB is now working.

It is possible for me to close this issue now.
Good luck to others.

**Comment by jerryshell** [comment]
Same problem. The BBB worked fine at first, but a few months later (there were several upgrades in between). 
Restart the machine (Adjust the configuration of the GCP machine, but the public ip has not changed), a 1002 error appears, microphone is not available, but screen sharing works fine.

Reinstall by `wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -w -v xenial-22 -a -w -s mydomain.com` BBB is now working.
