### ISSUE TITLE
Kurento Media Server Failed to start

### ISSUE THREAD

**Issue by coderDem** [bigbluebutton/bbb-install#277]
Hello,

I have updated my Ubuntu from 16.04 to Ubuntu 18.04.
Here I reinstalled bbb with the 

`
wget -qO- https://ubuntu.bigbluebutton.org/bbb- install.sh | bash -s -- -v bionic-230-dev -s <awsomesite.de> -e <admin@awsomesite.de> -a -w
`

I have know a problem with the Kurento Media Server:
`bbb-conf --status`
`nginx —————————————————► [✔ - active]`
`freeswitch ————————————► [✔ - active]`
`redis-server ——————————► [✔ - active]`
`bbb-apps-akka —————————► [✔ - active]`
`bbb-fsesl-akka ————————► [✔ - active]`
`tomcat8 ———————————————► [✔ - active]`
`mongod ————————————————► [✔ - active]`
`bbb-html5 —————————————► [✔ - active]`
`bbb-webrtc-sfu ————————► [✔ - active]`
`kurento-media-server ——► [✘ - failed]`
`etherpad ——————————————► [✔ - active]`
`bbb-web ———————————————► [✔ - active]`

`service kurento-media-server status`
`● kurento-media-server.service - Kurento Media Server daemon
   Loaded: loaded (/usr/lib/systemd/system/kurento-media-server.service; enabled; vendor preset: enabled)
   Active: failed (Result: signal) since Mon 2020-09-14 09:15:15 CEST; 14min ago
  Process: 41792 ExecStart=/usr/bin/kurento-media-server --gst-debug-level=3 --gst-debug=3,Kurento*:4,kms*:4,KurentoWebSocketTransport:5 (code=killed, signal=ABRT)
  Process: 41791 ExecStartPre=/bin/rm -f /var/kurento/.cache/gstreamer-1.5/registry.x86_64.bin (code=exited, status=0/SUCCESS)
 Main PID: 41792 (code=killed, signal=ABRT)`

`Sep 14 09:15:15 Ubuntu systemd[1]: kurento-media-server.service: Service hold-off time over, scheduling restart.`
`Sep 14 09:15:15 Ubuntu systemd[1]: kurento-media-server.service: Scheduled restart job, restart counter is at 5.`
`Sep 14 09:15:15 Ubuntu systemd[1]: Stopped Kurento Media Server daemon.`
`Sep 14 09:15:15 Ubuntu systemd[1]: kurento-media-server.service: Start request repeated too quickly.`
`Sep 14 09:15:15 Ubuntu systemd[1]: kurento-media-server.service: Failed with result 'signal'.`
`Sep 14 09:15:15 Ubuntu systemd[1]: Failed to start Kurento Media Server daemon.`

Does anybody have an idea what is wrong here?

**Comment by ffdixon** [comment]
Do you see any errors in 

  journalctl -u kurento-meida-server

and in the Kurento log files

  /var/log/kurento-media-server

**Comment by ffdixon** [comment]
Also, when passing the parameters, it would be `-s awsomesite.de -e admin@awsomesite.de`.

**Comment by coderDem** [comment]
Hello @ffdixon,

the parameter <awsomesite.de> were only the placeholder for awsomesite.de.
I saw no errors in the log /var/log/kurento-media-server

Right now I switched to Ubuntu 16.04 and reinstalled BBB with the script.
Now everything is working.

Thank you
