### ISSUE TITLE
Mobile View Bigbluebutton v2.3 -Left side Menu lock and can not close or going back to main screen

### ISSUE THREAD

**Issue by LMSSPACE** [bigbluebutton/bbb-install#278]
@ffdixon
Hi Dear 
First of all thanks a lot for everything you and your team have done.
I installed a fresh Bigbluebutton v2.3 on my VM and everything is working fine and very well but there is an issue on the mobile view.
when a user tries to access the left side menu which contains public chat, shared note, and users list the menu will lock and there is no way to going back.
on the bigbluebutton v2.2.3 when it was working fine but in v2.3 it has an issue which I describe it.

I would be so happy to help me and the community to solve this problem.

Best Regards

**Comment by ffdixon** [comment]
Thanks for letting us know.  BigBlueButton 2.3-alpha is still under development.  We'll take a look at fixing this issue in 2.3-alpha3.  Can you open an issue at https://github.com/bigbluebutton/bigbluebutton/issues
