### ISSUE TITLE
Long response in screensharing

### ISSUE THREAD

**Issue by maxlavr83** [bigbluebutton/bbb-install#28]
During the screensharing, all actions are delayed, and videos with friezes.
The server meets the minimum requirements - https://docs.bigbluebutton.org/install/install.html .
Tell me, please, can sceensharing be speeded up?

**Comment by ffdixon** [comment]
Can you try it against https://test.bigbluebutton.org/ and let us know if you encounter the same issue.

**Comment by maxlavr83** [comment]
Hi,
Against this reference the issue is also observed
To share a desktop I use Java (8 Update 181)

**Comment by maxlavr83** [comment]
Ok, I will, thanks
