### ISSUE TITLE
 The microphone does not work error 1007. It refers to the internal address of the server, and not to the external

### ISSUE THREAD

**Issue by kishrop** [bigbluebutton/bbb-install#281]
Hello!
Installed BBB on ubuntu server. Located in NAT. I set everything up according to the instructions. Camera works. The desktop display is working. Connects to the audio conference as listening. Microphone activation does not work. Error 1007 refers to an internal server address, not an external one. I use public STUN.
Help me please! =(

**Comment by kishrop** [comment]
If you have the HTML5 client installed, you may need to a few more changes. If enableListenOnly is set to true in /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml, as in

$ grep enableListenOnly /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml
    enableListenOnly: true
then Kurento is providing a listen only audio stream for users of the HTML5 client. In this case, edit /usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml change the value to ip to match the external IP address of the server, and the value of sip_ip to match the internal IP address of the server (where FreeSWITCH is listening to port 5066). For example, if the servers external IP address is 203.0.113.1 and the internal IP address is 172.30.1.145 then edit default.yml and change the values for ip and sip_ip as follows:

freeswitch:
    ip: 203.0.113.1
    sip_ip: 172.30.1.145
    port: 5066
Next, change the value of sip+ip You also need to setup Kurento to use a STUN server.

I don't understand: Next, change the value of sip + ip.

**Comment by ffdixon** [comment]
Check the IP address in /etc/bigbluebutton/nginx/sip.nginx -- it needs to be the external IP address. 

~~
location /ws {
        proxy_pass https://EXTERNAL_IP_ADDRESS:7443;
        ...
}
~~~

If you have further questions, post to [bigbluebutton-setup](https://bigbluebutton.org/support/community/) mailing list.
