### ISSUE TITLE
bigbluebutton 2.2 WHEN LOGGING IN TO THE ROOM MICROPHONE CONNECTION PROBLEM

### ISSUE THREAD

**Issue by webcruna** [bigbluebutton/bbb-install#282]
Good morning, I am a teacher, I have installed BBB in a VPS, when I enter the ROOM the MICROPHONE box freezes and does not let me advance or SPEAK, Thanks for your help

you can see the PROBLEM HERE
https://reunion.pe/b/adm-rqb-unz-waz

**Comment by ffdixon** [comment]
There isn't enough information to help.  See https://docs.bigbluebutton.org/2.2/getting-help.html#help-installing-or-running-bigbluebutton
