### ISSUE TITLE
Node.js 9 is deprecated

### ISSUE THREAD

**Issue by Craftoncu** [bigbluebutton/bbb-install#291]
Install Scripts installs NodeJs9 which is deprecated and not longer supported.

**Comment by ffdixon** [comment]
Yes, we are working on BigBlueButton 2.3-dev which has a newer version of nodejs. This will be on Ubuntu 18.04. See https://docs.bigbluebutton.org/dev/dev23.html.

**Comment by ffdixon** [comment]
We have a 2.3-alpha release.  Please try it and let us know any issues with the installation.  

  https://docs.bigbluebutton.org/dev/dev23.html
