### ISSUE TITLE
How to install without domain?

### ISSUE THREAD

**Issue by KonradHoeffner** [bigbluebutton/bbb-install#296]
I don't have a spare domain so I want to install a BBB instance that is just reachable over the IP address of the server only. The documentation is for the use case of a domain, however. Is it possible to deploy BBB without a domain and if yes, how?

**Comment by ffdixon** [comment]
It used to be possible to install without a domain and WebRTC audio/video would work, but the browsers now require domain+https to install.  Other parts of BigBlueButton client now require https, so you'll need to have a domain name + SSL certificate to setuip BigBlueButton.

**Comment by KonradHoeffner** [comment]
Thanks for the instant response! And is it possible to use a subdomain or a folder of a domain I have control of that already has an SSL certificate?

**Comment by borhanreo** [comment]
Just run this command 
`wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v xenial-22 -a`

**Comment by dumidu1998** [comment]
> Thanks for the instant response! And is it possible to use a subdomain or a folder of a domain I have control of that already has an SSL certificate?

Yes. you can use your subdomain as domain name when installing. eg:- `meet.dumidu.xyz`

**Comment by KonradHoeffner** [comment]
Thanks, my question is now answered!
