### ISSUE TITLE
Install bionic-230-dev on ubuntu 18.04 little error

### ISSUE THREAD

**Issue by jdossantos** [bigbluebutton/bbb-install#297]
Installation on ubuntu 18.04 with dev version works like a charm, very good work !

At the end there's a little error though : 

default: # Potential problems described below
default: dpkg-query: no packages found matching libreoffice
default: # Not running:  LibreOffice

bbb-libreoffice is running though : 

docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
c11ad7189d95        bbb-libreoffice     "/usr/local/bin/bbb-…"   5 days ago          Up 5 days           0.0.0.0:8204->8000/tcp   bbb-libreoffice-4
f83a5f4de928        bbb-libreoffice     "/usr/local/bin/bbb-…"   5 days ago          Up 5 days           0.0.0.0:8203->8000/tcp   bbb-libreoffice-3
6a66b37da028        bbb-libreoffice     "/usr/local/bin/bbb-…"   5 days ago          Up 5 days           0.0.0.0:8202->8000/tcp   bbb-libreoffice-2
f045569156fa        bbb-libreoffice     "/usr/local/bin/bbb-…"   5 days ago          Up 5 days           0.0.0.0:8201->8000/tcp   bbb-libreoffice-1

**Comment by ffdixon** [comment]
Yes. Going to fix that in the next update to 2.3-dev.

**Comment by ffdixon** [comment]
Can you try 2.3-alpha4 and let us know if this problem still persists -- thanks!

**Comment by githlp** [comment]
just curious: to get a clean installation: in case i do a fresh install of ubuntu 18.04: do i use the bbb-install.sh script
`wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v bionic-230-dev -s bbb.myserver.com -e mymail@myserver.com  -a -w`
without any adoptions ?

The question is about the already created certificates from Lets Encrypt - is it a problem when the script creates them again for the same domain or do i have to store the old ones anywhere before doing a complete new installation ?

**Comment by githlp** [comment]
so i just try it out i guess ..

**Comment by ffdixon** [comment]
You can run `bbb-install.sh` on the same server multiple times.  It will detect if the certificates need to be renewed.

**Comment by jdossantos** [comment]
> Can you try 2.3-alpha4 and let us know if this problem still persists -- thanks!

Hello, apologies for taking some time to answer, I just tried and I get this at the end of the install process : 
default: # Potential problems described below
    default: .
    default: .

I guess this is resolved ! thanks !
