### ISSUE TITLE
fails with "bbb-install: Did not detect nodejs 8.x candidate for installation"

### ISSUE THREAD

**Issue by quantenschaum** [bigbluebutton/bbb-install#298]
:bomb: On Xenial this fails with `bbb-install: Did not detect nodejs 8.x candidate for installation`

btw: Why Xenial? This is almost 5 years old! We've got Focal 20.04 LTS now!

**Comment by ffdixon** [comment]
We are working towards 18.04 in 2.3.  https://docs.bigbluebutton.org/dev/dev23.html

**Comment by quantenschaum** [comment]
Nice! But the current install guide explicitly mentions Xenial, and Xenial is still Xenial, so I expect this to work on a fresh install of Xenial. But it doesn't!

(Wouldn't it be better to skip 18.04 and go for 20.04 directly? Why is this actually tied to Ubuntu, shouldn't this be distro agnostic? Seems to be very brittle all in all.)

**Comment by ffdixon** [comment]
> Nice! But the current install guide explicitly mentions Xenial, and Xenial is still Xenial, so I expect this to work on a fresh install of Xenial. But it doesn't!

The binaries for FreeSWITCH and Kurento are built for Xenail in 2.2.  In 2.3-dev, we are building them for Bionic.  At this moment, Kurento isn't supported on 20.04, so our focus is on 18.04.

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for development related issues regarding the bbb-install script.

**Comment by PelleHanses** [comment]
I also had similar error "bbb-install: Did not detect nodejs 12.x candidate for installation".  The solution was to edit the date/time on the server. 

```
sudo service ntp stop
sudo ntpd -gq
sudo service ntp start
```

OS: Ubuntu 18.04
