### ISSUE TITLE
 questions 

### ISSUE THREAD

**Issue by Mitha2017** [bigbluebutton/bbb-install#3]
I have questions about big blue button

**Comment by ffdixon** [comment]
Hi there, 

Please post your questions to one of our forums.  See https://bigbluebutton.org/support

**Comment by Mitha2017** [comment]
Hi
Could you plz answer these questions for me?

How many rooms extremely you will provide me?

How many students extremely in each room?

The programming language used for Bigbluebutton

could you plz provide me with E-mail for more information

I want to communicate with people who bought Bigbluebutton to take feedback



Regards:
Mitha



2018-02-25 7:30 GMT+04:00 Fred Dixon <notifications@github.com>:

**Comment by ffdixon** [comment]
> How many rooms extremely you will provide me?

BigBlueButton is an open source project.  There is no cost to installing BigBlueButton on one of your servers.  See: http://docs.bigbluebutton.org/#latest-versions.

> How many students extremely in each room?

See http://docs.bigbluebutton.org/support/faq.html#how-many-simultaneous-users-can-bigbluebutton-support.

> The programming language used for Bigbluebutton

See http://docs.bigbluebutton.org/overview/architecture.html.

> I want to communicate with people who bought Bigbluebutton to take feedback

Please post your questions to the corresponding forum, see: https://bigbluebutton.org/support
