### ISSUE TITLE
Button Live broadcasting RTMP 

### ISSUE THREAD

**Issue by chezmohamed** [bigbluebutton/bbb-install#302]
![image](https://user-images.githubusercontent.com/26858857/99901765-6e895d00-2cb9-11eb-8b87-ba680580b9d1.png)
Hello
I want to do one-session live broadcasting, but I can't find a "Live broadcasting RTMP" button
how can I activate this option?
thanks

**Comment by basisbit** [comment]
This is not a feature contained in default BigBlueButton. I suggest you to ask the operator of the server where you made this screenshot for how they added it.
