### ISSUE TITLE
Install fails with "bbb-install: Unable to setup PPA for ppa:rmescandon/yq"

### ISSUE THREAD

**Issue by heinrichrebehn** [bigbluebutton/bbb-install#303]
gpg: keyring `/tmp/tmpee6ko_4r/secring.gpg' created
gpg: keyring `/tmp/tmpee6ko_4r/pubring.gpg' created
gpg: requesting key CC86BB64 from hkp server keyserver.ubuntu.com
gpg: /tmp/tmpee6ko_4r/trustdb.gpg: trustdb created
gpg: key CC86BB64: public key "Launchpad PPA for Roberto Mier Escand?n \xee\x83\xbf" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
'ascii' codec can't decode byte 0xc3 in position 108: ordinal not in range(128)
gpg: keyring `/tmp/tmpqifdb3o5/secring.gpg' created
gpg: keyring `/tmp/tmpqifdb3o5/pubring.gpg' created
gpg: requesting key CC86BB64 from hkp server keyserver.ubuntu.com
gpg: /tmp/tmpqifdb3o5/trustdb.gpg: trustdb created
gpg: key CC86BB64: public key "Launchpad PPA for Roberto Mier Escand?n \xee\x83\xbf" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
'ascii' codec can't decode byte 0xc3 in position 108: ordinal not in range(128)
bbb-install: Unable to setup PPA for ppa:rmescandon/yq

**Comment by ffdixon** [comment]
Did you get this error running `bbb-install.sh`?

**Comment by heinrichrebehn** [comment]
Hi Fred,
thanks for replying. The error happens regardless wether I use bbb-install.sh or execute the commands by hand.
Meanwhile, I found a workaround at

https://github.com/mikefarah/yq/issues/217

`sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6657DBE0CC86BB64
sudo apt update
sudo apt install -y yq`

After that, bbb-install.sh runs successfully.

-Heinrich

**Comment by ffdixon** [comment]
Thanks for sharing your solution.

**Comment by braisarias** [comment]
Its seems to fail it again. 
The key for PPA is not found at keyserver:
https://keyserver.ubuntu.com/pks/lookup?search=6657DBE0CC86BB64&fingerprint=on&op=index
