### ISSUE TITLE
install coturn on bbb server

### ISSUE THREAD

**Issue by hex-m** [bigbluebutton/bbb-install#305]
The documentation mentions:

> You need a separate server (not the BigBlueButton server) to set up as a TURN server.

There is no reason, why coturn should not be installed on the same server, as long as the bbb-server has a public IP. The reasoning why this would be a good idea is also [explained here](https://github.com/bigbluebutton/bigbluebutton/issues/10764#issuecomment-724362897).

As Jitsi Meet was mentioned, their coturn packaging is [public](https://github.com/jitsi/jitsi-meet/tree/master/doc/debian/jitsi-meet-turn) and may be a good start.

caveats:
* 2.3 (Ubuntu 18.04) only
* server needs public IP
* port 443 (which is the recommended coturn-port according to the documentation) is already in use

**Comment by basisbit** [comment]
haproxy (or maybe nginx?) could be used to have coturn also be reachable on port 443. As far as I know, Jitsi does this the same way. Any other port would cause some people to not be able to connect, so I'd consider it to be mandatory.

**Comment by hex-m** [comment]
Closing this as a duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/8875
