### ISSUE TITLE
freeswitch config missing wss-binding setting to external-ip

### ISSUE THREAD

**Issue by couchgott** [bigbluebutton/bbb-install#306]
Since short time the freeswitch config within: 

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml

does not get the parameter wss-binding set correctly. 

when deploying using bbb-install.sh it ends up with: 

`<param name="wss-binding" value=":7443"/>`

while it used to set the external IP of the server instance correctly beforehand. (Tested on EC2/AWS) 

this is causing 1002 errors which can be easily fixed manually setting the parameter right and restart freeswitch. 

not totally sure if this is related to the latest commit: https://github.com/bigbluebutton/bbb-install/commit/5c6a738b8361a05b91554c897425c3c01bb4b180 

as there were some changes for the IP replacements.

**Comment by nzmhtpgl** [comment]
this was happened to me also. for 5 days i am changing it manuelly. is there any solution?

**Comment by ffdixon** [comment]
Can you run `bbb-install.sh` again.  Did some testing on AWS and [made some improvements](https://github.com/bigbluebutton/bbb-install/commit/43cbf0e2677e79aca971d9d0777ca8708f9a51d2) that should properly assign `wss-binding` now.

**Comment by nzmhtpgl** [comment]
we can not install with bbb-install.sh anymore after this update.

**Comment by gamferreira** [comment]
We are also experiencing the same problem with AWS. Using the lastest bbb-install.sh script the process hangs here:

```
Waiting for port 443 to clear
....................................................................................................................................................................................................................................
```

This is the output of netstat:

```
root@ip-10-1-15-196:~# netstat -antp
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      27915/rpcbind
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1362/sshd
tcp        0      0 127.0.0.1:20217         0.0.0.0:*               LISTEN      28399/stunnel
tcp        0      0 10.1.15.196:37168       52.46.132.109:443       ESTABLISHED 1866/amazon-ssm-age
tcp        0      0 10.1.15.196:40174       10.1.5.174:2049         ESTABLISHED 28399/stunnel
tcp        0      0 127.0.0.1:20217         127.0.0.1:56044         ESTABLISHED 28399/stunnel
tcp        0      0 127.0.0.1:56044         127.0.0.1:20217         ESTABLISHED -
tcp        0      0 10.1.15.196:39310       52.94.233.158:443       ESTABLISHED 1866/amazon-ssm-age
tcp        0    325 10.1.15.196:42666       52.46.128.123:443       ESTABLISHED 1004/ssm-session-wo
tcp6       0      0 :::111                  :::*                    LISTEN      27915/rpcbind
tcp6       0      0 :::22                   :::*                    LISTEN      1362/sshd
```

**Comment by ffdixon** [comment]
The logic to check if port 443 had clear is too simple

 https://github.com/bigbluebutton/bbb-install/blob/master/bbb-install.sh#L472

as it's a regular expression match looking for ':443'.  For the new few hours, you can download bbb-install.sh, remove the above line, make it executable, and run it locally.

Need to figure out a better way to see if port 443 is still in use by another process which prevents `nc` from listening on it.  Suggestions welcome!

**Comment by ffdixon** [comment]
Updated the install script -- can you try it again.

**Comment by gamferreira** [comment]
@ffdixon I will give it a try later today and keep you posted

**Comment by nzmhtpgl** [comment]
> Updated the install script -- can you try it again.

everything is working now. tested on aws. many thanks

**Comment by Moustique82** [comment]
the script as change the <param name="wss-binding" value=":7443"/> ?

**Comment by ffdixon** [comment]
@Moustique82  Can you try the latest version of `bbb-install.sh` and if you still encounter this issue, open a new issue with steps to reproduce.

**Comment by jerry1807** [comment]
Hey hi, I am trying to use the bbb.sh script on digital ocean I am getting the error Waiting for port 443 to clear

**Comment by jerry1807** [comment]
Kindly help me with this error

**Comment by ersaurabh101** [comment]
Hello all, I am also facing the same issue, any solution  ?

**Comment by ffdixon** [comment]
Just to confirm, are you doing these commands on different servers (one server for the TURN server and the second server for BigBlueButton)?

Does BigBlueButton work when you test it with the TURN server?

**Comment by ersaurabh101** [comment]
you know what happened

I did everything as guided on GCP.

On SSH, the script end on both the instances at Waiting for port 443 to clear.. line

After 30 minutes, things worked.

I will again redo all this to assure they will work in future by creating 2 new instances. I would like to invite you t work together and experience this. I believe it should work smoothly in future. Let me know if you would like to see how it goes.

Regards
Saurabh chadha
