### ISSUE TITLE
error installing bbb

### ISSUE THREAD

**Issue by hassanayoub85** [bigbluebutton/bbb-install#308]
when i am trying to install bbb using bbb-instal.sh, I get this error:
{
Setting up bbb-demo (1:2.2.0-9) ...
Reloading nginx.service using systemd
Processing triggers for systemd (229-4ubuntu21.29) ...
Processing triggers for ureadahead (0.100.0-19.1) ...
Errors were encountered while processing:
 redis-server
 bbb-web
 bbb-record-core
 bbb-playback-presentation
 bbb-config
 bigbluebutton
E: Sub-process /usr/bin/dpkg returned an error code (1)
..............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
}
dots keeps appearing for hours.
Command I am using "wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v xenial-22 -a" on ubuntu 16.04

**Comment by anazari96** [comment]
I got this error on ubuntu 18 
command I am using is ```sudo wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | sudo bash -s -- -v bionic-230-dev -a -g```

**Comment by ffdixon** [comment]
Can you provide a valid hostname that points to the public IP address of your server along with an email address.

See the docs for examples.

**Comment by hassanayoub85** [comment]
"i tried -s domain -e email", same error

**Comment by ffdixon** [comment]
We need more information to debug this.  What is the hosting provider of your server?  Is it on the internet with a public IP address? Does your server meet the minimum requirements?

**Comment by anazari96** [comment]
I need to install it on a VM on my laptop for developming purpose 
so I can not install it on a server with valid public IP

**Comment by hassanayoub85** [comment]
i donno but i retried today and it worked!
