### ISSUE TITLE
What is the default login for Greenlight after using the script?

### ISSUE THREAD

**Issue by opensourcecompany** [bigbluebutton/bbb-install#31]
Since it is now dead-easy to setup an instance, it would be nice to see the password which is given for the "in application" authentification.

Done the script on a plain vm with settings as described.
No password shown, no email received.
Downloaded sqlite database -> user is in database

How do you reset/resend a password? :-D

**Comment by pdxbmw** [comment]
I believe you have to run the command `docker exec greenlight-v2 bundle exec rake admin:create` to create the default admin account. The command will display the loin credentials after it runs.

```
# docker exec greenlight-v2 bundle exec rake admin:create
Account successfully created.
Email: admin@example.com
Password: administrator
Role: admin
PLEASE CHANGE YOUR PASSWORD IMMEDIATELY
```
