### ISSUE TITLE
greenlight  installed but my url does not change to url/b

### ISSUE THREAD

**Issue by hadi-esmaeeli** [bigbluebutton/bbb-install#310]
potential:
 Potential problems described below
# IP does not match:
#                           IP from ifconfig: 172.16.2.7
#   /etc/nginx/sites-available/bigbluebutton: vc.iuc.ac.ir
# Warning: API URL IPs do not match host:
#
#                                IP from ifconfig: 172.16.2.7

**Comment by Oppageek** [comment]
What happends when you go to /b ? Is it looping or redirecting you to your main url ?

**Comment by ffdixon** [comment]
Did you use `bbb-install.sh` with a fully qualified domain name that resolves to the external IP address of your server?

**Comment by ffdixon** [comment]
Closing do to inactivity.
