### ISSUE TITLE
Focal Fossa - 20.04 LTS not supported

### ISSUE THREAD

**Issue by reesericci** [bigbluebutton/bbb-install#311]
This script does not currently support focal fossa (20.04 LTS).

**Comment by Oppageek** [comment]
Yes, they have said it many times in the documentation,
Please use only 16.04.x.

**Comment by ffdixon** [comment]
We are moving to 18.04 in the upcoming [BigBlueButton 2.3](https://docs.bigbluebutton.org/dev/dev23.html) (still in development).
