### ISSUE TITLE
do it for debian 9+

### ISSUE THREAD

**Issue by Faflixt** [bigbluebutton/bbb-install#314]

**Comment by basisbit** [comment]
Debian is not supported by bigbluebutton, thus bbb-install can't really do what you want. Also, see https://github.com/bigbluebutton/bigbluebutton/issues/8956 and a bunch of other issues.

**Comment by ffdixon** [comment]
Merged into #317

**Comment by akuckartz** [comment]
#314 was merged into #317 and #317 was merged into #314

**Comment by ffdixon** [comment]
Looks like the poster had opened two issues, and neither of them were very well presented.  We're going to leave both these closed and I'll open a new issue.

https://github.com/bigbluebutton/bbb-install/issues/325
