### ISSUE TITLE
Deprecation warning for Node 8.* carbon

### ISSUE THREAD

**Issue by kabaluyot** [bigbluebutton/bbb-install#315]
With the automated script, the deprecation shows

<img width="750" alt="Screen Shot 2020-12-12 at 9 41 27 PM" src="https://user-images.githubusercontent.com/38805756/101985430-ef3ce700-3cc2-11eb-81d9-558408466e5a.png">

**Comment by ffdixon** [comment]
This is a known issue.  The project is soon moving to Ubuntu 18.04 with BigBlueButton 2.3-dev (still in development) where we'll be using node 12.20.0 (or later).

**Comment by kabaluyot** [comment]
Ok closing this in favor the other prior issue filed.
