### ISSUE TITLE
How to uninstall greenlight?

### ISSUE THREAD

**Issue by kabaluyot** [bigbluebutton/bbb-install#316]
accidentally installed greenlight (the guide in setting up TURN server has -g for greenlight enabled)

**Comment by ffdixon** [comment]
[Fixed](https://github.com/bigbluebutton/bbb-install/commit/acf196783c1f33f4c7c1517edb349d57127c47a8).  Thanks.

**Comment by ffdixon** [comment]
https://docs.bigbluebutton.org/greenlight/gl-install.html#uninstall

**Comment by ontimond** [comment]
I had the same issue, there are two greenlight nginx config files in ` /etc/bigbluebutton/nginx/`:

```
greenlight-redirect.nginx
greenlight.nginx
```

So I moved them to another directory to keep these files in case something went wrong and reload nginx:

```
mv /etc/bigbluebutton/nginx/greenlight* /root/
nginx -s reload
```
