### ISSUE TITLE
Support for Debian 9

### ISSUE THREAD

**Issue by Faflixt** [bigbluebutton/bbb-install#317]
Could u please make it for `Debian 9 +`
And Ubunutu `18 20`

> 
i have an hoster where i can just do ubunutu 20 on it so it doesn´t work

`nojoke this is crap and bullshit update it to this and its the best!`

**Comment by ffdixon** [comment]
We have support for Ubuntu 18.04 coming in 2.3 (still under development).  See https://docs.bigbluebutton.org/dev/dev23.html

**Comment by basisbit** [comment]
also, please do not create duplicate issue reports. https://github.com/bigbluebutton/bbb-install/issues/314

**Comment by Faflixt** [comment]
It would be nice when u guys would make it for `Ubuntu 20.10` too!

LG
Falfixt

**Comment by ffdixon** [comment]
No plans to support Debian 9 or Ubuntu 20.04 or Ubuntu 20.10.  Our focus for 2.3 is for Ubuntu 18.04, which will be a big improvement over the current 16.04 for 2.2.  See https://docs.bigbluebutton.org/dev/dev23.html#installation

**Comment by ffdixon** [comment]
Merged into https://github.com/bigbluebutton/bbb-install/issues/314

**Comment by akuckartz** [comment]
#314 was merged into #317 and #317 was merged into #314
