### ISSUE TITLE
After clean installation: 404 Not Found nginx - html5client/join?sessionToken=XXXXX

### ISSUE THREAD

**Issue by lrit18** [bigbluebutton/bbb-install#321]
Hello everybody,
i installed bbb with the installation script. beforehand i have performed all recommended post installation steps. After the installation was completed after 50 minutes, I opened the browser and landed on the greenlight start page. If I then start a conference or want to open the room, I get a white page with the error message 404 Not Found nginx.

On the page https: //xxxx/demo/demoHTML5.jsp I always see the message "You must have the BigBlueButton HTML5 client installed to use this API demo." displayed. The HTML5 client was installed with the setup script.

After executing the command sudo bbb-conf --status I see that the bbb-html5 is not running.

I had to fix the error http://docs.bigbluebutton.org/2.2/troubleshooting.html#freeswitch-fails-to-start-with-a-setscheduler-error. also "Error: Could not detect FreeSWITCH listening on port 5060". These issues are now resolved.

i look forward to tips and support

**Comment by lrit18** [comment]
Hi there, 
I still couldn't fix the problem. 
Does any of you have ideas and tips and can help me please?

**Comment by ffdixon** [comment]
Can you try 

  https://docs.bigbluebutton.org/2.2/troubleshooting.html#bbb-html5-fails-to-start-with-a-setscheduler-error

and let us know if this fixes the issue for you.

**Comment by lrit18** [comment]
> 
> 
> Can you try
> 
> https://docs.bigbluebutton.org/2.2/troubleshooting.html#bbb-html5-fails-to-start-with-a-setscheduler-error
> 
> and let us know if this fixes the issue for you.

Thank you! That fixes my issue. Perfect.

**Comment by mtalhabalci** [comment]
> Can you try
> 
> https://docs.bigbluebutton.org/2.2/troubleshooting.html#bbb-html5-fails-to-start-with-a-setscheduler-error
> 
> and let us know if this fixes the issue for you.

these solutions always go to 404 pages.

**Comment by lrit18** [comment]
Hey, the page moves to: 
https://docs.bigbluebutton.org/support/troubleshooting.html#bbb-html5-fails-to-start-with-a-setscheduler-error
