### ISSUE TITLE
Manual upgrade from 230 alpha2 to alpha3 not successful

### ISSUE THREAD

**Issue by githlp** [bigbluebutton/bbb-install#322]
For the benefit of others, these are the steps listed in our documentation for manually upgrading to the latest build of BigBlueButton 2.2.

  https://docs.bigbluebutton.org/2.2/install.html#upgrading-from-bigbluebutton-22

_Originally posted by @ffdixon in https://github.com/bigbluebutton/greenlight/issues/2382#issuecomment-749179168_

**Comment by githlp** [comment]
Updating with the bbb-install.sh script requires to purge apache2 as well as apache2-bin, but then it cannot restart:

`Job for tomcat8.service failed because the control process exited with error code.`

How is that supposed to work then ?

**Comment by githlp** [comment]
ok, after re-installing tomcat8 the whole thing runs smoothly again, but the purge of apache2 and the manual re-install of tomcat is still confusing..

**Comment by Davka** [comment]
why was apache installed?

**Comment by githlp** [comment]
good question.

On this server i have installed bbb, greenlight (docker version), moodle (nginx) and a cockpit monitoring service (tiny http).

I did not install Apache, but maybe some php has it as dependency?

Must check reverse dependency on the system..

**Comment by Davka** [comment]
i think you install too many services on one host

**Comment by githlp** [comment]
well, i can not afford to rent a server per service ;-)

**Comment by Davka** [comment]
I can understand but I would run BBB and greenlight on their own server

**Comment by ffdixon** [comment]
The docs state that port 80 and 443 must not be in use by any other application.  You can not run apache2 on the same server as BigBlueButton.

https://docs.bigbluebutton.org/2.2/install.html#minimum-server-requirements
