### ISSUE TITLE
How can we upgrade to the latest alpha version of 2.3?

### ISSUE THREAD

**Issue by cod3r0k** [bigbluebutton/bbb-install#324]
Hi, I want to install the latest updated of 2.3-dev. But I found that it is not install the alpha version. Could you help me how can I do that?

for example how can I upgrade or install to "https://github.com/bigbluebutton/bigbluebutton/releases/tag/v2.3-alpha-4" ?

**Comment by ffdixon** [comment]
Just run the install script again at https://docs.bigbluebutton.org/dev/dev23.html#installation and it will automatically bring down the latest version.

**Comment by cod3r0k** [comment]
Dear @ffdixon , I run it again, but it is never changed. The alpha-4 version of 2.3-dev is not installed. 

`
wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v bionic-230-dev -s domain.com -e myemail@email  -a -w
`
The below screen shot doesn't have 2.3-dev latest features which mentioned. (like as question in poll or others...)
![image](https://user-images.githubusercontent.com/36899025/103421010-67eedf00-4baf-11eb-99f0-a02b5ba93219.png)

**Comment by ffdixon** [comment]
What is the version of BigBlueButton printed at the top of `sudo bbb-conf --check`?

**Comment by cod3r0k** [comment]
> What is the version of BigBlueButton printed at the top of `sudo bbb-conf --check`?

Dear @ffdixon , I check it. `BigBlueButton Server 2.3.0-alpha4 (1476)` was written!
But I never find any new features which BBB mentioned at https://docs.bigbluebutton.org/dev/dev23.html#features . Is there any mistake?

**Comment by ffdixon** [comment]
Some of those features are still in development (as indicated at the top of that page).  That's why we're still calling it an alpha release (development of core features has not yet finished).

**Comment by cod3r0k** [comment]
> Some of those features are still in development (as indicated at the top of that page). That's why we're still calling it an alpha release (development of core features has not yet finished).

Wow, Thank you so much for your support!
