### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by karussell** [bigbluebutton/bbb-install#334]
Thanks a lot for this script and big blue button in general - an amazing software!

I just installed it within 20 minutes without any problems, including https & domain etc.

```
wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -w -g -v xenial-22 -s bbb.example.com -e info@example.com
```

As I am using greenlight UI (`-g`) I only had to create an admin user:

```
docker exec greenlight-v2 bundle exec rake user:create["name","some@email.com","mypassword","admin"]
```

and disable public registration to suit my simple needs.

**Comment by ffdixon** [comment]
Thanks for kind words.  

We're thinking of disabling public registration by default as it makes more sense that the server is locked down at the beginning and only the administrator can login.
