### ISSUE TITLE
The script do not accept Ubuntu focal (20.04)

### ISSUE THREAD

**Issue by MirtoBusico** [bigbluebutton/bbb-install#336]
Please, when the last Ubuntu LTS will be supported by tne script?

**Comment by antobinary** [comment]
Kurento media server ( key part of BigBlueButton) does not support Ubuntu 20.04 yet afaik. BigBlueButton 2.3.x (in active development and released as 'alpha'  https://docs.bigbluebutton.org/dev/dev23.html ) runs on Ubuntu 18.04 bionic

**Comment by MirtoBusico** [comment]
> Kurento media server ( key part of BigBlueButton) does not support Ubuntu 20.04 yet afaik. BigBlueButton 2.3.x (in active development and released as 'alpha' https://docs.bigbluebutton.org/dev/dev23.html ) runs on Ubuntu 18.04 bionic
Thanks a lot. I'll install on a 18.04

**Comment by antobinary** [comment]
Looks like @MirtoBusico proceeded with the supported 18.04 bionic
