### ISSUE TITLE
Wrong parameters for turn-server installation (listening_ip, relay_ip)

### ISSUE THREAD

**Issue by werk21** [bigbluebutton/bbb-install#337]
In bbb-install.sh on lines 1108 and 1109 you write wrong config-items:

```
listening_ip=$IP
relay_ip=$IP
```

Correct configuration:

```
listening-ip=$IP
relay-ip=$IP
```
(Use `-` instead of `_`.)

Thank you for this cool installation tool!

**Comment by ffdixon** [comment]
Thanks for reporting this.  Fixed https://docs.bigbluebutton.org/2.2/setup-turn-server.html#configure-coturn.
