### ISSUE TITLE
do sudo apt-get update  error server certificate verification failed

### ISSUE THREAD

**Issue by ttfather** [bigbluebutton/bbb-install#34]
console info:
E: Failed to fetch https://ubuntu.bigbluebutton.org/xenial-200/dists/bigbluebutton-xenial/main/binary-amd64/Packages  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none

do wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v xenial-200 -s mydomain.com -e luxin@mydomain.com -t -g

nothing happens

**Comment by ttfather** [comment]
when id use --no-check-certificate option 
the error is  bbb-install: Unable to locate packages for xenial-200.
 i guess may be your ssl certificate lose efficacy

**Comment by ffdixon** [comment]
We just tried to it ourselves and the install worked -- can you try it again and let us know if you get the same error.
