### ISSUE TITLE
Turn Server via bbb-script: Wrong UDP port range in documentation

### ISSUE THREAD

**Issue by relecand** [bigbluebutton/bbb-install#344]
In the docs there is a wrong UDP port range:

49152-65535 | UDP | relay ports range

https://github.com/bigbluebutton/bbb-install#install-a-turn-server

Should be like here: https://docs.bigbluebutton.org/2.2/setup-turn-server.html#required-ports

Copy of: https://github.com/bigbluebutton/bbb-install/issues/333#issuecomment-772900639

All the best,

Christian

**Comment by ffdixon** [comment]
Fixed -- thanks!
