### ISSUE TITLE
missing wget leads to wrong error message

### ISSUE THREAD

**Issue by RokkuCode** [bigbluebutton/bbb-install#345]
If wget is not installed then the script quits with the error
```
Unable to locate packages for xenial-22 at ubuntu.bigbluebutton.org
```
This is misleading. The script should check for installed wget. This is neccessary if a user checks out the script via git and runs it instead of downloading via wget.

**Comment by ffdixon** [comment]
Thanks for reporting.  Fixed with https://github.com/bigbluebutton/bbb-install/commit/128923f54a2e9551e451fb7c173d4a866cfe2332.
