### ISSUE TITLE
error 1006 - microphone

### ISSUE THREAD

**Issue by migashde** [bigbluebutton/bbb-install#349]
error 1006 comes out after join audio with microphone. listen only, screenshare, camera works well
reinstalled bbb several times, does not help. test.bigbluebutton.org works well on same computer.
bbb-conf --check

BigBlueButton Server 2.2.33 (2347)
                    Kernel version: 4.4.0-203-generic
                      Distribution: Ubuntu 16.04.7 LTS (64-bit)
                            Memory: 32864 MB
                         CPU cores: 8

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://sub.mydomain.com
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server_name: sub.mydomain.com
                              port: 80, [::]:80
                              port: 443 ssl

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: <mylocalip>
                   external_rtp_ip: <mypublicip>
                   external_sip_ip: <mypublicip>

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${external_rtp_ip}
                        ext-sip-ip: $${external_sip_ip}
                        ws-binding: <mylocalip>:5066
                       wss-binding: <mypublicip>:7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: sub.mydomain.com
                 playback_protocol: https
                            ffmpeg: 4.2.4-1ubuntu0.1bbb1~16.04.1

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: <mypublicip>
                          protocol: https

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: <mylocalip>
                       kurento.url: ws://127.0.0.1:8888/kurento
                    kurento.sip_ip: <mylocalip>
                    localIpAddress: <mylocalip>
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 1140
                        kurentoUrl: wss://sub.mydomain.com/bbb-webrtc-sfu
                  enableListenOnly: true
                    sipjsHackViaWs: true

/usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml (STUN Server)
                              stun:stun.l.google.com:19302

 Potential problems described below

 Warning: The API demos are installed and accessible from:

    https://sub.mydomain.com

 and

    https://sub.mydomain.com/demo/demo1.jsp

 These API demos allow anyone to access your server without authentication
 to create/manage meetings and recordings. They are for testing purposes only.
 If you are running a production system, remove them by running:

    apt-get purge bbb-demo

**Comment by ffdixon** [comment]
Can you post this to [bigbluebutton-setup](https://groups.google.com/forum/#!forum/bigbluebutton-setup) and we'll help you there.  

> /etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
> proxy_pass:
> protocol: https

There is no value for `proxy_pass`, it should look something like this

```
location /ws {
        proxy_pass http://aaa.bbb.ccc.ddd:5066;
        proxy_http_version 1.1;
```

**Comment by migashde** [comment]
location /ws {
        proxy_pass https://<mypublicip>:7443;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_read_timeout 6h;
        proxy_send_timeout 6h;
        client_body_timeout 6h;
        send_timeout 6h;

        auth_request /bigbluebutton/connection/checkAuthorization;
        auth_request_set $auth_status $upstream_status;
}

**Comment by migashde** [comment]
i edited back to http and 5066 and edited  opt/freeswitch/conf/sip_profiles/external.xml
ws-binding local_ip to public_ip. now it works fine...
