### ISSUE TITLE
bbb-install: Unable to locate packages for xenial-200.

### ISSUE THREAD

**Issue by ttfather** [bigbluebutton/bbb-install#35]
i use this ./bbb-install.sh  -v xenial-200 -s mydomain.com -e info@mydomain.com -t -g -c mydomain.com:JJJ888aaa
to install bbb

the console info:
+ DISTRO=xenial
+ wget -qS --spider https://ubuntu.bigbluebutton.org/xenial-200/dists/bigbluebutton-xenial/Release.gpg
+ err 'Unable to locate packages for xenial-200.'
+ say 'Unable to locate packages for xenial-200.'
+ echo 'bbb-install: Unable to locate packages for xenial-200.'
bbb-install: Unable to locate packages for xenial-200.

**Comment by ffdixon** [comment]
Hmm -- others were reporting issues, but we just tried installing on a new server and it worked.

Can you try it again and let us know if your getting the same error.

**Comment by ttfather** [comment]
I try it again,works!  thank you !

**Comment by MarwanSdeek** [comment]
I am facing the same problem on Ubuntu 16.04 LTS
