### ISSUE TITLE
Kurento Media Server on 2.3-dev

### ISSUE THREAD

**Issue by lazyest** [bigbluebutton/bbb-install#350]
Is there only my issue when there is no Kurento Media Server installation candidate with script? Script is removing /etc/apt/sources.list.d/kurento.list arguing no more separate repo, but there is no kurento in other sources. I've chattr+i on kurento.list as workaround but I think there is something wrong here :) Ubuntu 18.04.

**Comment by lazyest** [comment]
workaround wrong, just copying it in another one with close filename but for some reason logic in script was broken and need to be fixed I believe :(

**Comment by ffdixon** [comment]
Just pushed a fix for this https://github.com/bigbluebutton/bbb-install/commit/f753eeeb2c95715ca45b78a14dfb5f6495eb81c0.

Can you try it again now and let us know if it works.

**Comment by lazyest** [comment]
I will, I promise ;)

**Comment by lazyest** [comment]
Confirming, script is back :) Thanks for a quick reaction.
