### ISSUE TITLE
[Solved] Invalid BigBlueButton Endpoint and Secret

### ISSUE THREAD

**Issue by heinrichrebehn** [bigbluebutton/bbb-install#351]
Hello,

I am getting above error after fresh install with bbb-install.sh.
I followed the instructions on the "Lear more" link, but to no avail.

`root@bbb:~# bbb-conf --check

BigBlueButton Server 2.2.35 (2390)
                    Kernel version: 4.4.0-203-generic
                      Distribution: Ubuntu 16.04.7 LTS (64-bit)
                            Memory: 8174 MB
                         CPU cores: 8

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://bbb.wtmhb.de
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server_name: bbb.wtmhb.de
                              port: 80, [::]:80
                              port: 443 ssl

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 5.9.137.145
                   external_rtp_ip: 5.9.137.145
                   external_sip_ip: 5.9.137.145

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: 5.9.137.145:5066
                       wss-binding: 5.9.137.145:7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: bbb.wtmhb.de
                 playback_protocol: https
                            ffmpeg: 4.2.4-1ubuntu0.1bbb1~16.04.1

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: 5.9.137.145
                          protocol: http

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: 5.9.137.145
                       kurento.url: ws://127.0.0.1:8888/kurento
                    kurento.sip_ip: 5.9.137.145
                    localIpAddress: 5.9.137.145
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 1144
                        kurentoUrl: wss://bbb.wtmhb.de/bbb-webrtc-sfu
                  enableListenOnly: true
                    sipjsHackViaWs: true

/usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml (STUN Server)
                              stun:stun.l.google.com:19302

# Potential problems described below

root@bbb:~# bbb-conf --status
nginx —————————————————► [✔ - active]
freeswitch ————————————► [✔ - active]
redis-server ——————————► [✔ - active]
bbb-apps-akka —————————► [✔ - active]
bbb-transcode-akka ————► [✔ - active]
bbb-fsesl-akka ————————► [✔ - active]
red5 ——————————————————► [✔ - active]
mongod ————————————————► [✔ - active]
bbb-html5 —————————————► [✔ - active]
bbb-webrtc-sfu ————————► [✔ - active]
kurento-media-server ——► [✔ - active]
etherpad ——————————————► [✔ - active]
bbb-web ———————————————► [✔ - active]
root@bbb:~/greenlight# docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check

Checking environment: Passed
Checking Connection: Passed
Checking Secret: Passed

`
I did a couple of successful installations before, so I don't understand why it is not working anymore.

**Comment by heinrichrebehn** [comment]
Hi,
I just downloaded a new version of bbb-install.sh from https://github.com/bigbluebutton/bbb-install
and it is working OOB now.
Thanks a lot!

BTW, is the above version always the same as the one that you get with
$ wget https://ubuntu.bigbluebutton.org/bbb-install.sh ?

-Heinrich

**Comment by ffdixon** [comment]
They are usually in sync, but sometimes we do testing first at the wget version.  Glad to hear you got it working.
