### ISSUE TITLE
Beta currently not available

### ISSUE THREAD

**Issue by lonesomewalker** [bigbluebutton/bbb-install#356]
bbb-install.sh -v bionic-230-dev currently only installs alpha version 8.

Should maybe be latest dev?

**Comment by ffdixon** [comment]
To install the 2.3-beta-1 (or upgrade from an alpha release), use the parameter (see [announcement](https://groups.google.com/g/bigbluebutton-dev/c/xAU3MZIWt_U/m/oYRqCvRfBAAJ))

```
  -v bionic-230
```

This switches you to the beta packages.
