### ISSUE TITLE
alpha7 can not be updated to the latest version

### ISSUE THREAD

**Issue by cod3r0k** [bigbluebutton/bbb-install#359]
Dear @ffdixon , I think there is some problem. Alpha7 can not be updated to the latest version (beta1) with the following common command :
`wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v bionic-230-dev -s domain -e email  -a -w`

**Comment by ffdixon** [comment]
Use `-v bionic-230`  (see [forum post on 2.3-beta-1](https://groups.google.com/g/bigbluebutton-dev/c/xAU3MZIWt_U/m/oYRqCvRfBAAJ)).
