### ISSUE TITLE
Upgrade to 2.3 on bionic from 2.2 on xenial

### ISSUE THREAD

**Issue by mhier** [bigbluebutton/bbb-install#366]
I am trying to install bbb 2.3 on bionic after upgrade from xenial (with do-release-upgrade). In that case I have an existing file `/etc/apt/sources.list.d/nodesource.list` but with all lines commented. As a consequence, the script won't download the new file and subsequently fail due to the missing nodejs 12 requirement. Maybe the check whether the file exists should be improved, or the file should be downloaded in any case, if nodejs 12 is not found.

**Comment by ffdixon** [comment]
We recommend folks start with a new 18.04 server (no prior version of BigBlueButton installed).

We have not tested upgrading BigBlueButton 2.2 -> 2.3 by updating an existing xenial server to bionic.  There are a lot of package changes that may conflict with the older version.  Recommend, if possible, starting with a new 18.04 server.

**Comment by mhier** [comment]
Well, it is not easily possible in my case (upgrade from home office). I am not asking for a guarantee for this to work, I am just trying to point out how to improve the script to make such upgrade easier.

Another helpful thing would be to uninstall old BBB 2.2 packages if present, or at least warn about them and ask the user to uninstall them.

**Comment by jibon57** [comment]
@mhier I've written a blog post on it. You can read it from here: [How to upgrade BigBlueButton 2.2 to 2.3 (Ubuntu 16.04 to 18.04)](https://www.mynaparrot.com/blog/180-how-to-upgrade-bigbluebutton-2-2-to-2-3-ubuntu-16-04-to-18-04) but make sure you've read the warnings.

@ffdixon I ain't sure linking some page is allow here or not. If not allow then can delete my comment.

**Comment by mhier** [comment]
> @mhier I've written a blog post on it. You can read it from here: [How to upgrade BigBlueButton 2.2 to 2.3 (Ubuntu 16.04 to 18.04)](https://www.mynaparrot.com/blog/180-how-to-upgrade-bigbluebutton-2-2-to-2-3-ubuntu-16-04-to-18-04) but make sure you've read the warnings.

Thanks, I already managed to do the upgrade. I listed all my trouble points in by post above.

**Comment by ffdixon** [comment]
Thanks @jibon57 for sharing the link.

**Comment by angelaki** [comment]
Does install.sh support 2.3 stable (Wooohooo!) already?

**Comment by abockhold** [comment]
> Does install.sh support 2.3 stable (Wooohooo!) already?

Yes, it does since quite some time. Use "-v bionic-230" (but be careful to do this on an Ubuntu 18.04).

**Comment by octomike** [comment]
> We recommend folks start with a new 18.04 server (no prior version of BigBlueButton installed).

Curious, how would I migrate existing rooms/users to the new instance?

**Comment by ffdixon** [comment]
Sorry, should have put in a link to the docs.  See https://docs.bigbluebutton.org/2.2/customize.html#transfer-recordings

**Comment by staeglis** [comment]
The link is only about transferring recordings and not about transferring the users/rooms /Greenlight) or have I've missed something?

**Comment by peterVoisin** [comment]
@jibon57 
I'm also trying to update my BBB 2.2 on Ubuntu 16.04 to 2.3 on 18.04.
By following your procedure, everything seems to be going well but BBB does not work, I get a 404 not found error when launching a room.

**Comment by jibon57** [comment]
Can you run `bbb-conf --check` & give output here?

**Comment by peterVoisin** [comment]
... I use an LXC container and I see in the log
`Starting BigBlueButton HTML5 service...`
`systemd[1]: Started BigBlueButton HTML5 service.`
`systemd[1]: bbb-html5.service: Failed to reset devices.list: Operation not permitted`
My problem may be here 
Sorry I restored a backup, I'll post the bbb-conf --check output when I can try again

**Comment by staeglis** [comment]
@jibon57 If I follow your guide, I have to delete a lot of files? Are all rooms and relevant settings preserved during the update?

**Comment by peterVoisin** [comment]
@staeglis The Jibon57 guide doesn't make any changes to your Greenlight instance, you keep all your users / rooms / records.
But this is a new install of BBB, you will need to reconfigure your `.env` with `bbb-conf --secret `.

**Comment by staeglis** [comment]
In this case I would prefer doing a clean installation on new virtual machine with migrating the settings / your users / rooms / record. How I can achieve this?

**Comment by EmmyGraugans** [comment]
Simply copy the recordings and the greenlight to the new instance. Everything else will (and should) be new.

**Comment by peterVoisin** [comment]
Hello, I tried to update again and and I have come to the same issue.
I get a 404 not found error when launching a room.

bbb-conf --check
`BigBlueButton Server 2.3.1 (2209)
                    Kernel version: 5.4.106-1-pve
                      Distribution: Ubuntu 18.04.5 LTS (64-bit)
                            Memory: 8392 MB
                         CPU cores: 12

/etc/bigbluebutton/bbb-web.properties (override for bbb-web)
/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://visio.mairie-mayenne.net
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server_name: visio.mairie-mayenne.net
                              port: 80, [::]:80
                              port: 443 ssl

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 146.59.213.204
                   external_rtp_ip: 146.59.213.204
                   external_sip_ip: 146.59.213.204

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: 146.59.213.204:5066
                       wss-binding: 146.59.213.204:7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: visio.mairie-mayenne.net
                 playback_protocol: https
                            ffmpeg: 4.2.4-1ubuntu0.1bbb2~18.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: 146.59.213.204
                          protocol: http

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: 146.59.213.204
                       kurento.url: ws://127.0.0.1:8888/kurento
                    kurento.sip_ip: 146.59.213.204
                    localIpAddress: 146.59.213.204
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 1720
                        kurentoUrl: wss://visio.mairie-mayenne.net/bbb-webrtc-sfu
                  enableListenOnly: true
                    sipjsHackViaWs: true

/usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml (STUN Server)
                              stun: stun.l.google.com:19302


# Potential problems described below`

**Comment by Bschalck** [comment]
Hy @peterVoisin  , did you solve you problem ?

**Comment by peterVoisin** [comment]
Hi @Bschalck, yes I solved it.
I reinstall a vm with KVM to replace the container(LXC), and transferred my Greenlight and its database.
It's less light...

Thanks

**Comment by nasilaj** [comment]
Thank you for your email.
I have tried to install BBB but I cant succeed.

Please help
