### ISSUE TITLE
cannot locate /var/www/bigbluebutton/client/conf/config.xml

### ISSUE THREAD

**Issue by ibondoc** [bigbluebutton/bbb-install#369]
I'm trying to configure our BBB 2.3 server to disable listenOnly, but i cannot seem to locate config.xml. did the directories for these config files change?

the /conf directory does not exist as well.

**Comment by joo4mart** [comment]
The configuration have changed for bbb 2.3 and some file does not exist anymore. But now we have a better better way for overriding configuration. Details see here: [https://docs.bigbluebutton.org/2.3/install.html#local-overrides-for-configuration-settings](https://docs.bigbluebutton.org/2.3/install.html#local-overrides-for-configuration-settings)
