### ISSUE TITLE
bionic-23 is not available on packages-eu.bigbluebutton.org

### ISSUE THREAD

**Issue by wolbernd** [bigbluebutton/bbb-install#373]
When running bbb-install.sh with the following parameters:

`bbb-install.sh -v bionic-23 -s xyz -r packages-eu.bigbluebutton.org -d -c abc:$3cr3t`

I get the following error message: `Unable to locate packages for bionic-23 at packages-eu.bigbluebutton.org`

What does work:
`bbb-install.sh -v bionic-230 -s xyz -r packages-eu.bigbluebutton.org -d -c abc:$3cr3t` 

`bbb-install.sh -v bionic-23 -s xyz -d -c abc:$3cr3t`

It seems like there is something missing on packages-eu server. I'm not sure if this server is officially supported however it is mentioned in the README

**Comment by ffdixon** [comment]
> bbb-install.sh -v bionic-23 -s xyz -r packages-eu.bigbluebutton.org -d -c abc:$3cr3t

Fixed -- this should work now going forward.
