### ISSUE TITLE
NAT Ports

### ISSUE THREAD

**Issue by Tampa** [bigbluebutton/bbb-install#38]
Installed using bbb-install.sh after removing local IP check. Installed only complained about 
My problem is a fairly dense network requires running on non-standard ports, meaning 80 and 443 are already in use. I changed nginx to use 8501 and 8511 instead. Externally using these I can reach through nginx, but get:

HTTP Status 404 - /bigbluebutton//join
type Status report
message /bigbluebutton//join
description The requested resource is not available.
Apache Tomcat/7.0.68 (Ubuntu)

What other configs need changing?

Also, is there a way to restrict UDP ports for freeswitch to a smaller range of 32000 to 35000?

**Comment by ffdixon** [comment]
BigBlueButton has a lot of dependencies on port 80/443.  We (the core developers) haven't tried running it on any other ports except 80/443.

For Kurento/FreeSWITCH port range, see

  https://github.com/bigbluebutton/bigbluebutton/issues/5156

**Comment by Tampa** [comment]
I cannot use the default ports due to clash with vsphere and crawling the entire system to find references is difficult. An overview of all used dependencies and/or their config files and locations would greatly help.

**Comment by sijuthankachan** [comment]
Hi Team,
UDP port range 16384-32768 arround 16384 ports need to keep open in the server is risk correct? Always its too difficult to get the approval from the server security teams.
Is any other alternative to achive this with less risk?
