### ISSUE TITLE
bbb-install.sh dependency error

### ISSUE THREAD

**Issue by Miro3IT** [bigbluebutton/bbb-install#380]
Hi!

I'm trying to run bbb-instal.sh (with only -v bionic-23 -s <FQDN> -d)
on fresh installed Ubuntu 18.04
but I get dpkg error processing package...
dependency problem....

errors while processing
redis-server
bbb-record-core
bbb-web
bbb-playback-presentation
bbb-html5
bbb-libreoffice-docker
bbb-playback
bbb-config
bigbluebutton

last line i see is Setting up redis-server
I've tried several options from different posts, but no luck - I must be missing sumting fundamental ;-/

a -d option is not realy clear - can't find the info - do I have to upload cert. to the specific location before runnig the installation script or do I set it later ?

server has public IP with DNS A and PTR records set

**Comment by ffdixon** [comment]
Check out this part of `bbb-install.sh`

  https://github.com/bigbluebutton/bbb-install/blob/master/bbb-install.sh#L877

Can you try placing your certificates at  `/local/certs/fullchain.pem` and `/local/certs/privkey.pem` and `bbb-install.sh` will make the appropriate symbolic links so they are found by `/etc/nginx/sites-available/bigbluebutton`.

**Comment by Miro3IT** [comment]
OK, thanks,  I'll try tomorow and report the result.

**Comment by Miro3IT** [comment]
I got some more time today and uploaded the PEM files, then rerun the script, but no difference ;-(

**Comment by ffdixon** [comment]
Can you post the full output from `bbb-install.sh` so we can see the error.

**Comment by Miro3IT** [comment]
Hit:1 http://archive.ubuntu.com/ubuntu xenial InRelease
Get:2 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [109 kB]
Hit:3 http://ppa.launchpad.net/bigbluebutton/support/ubuntu bionic InRelease
Hit:4 http://ppa.launchpad.net/certbot/certbot/ubuntu bionic InRelease
Hit:5 https://deb.nodesource.com/node_12.x bionic InRelease
Hit:6 http://ppa.launchpad.net/libreoffice/ppa/ubuntu bionic InRelease
Hit:7 http://archive.ubuntu.com/ubuntu bionic InRelease
Get:8 http://security.ubuntu.com/ubuntu xenial-security InRelease [109 kB]
Ign:9 https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 InRelease
Hit:10 http://ppa.launchpad.net/rmescandon/yq/ubuntu bionic InRelease
Hit:11 https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 Release
Hit:12 https://ubuntu.bigbluebutton.org/bionic-23 bigbluebutton-bionic InRelease
Fetched 218 kB in 1s (160 kB/s)
Reading package lists...
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
LESSCLOSE=/usr/bin/lesspipe %s %s
LANG=en_US.UTF-8
INVOCATION_ID=ff178d14854244909b3fc59aff5eef96
XDG_VTNR=1
XDG_SESSION_ID=16
HUSHLOGIN=FALSE
USER=root
PWD=/root
HOME=/root
JOURNAL_STREAM=9:218600
DEBIAN_FRONTEND=noninteractive
MAIL=/var/mail/root
TERM=linux
SHELL=/bin/bash
XDG_SEAT=seat0
SHLVL=2
LOGNAME=root
XDG_RUNTIME_DIR=/run/user/0
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
LESSOPEN=| /usr/bin/lesspipe %s
_=/usr/bin/env
deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 multiverse
/usr/bin/docker
Successfully installed bundler-2.1.4
Parsing documentation for bundler-2.1.4
Done installing documentation for bundler after 4 seconds
1 gem installed
Hit:1 https://deb.nodesource.com/node_12.x bionic InRelease
Hit:2 http://archive.ubuntu.com/ubuntu xenial InRelease
Hit:3 http://ppa.launchpad.net/bigbluebutton/support/ubuntu bionic InRelease
Hit:4 http://archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:5 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:6 http://ppa.launchpad.net/certbot/certbot/ubuntu bionic InRelease
Ign:7 https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 InRelease
Hit:8 http://ppa.launchpad.net/libreoffice/ppa/ubuntu bionic InRelease
Hit:9 https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 Release
Hit:10 http://security.ubuntu.com/ubuntu xenial-security InRelease
Hit:11 http://ppa.launchpad.net/rmescandon/yq/ubuntu bionic InRelease
Hit:12 https://ubuntu.bigbluebutton.org/bionic-23 bigbluebutton-bionic InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
Calculating upgrade...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
9 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up redis-server (5:4.0.9-1ubuntu0.2) ...
Job for redis-server.service failed because a timeout was exceeded.
See "systemctl status redis-server.service" and "journalctl -xe" for details.
invoke-rc.d: initscript redis-server, action "start" failed.
● redis-server.service - Advanced key-value store
   Loaded: loaded (/lib/systemd/system/redis-server.service; disabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: timeout) since Mon 2021-05-24 19:57:19 CEST; 13ms ago
     Docs: http://redis.io/documentation,
           man:redis-server(1)
dpkg: error processing package redis-server (--configure):
 installed redis-server package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of bbb-record-core:
 bbb-record-core depends on redis-server; however:
  Package redis-server is not configured yet.

dpkg: error processing package bbb-record-core (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of bbb-web:
 bbb-web depends on redis-server; however:
  Package redis-server is not configured yet.

dpkg: error processing package bbb-web (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of bbb-playback-presentation:
 bbb-playback-presentation depends on bbb-record-core; however:
  Package bbb-record-core is not configured yet.

dpkg: error processing package bbb-playback-presentation (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of bbb-html5:
 bbb-html5 depends on bbb-web; however:
  Package bbb-web is not configured yet.

dpkg: error processing package bbb-html5 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of bbb-libreoffice-docker:
 bbb-libreoffice-docker depends on bbb-record-core; however:
  Package bbb-record-core is not configured yet.

dpkg: error processing package bbb-libreoffice-docker (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of bbb-playback:
 bbb-playback depends on bbb-record-core; however:
  Package bbb-record-core is not configured yet.

dpkg: error processing package bbb-playback (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of bbb-config:
 bbb-config depends on bbb-html5; however:
  Package bbb-html5 is not configured yet.
 bbb-config depends on bbb-playback-presentation; however:
  Package bbb-playback-presentation is not configured yet.
 bbb-config depends on bbb-playback; however:
  Package bbb-playback is not configured yet.

dpkg: error processing package bbb-config (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of bigbluebutton:
 bigbluebutton depends on bbb-config; however:
  Package bbb-config is not configured yet.

dpkg: error processing package bigbluebutton (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 redis-server
 bbb-record-core
 bbb-web
 bbb-playback-presentation
 bbb-html5
 bbb-libreoffice-docker
 bbb-playback
 bbb-config
 bigbluebutton

# BigBlueButton does not appear to be installed.  Could not
# locate: /etc/bigbluebutton/bigbluebutton-release

Reading package lists...
Building dependency tree...
Reading state information...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
9 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up redis-server (5:4.0.9-1ubuntu0.2) ...
Job for redis-server.service failed because a timeout was exceeded.
See "systemctl status redis-server.service" and "journalctl -xe" for details.
invoke-rc.d: initscript redis-server, action "start" failed.
● redis-server.service - Advanced key-value store
   Loaded: loaded (/lib/systemd/system/redis-server.service; disabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: timeout) since Mon 2021-05-24 19:58:50 CEST; 67ms ago
     Docs: http://redis.io/documentation,
           man:redis-server(1)
dpkg: error processing package redis-server (--configure):
 installed redis-server package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of bbb-record-core:
 bbb-record-core depends on redis-server; however:
  Package redis-server is not configured yet.

dpkg: error processing package bbb-record-core (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of bbb-web:
 bbb-web depends on redis-server; however:
  Package redis-server is not configured yet.

dpkg: error processing package bbb-web (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of bbb-playback-presentation:
 bbb-playback-presentation depends on bbb-record-core; however:
  Package bbb-record-core is not configured yet.

dpkg: error processing package bbb-playback-presentation (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of bbb-html5:
 bbb-html5 depends on bbb-web; however:
  Package bbb-web is not configured yet.

dpkg: error processing package bbb-html5 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of bbb-libreoffice-docker:
 bbb-libreoffice-docker depends on bbb-record-core; however:
  Package bbb-record-core is not configured yet.

dpkg: error processing package bbb-libreoffice-docker (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of bbb-playback:
 bbb-playback depends on bbb-record-core; however:
  Package bbb-record-core is not configured yet.

dpkg: error processing package bbb-playback (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of bbb-config:
 bbb-config depends on bbb-html5; however:
  Package bbb-html5 is not configured yet.
 bbb-config depends on bbb-playback-presentation; however:
  Package bbb-playback-presentation is not configured yet.
 bbb-config depends on bbb-playback; however:
  Package bbb-playback is not configured yet.

dpkg: error processing package bbb-config (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of bigbluebutton:
 bigbluebutton depends on bbb-config; however:
  Package bbb-config is not configured yet.

dpkg: error processing package bigbluebutton (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 redis-server
 bbb-record-core
 bbb-web
 bbb-playback-presentation
 bbb-html5
 bbb-libreoffice-docker
 bbb-playback
 bbb-config
 bigbluebutton

# BigBlueButton does not appear to be installed.  Could not
# locate: /etc/bigbluebutton/bigbluebutton-release


# BigBlueButton does not appear to be installed.  Could not
# locate: /etc/bigbluebutton/bigbluebutton-release

**Comment by Miro3IT** [comment]
I guess it all startr with:
Setting up redis-server (5:4.0.9-1ubuntu0.2) ...
Job for redis-server.service failed because a timeout was exceeded.
See "systemctl status redis-server.service" and "journalctl -xe" for details.
invoke-rc.d: initscript redis-server, action "start" failed.
will try to get this detatils...

**Comment by Miro3IT** [comment]
redis-server.service status log:
 redis-server.service - Advanced key-value store
   Loaded: loaded (/lib/systemd/system/redis-server.service; disabled; vendor preset: enabled)
   Active: activating (start) since Mon 2021-05-24 21:48:23 CEST; 58s ago
     Docs: http://redis.io/documentation,
           man:redis-server(1)
  Process: 4701 ExecStart=/usr/bin/redis-server /etc/redis/redis.conf (code=exited, status=0/SUCCESS)
    Tasks: 0 (limit: 4915)
   CGroup: /system.slice/redis-server.service

May 24 21:48:23 <FQDN> systemd[1]: Starting Advanced key-value store...
May 24 21:48:23 <FQDN> systemd[1]: redis-server.service: Can't open PID file /var/run/redis/redis-server.pid (yet?) after start: No such file or directory

**Comment by ffdixon** [comment]
Are you installing BigBlueButton on a clean Ubuntu 18.04 64-bit server, with no prior installation of BigBlueButton 2.2?

Your apt-get update is showing references to xenial??

```
Hit:1 https://deb.nodesource.com/node_12.x bionic InRelease
Hit:2 http://archive.ubuntu.com/ubuntu xenial InRelease
Hit:3 http://ppa.launchpad.net/bigbluebutton/support/ubuntu bionic InRelease
Hit:4 http://archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:5 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:6 http://ppa.launchpad.net/certbot/certbot/ubuntu bionic InRelease
Ign:7 https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 InRelease
Hit:8 http://ppa.launchpad.net/libreoffice/ppa/ubuntu bionic InRelease
Hit:9 https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 Release
Hit:10 http://security.ubuntu.com/ubuntu xenial-security InRelease
Hit:11 http://ppa.launchpad.net/rmescandon/yq/ubuntu bionic InRelease
Hit:12 https://ubuntu.bigbluebutton.org/bionic-23 bigbluebutton-bionic InRelease
```

You should see

```
Hit:1 https://download.docker.com/linux/ubuntu bionic InRelease
Get:2 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]                                                                                                              
Get:3 http://mirrors.digitalocean.com/ubuntu bionic InRelease [242 kB]                                                                                                                   
Hit:4 https://deb.nodesource.com/node_12.x bionic InRelease                                                                                                                              
Ign:5 https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 InRelease                                                                                                              
Hit:6 https://ubuntu.bigbluebutton.org/bionic-23-dev bigbluebutton-bionic InRelease                                                                                                     
Hit:7 https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 Release                                                       
Hit:8 http://ppa.launchpad.net/bigbluebutton/support/ubuntu bionic InRelease                             
Hit:9 http://archive.ubuntu.com/ubuntu bionic InRelease                                                                             
Get:10 http://mirrors.digitalocean.com/ubuntu bionic-updates InRelease [88.7 kB]                                                    
Get:11 http://mirrors.digitalocean.com/ubuntu bionic-backports InRelease [74.6 kB]                                        
Hit:12 http://ppa.launchpad.net/certbot/certbot/ubuntu bionic InRelease              
Hit:14 http://ppa.launchpad.net/libreoffice/ppa/ubuntu bionic InRelease                                                   
Hit:15 http://ppa.launchpad.net/rmescandon/yq/ubuntu bionic InRelease                   
Get:16 http://mirrors.digitalocean.com/ubuntu bionic-updates/main amd64 Packages [2070 kB]
Get:17 http://mirrors.digitalocean.com/ubuntu bionic-updates/universe amd64 Packages [1735 kB]
Fetched 4299 kB in 1s (2915 kB/s)                                                      
```

**Comment by Miro3IT** [comment]
no, there was no prior instalation, however, after error I did some reopsitory changes as sugested in some forums...
I'l copy your sources to my list and retry

**Comment by Miro3IT** [comment]
reseting sources do default and reruning script didn't help

**Comment by Miro3IT** [comment]
in journalctl report I foud this problem:
May 24 23:53:04 FQDN bbb-webrtc-sfu[827]: 2021-05-24T21:53:04.397Z - error: [mcs-freeswitch-esl-wrapper] FreeSWITCH ESL connection received error ECONNREFUSED errno=ECONNREFUSED, code=ECONNREFUSED, syscall=connect, address=127.0.0.1, port=8021

**Comment by Miro3IT** [comment]
OK, I have absolutely no idea what went wrog two days ago, but I am almost sure I did the same thing today, except I aded another (-w) switch

-  fresh install Ubuntu
- change /etc/hostname with FQDN, reboot
- LANG="en_US.UTF-8"
- DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
- x86_64
- enable_ipv6, reboot
- DNS set A, AAAA, PTR4, PTR6
- inet6 ::1/128 scope host OK
- kernel 4.15.0-143-generic
- 6 cores / 12 threads (4 CPU cores/8 GB of memory should be OK for testing)
- create /local/certs
- upload fullchain.pem + privkey.pem
wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v bionic-230 -s FQDN -w -d >> install.log

this time instalation finised with no errors. - Now let's "play" with it ;-p
Thanks for help @ffdixon
