### ISSUE TITLE
Use HTML5 version for production use

### ISSUE THREAD

**Issue by hamidaspnet** [bigbluebutton/bbb-install#39]
HI.
Do you advice  HTML5 version for production use?

Thanks.

Best regards

**Comment by ffdixon** [comment]
In the future, can you post general questions to the bigbluebutton-dev mailing list, see

   https://groups.google.com/forum/#!forum/bigbluebutton-dev

There have been companies using the HTML5 version in BigBlueButton 2.0 for production.  There is a lot of work going on in BigBlueButton 2.2-beta, which is currently running on https://test.bigbluebutton.org/.

We've not released packages for BigBlueButton 2.2-beta yet.  Look for a post to bigbluebutton-dev when it's available.
