### ISSUE TITLE
Certificate for "ubuntu.bigbluebutton.org" is out of date.

### ISSUE THREAD

**Issue by arashjl** [bigbluebutton/bbb-install#396]
Hi,

It seems the certificate for ubuntu.bigbluebutton.org is out of date.

```
--2021-07-16 05:54:08--  https:// is out of date./bbb-install.sh
Resolving ubuntu.bigbluebutton.org (ubuntu.bigbluebutton.org)... 85.10.207.48, 176.9.122.176, 136.243.104.113
Connecting to ubuntu.bigbluebutton.org (ubuntu.bigbluebutton.org)|85.10.207.48|:443... connected.
ERROR: cannot verify ubuntu.bigbluebutton.org's certificate, issued by ‘CN=R3,O=Let's Encrypt,C=US’:
  Issued certificate has expired.
To connect to ubuntu.bigbluebutton.org insecurely, use `--no-check-certificate'.
```

**Comment by ffdixon** [comment]
We've renewed the certificate for ubuntu.bigbluebutton.org (sorry about that).  Checking to see why the auto-renewal didn't work.

**Comment by arashjl** [comment]
> We've renewed the certificate for ubuntu.bigbluebutton.org (sorry about that). Checking to see why the auto-renewal didn't work.

Thank you for your great job on this incredible project.
It allowed many people and students to continue learning from their own home without taking a risk on their lives.

**Comment by ffdixon** [comment]
Thanks for the feedback -- if you have a twitter account, can you tweet out this feedback - thanks!  It helps spread awareness of our project.
