### ISSUE TITLE
html5 client use after green light installation

### ISSUE THREAD

**Issue by kmp8072** [bigbluebutton/bbb-install#4]
i have installesd the green light front end for bbb now i am unable to launch html5 client. how to launch it

**Comment by antobinary** [comment]
Hey @kmp8072 

If you have `bbb-html5` running, all Android or iOS users will be redirected to the html5 client by default.
In addition, you can modify the following flags in `bigbluebutton.properties` if you want to force certain user types to be using the html5 client only:
https://github.com/bigbluebutton/bigbluebutton/blob/master/bigbluebutton-web/grails-app/conf/bigbluebutton.properties#L182-L190

In the future please post your questions at https://groups.google.com/forum/#!forum/bigbluebutton-dev or https://groups.google.com/forum/#!forum/bigbluebutton-setup
