### ISSUE TITLE
Update bbb flash version to HTML5

### ISSUE THREAD

**Issue by hamidaspnet** [bigbluebutton/bbb-install#40]
Hi,
I installed flash version with SSL using with Let's Encrypt.
I want update it to HTML5.
Do you advice update it or uninstall it first and insatll HTML5 version?

Thanks

Bets regard

**Comment by ffdixon** [comment]
For steps to install the HTML5 version, see

   http://docs.bigbluebutton.org/html/html5-install.html

You can also use bbb-install.sh to automate the installation of BigBlueButton + HTML5 + SSL (via Let's Encrypt).  See

  https://github.com/bigbluebutton/bbb-install
