### ISSUE TITLE
Restart ubuntu OS when re run bbb-install bash script

### ISSUE THREAD

**Issue by MrCapitalist** [bigbluebutton/bbb-install#400]
Hello dear Fred Dixon and other BBB teams

I have a problem when running bbb-install script after running it before. 

I installed BBB and because of the problem with my connections, the installation has didn't complete. Now when I want to execute this script again, OS will be reboot!!!! Therefore I can't repair or upgrade my BBB!!
Please check the script again
Thanks

**Comment by ffdixon** [comment]
>  the installation has didn't complete.

Can you give more details on the error that was printed when it didn't complete.

**Comment by MrCapitalist** [comment]
Nothing! It only reboots the OS in a few seconds after I hit enter

**Comment by MrCapitalist** [comment]
I run it again and it is fixed now!
