### ISSUE TITLE
new release bbb 2.4 development

### ISSUE THREAD

**Issue by koliosx** [bigbluebutton/bbb-install#402]
After the upgrade to 2.4 (stable version) with the cam backround development and efects, Users that are waiting in the lobby never join to conference even i accept them..

**Comment by ffdixon** [comment]
BigBlueButton 2.4 is currently alpha-2 and is under active development.  Thanks for letting us know.

**Comment by koliosx** [comment]
Dear ffdixon,

Thanks !!! you are doing Great Job...

**Comment by GhaziTriki** [comment]
A lot of releases are in the wild after this issue.
