### ISSUE TITLE
systemctl reload nginx instead of systemctl restart nginx for certbot renewal

### ISSUE THREAD

**Issue by d3hof** [bigbluebutton/bbb-install#405]
I just realised that the installscripts adds the line renewal_hook=systemctl restart nginx to the .conf for the bbb-domain in /etc/letsencrypt/renewal. I'm not sure but isn't that run on every renewal of a certificate?
So everytime a certificate is renewed nginx is restartet, what would mean a loss of connection for all clients.
A nicer way to this would be systemctl reload nginx, as it also applies the new configuration but without a connection loss for the clients.
Or is there something that I'm missing?

**Comment by michi-80337** [comment]
The renewal happens every two months, and by moving it into the night, there are good chances, that no conference is running when certificates are renewed. But You are correct, after a `nginx restart` all current users will have to reconnect their webcams and microphones.

A sysctl reload nginx will be enough to load the renewed certificate, and it will avoid the annoyance for the users.
