### ISSUE TITLE
Problem with BigBlueButton install

### ISSUE THREAD

**Issue by babak-hannani** [bigbluebutton/bbb-install#410]
How can I disable IPv6 when I install bigbluebutton 2.3? My Internet Provider does not support IPv6 and when install bigbluebutton, error occur. I must disable "listen to IPv6" in Nginx configuration during installation.

And where can I find manual installation guide for bigbluebutton 2.3 . I don't want to use script for installation.

**Comment by ffdixon** [comment]
What error are you getting when you install?

**Comment by babak-hannani** [comment]
nginx and redis service have error when start. (when use "nginx -t"    =>    Error:can not listen on IPv6)
When I disable IPv6 from nginx, redis and freeswitch configuration, bigbluebutton works correctly.

**Comment by ffdixon** [comment]
Good to hear.  For the benefit of others, can you share how you disabled IPv6 from your configuration.

**Comment by babak-hannani** [comment]
Steps of Tshoot :
1- Run install script for first time
2- Change redis configuration :
    Edit /etc/redis/redis.conf
>>> bind 127.0.0.1
>>> supervised systemd
3- Change Nginx configuration :
    Edit /etc/nginx/sites-enabled/bigbluebutton
>>> # listen [::]:80;
>>> # listen [::]:443 ssl;
    Edit /etc/nginx/sites-available/bigbluebutton
>>> # listen [::]:80;
>>> # listen [::]:443 ssl;
4- Run install script again
NOTE => During installation, you must do step 3 again. (You can do it when Error "443 - Connection Refused" appear or when you see those configs are not comment)
5- If installation finished successfully, disable IPv6 :
    Edit /opt/freeswitch/etc/freeswitch/autoload_configs/event_socket.conf.xml
>>> <param name="listen-ip" value="127.0.0.1"/>
    mv /opt/freeswitch/etc/freeswitch/sip_profiles/internal-ipv6.xml /opt/freeswitch/etc/freeswitch/sip_profiles/internal-ipv6.xml_
    mv /opt/freeswitch/etc/freeswitch/sip_profiles/external-ipv6.xml /opt/freeswitch/etc/freeswitch/sip_profiles/external-ipv6.xml_
    bbb-conf --clean
    bbb-conf --check

**Comment by babak-hannani** [comment]
Please add manual guide in website.
and
Please add flag for disable IPv6 when use bbb-install.sh

Thanks

**Comment by ctrlbrk42** [comment]
Is there still no flag during install? I'm having the same issue
