### ISSUE TITLE
can't install BBB on Ubuntu 18.04

### ISSUE THREAD

**Issue by Muller7777** [bigbluebutton/bbb-install#413]
trying to put bigbluebutton on Ubuntu 18.04 virtual container

according to the instructions from the off site in one script https://github.com/bigbluebutton/bbb-install/tree/master

does not work, stops at this

dpkg: error processing package bbb-libreoffice-docker (–configure): installed bbb-libreoffice-docker package post-installation script subprocess returned error exit status 1 dpkg: dependency problems prevent configuration of bbb-web: bbb-web depends on bbb-libreoffice-docker; however: Package bbb-libreoffice-docker is not configured yet.

dpkg: error processing package bbb-web (–configure): dependency problems - leaving unconfigured dpkg: dependency problems prevent configuration of bbb-html5: bbb-html5 depends on bbb-web; however: Package bbb-web is not configured yet.

dpkg: error processing package bbb-html5 (–configure): dependency problems - leaving unconfigured dpkg: dependency problems prevent configuration of bbb-config: bbb-config depends on bbb-html5; however: Package bbb-html5 is not configured yet.

dpkg: error processing package bbb-config (–configure): dependency problems - leaving unconfigured dpkg: dependency problems prevent configuration of bigbluebutton: bigbluebutton depends on bbb-config; however: Package bbb-config is not configured yet.

dpkg: error processing package bigbluebutton (–configure): dependency problems - leaving unconfigured Errors were encountered while processing: bbb-libreoffice-docker bbb-web bbb-html5 bbb-config bigbluebutton E: Sub-process /usr/bin/dpkg returned an error code (1)

BigBlueButton does not appear to be installed. Could not
locate: /etc/bigbluebutton/bigbluebutton-release
BigBlueButton does not appear to be installed. Could not
locate: /etc/bigbluebutton/bigbluebutton-release

**Comment by ffdixon** [comment]
> dpkg: error processing package bbb-libreoffice-docker (–configure): installed bbb-libreoffice-docker package 

What virtualization environment are you using?  BigBlueButton 2.3 used docker to encapsulate LibreOffice.  Also check out https://github.com/bigbluebutton/docker.

**Comment by Muller7777** [comment]
I have an Ubuntu 18.04 virtual machine
, collected by the container. I'm trying to install BBB 2.3 according to the instructions in one script from the site 

wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -w -a -v bionic-23 -s

**Comment by ffdixon** [comment]
Does the virtual machine support running docker within it?

**Comment by mohammad-69** [comment]
I have the same problem what's the solution? 

`Errors were encountered while processing:
 bbb-libreoffice-docker
 bbb-web
 bbb-html5
 bbb-config
 bigbluebutton
E: Sub-process /usr/bin/dpkg returned an error code (1)`

**Comment by ffdixon** [comment]
What is the parameter you are using for `-v` in the `bbb-install.sh` command?

**Comment by mohammad-69** [comment]
> What is the parameter you are using for `-v` in the `bbb-install.sh` command?
I've used below commands none of them worked on any type of ubuntu version : 
on ubuntu 18.04:
wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v bionic-23 -s s2.domain.com -e mymail@example.com -w -g

wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v  bionic-240 -s s2.domain.com -e mymail@example.com -a -w 

on ubuntu 16.04 : 
wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v  xenial-22 -s s2.domain.com -e mymail@example.com -w -g
