### ISSUE TITLE
It is no loading after providing IP + Salt to my wordpress

### ISSUE THREAD

**Issue by Coinizy1** [bigbluebutton/bbb-install#43]
Hi, ThankYOU so much for replying everyone everwhere. You guyz are doing a great job.
I have small problem today.
I made a new AWS server and allow all ports on my server to 0.0.0.0 means everywhere.
Then i installed the BBB server via this wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v xenial-200 
Now i took ip/bigbluebutton/ and salt key and entered it to my wordpress site config page (wordpress is hosted on some other server is taht a problem?)
Now when i make a meeting and click on join it is running and i am seeing my own webcam (i logged into wordpress from admin and clicked on join meeting)
Now when i copy this url and opens in incognito mode of firefox while logged into wordpress as contributor i am seeing failed to fetch config.xml why?
Please see screenshot
Thanks
![image](https://user-images.githubusercontent.com/31903098/54364895-a4c2ac80-468f-11e9-9bfd-906c31b7d8d0.png)

**Comment by ffdixon** [comment]
To narrow this down a bit, are you able to join BigBlueButton from the default home page on your BigBlueButton server?

**Comment by Coinizy1** [comment]
Hi,
If i create and join from this URL (server where BBB is hosted) 
http://34.216.121.9/demo/create.jsp
I can create and join.
But when i create a meeting from my WordPress site and click on join ( while i am logged in as admin) i can join but i don't know how to make a join or invite button to send it to my attendees.
my WordPress site is hosted on different server.
thanks

**Comment by ffdixon** [comment]
When configuring with wordpress, are you entering the URL as

~~~
http://34.216.121.9/bigbluebutton/
~~~

Can you login to your WordPress server via SSH and try the following command `wget -qO- http://34.216.121.9/bigbluebutton/api && echo`.  You should see the following output

~~~
$ wget -qO- http://34.216.121.9/bigbluebutton/api && echo
<response><returncode>SUCCESS</returncode><version>2.0</version></response>
~~~

This will confirm that your WordPress server can reach your BigBlueButton server to do API calls.

**Comment by Coinizy1** [comment]
Hi yes i logged into my Wordpress SSH and tried that command it returned success
![image](https://user-images.githubusercontent.com/31903098/54371319-ff153a80-469a-11e9-81ce-26f1345abae1.png)
Now here is my wordpress config
![image](https://user-images.githubusercontent.com/31903098/54371416-29ff8e80-469b-11e9-977d-358c6d3091f0.png)

The only issue i am facing is i dont know how to invite someone to my meeting :(
thanks

**Comment by Coinizy1** [comment]
Like here is a meeting room i created how will i make a link to invite people to join me?
![image](https://user-images.githubusercontent.com/31903098/54371487-47ccf380-469b-11e9-893c-113185f2fdcb.png)

**Comment by Coinizy1** [comment]
i also wanna know how can i fix the layout for a single seminar for attendees like i want meeeting layout only one webinar that i will host is that possible to fix it for attendess?
Thanks

**Comment by Coinizy1** [comment]
Actually i have ongoing meething where i am live but i cant see any room on the wordpress widget?
Thanks
![image](https://user-images.githubusercontent.com/31903098/54414337-9f5e7400-471a-11e9-8a32-6db1af34e896.png)

![image](https://user-images.githubusercontent.com/31903098/54414353-aab19f80-471a-11e9-8d3f-5f61c1b92d97.png)
