### ISSUE TITLE
certificate has expired with nodejs

### ISSUE THREAD

**Issue by yazilimevde** [bigbluebutton/bbb-install#432]
**i have a bigbluebutton meeting url. I access via postman and browser without any problem and I get the success code. But when I send https get request to the url in my nodejs project, I get certificate has expired error. What can be the problem?**

```
let createApiUrl = `https://bbb.example.com/bigbluebutton/api/create?name=${meetingName}&logoutURL=${logoutUri}&record=true&meetingID=${meetingId}&attendeePW=${attendeePW}&moderatorPW=${moderatorPW}&checksum=${checkSum}`;
response = await new Promise((resolve, reject) => {
  return HTTP.call("GET", `${createApiUrl}`, {}, (error, response) => {
    if (error) {
      reject(error);
    } else {
      resolve(response);
    }
  });
});
```
Error message =>

**Error: certificate has expired
at TLSWrap.ssl.onhandshakedone code: 'CERT_HAS_EXPIRED' }**

**Comment by GhaziTriki** [comment]
Are you using BBB 2.2.x with let's encrypt?
If yes check this : https://groups.google.com/g/bigbluebutton-setup/c/U3Xj_hQSe5s

**Comment by vlasov01** [comment]
@GhaziTriki Thank you! The solution from the link you provided is working for me. Here are the commands:
```
sudo apt-get remove certbot
sudo apt-get install snapd
sudo snap install --classic certbot
sudo certbot renew --force-renewal --cert-name <your.domain.com> --preferred-chain "ISRG Root X1"
```

**Comment by carlosr279** [comment]
@GhaziTriki Worked for me as well. Thanks!

**Comment by yazilimevde** [comment]
@GhaziTriki @vlasov01 @carlosr279  Worked for me as well. Thank you so much everyone!

**Comment by iparaskev78** [comment]
Worked for me too! The problem appeared yesterday evening the same time to our 2 installations. The one is BigBlueButton Server 2.2.22 (2088)  and the other is BigBlueButton Server 2.2.35 (2390) both  16.04.7 LTS (Xenial Xerus). My question is if now the auto - renewal will still work?

**Comment by diatodan** [comment]
Worked for me too, thanks !
For info, I also had to update the kernel : https://dausruddin.com/ubuntu-system-does-not-fully-support-snapd-cannot-mount-squashfs-image-using-squashfs/

**Comment by emadbagheri96** [comment]
> 
> 
> Are you using BBB 2.2.x with let's encrypt? If yes check this : https://groups.google.com/g/bigbluebutton-setup/c/U3Xj_hQSe5s

thanks alot! it works.
just there is a need to restart nginx after that too:
`sudo /etc/init.d/nginx restart  `

**Comment by dr-jkl** [comment]
I found a solution too, talking to rg305 on the Let's Encrypt Community (thanks!) and I think it is worth to share: on the server
- run "dpkg-reconfigure ca-certificates" and uncheck the old C.A. "mozilla/DST_Root_CA_X3.crt"
- edit "/etc/letsencrypt/live/bbb.example.com/fullchain.pem" with nano or similar editor and delete the last certificate
-----BEGIN CERTIFICATE-----
BLAHBLAHBLAH
-----END CERTIFICATE-----
- restart nginx with "sudo /etc/init.d/nginx restart"
I hope this will help.

**Comment by nasilaj** [comment]
I do not understand your office and how it operates.
I failed to install BBB and your many messages do not help me

i m disappointed
