### ISSUE TITLE
Can't delete recording with bbb v. 2.4

### ISSUE THREAD

**Issue by schlause** [bigbluebutton/bbb-install#436]
Currently testing the new version 2.4 rc1. Noticed today I could not delete recordings on greenlight (the popup shows but the recording will not be deleted) . Thanks though for the amazing work guys

**Comment by kepstin** [comment]
This was probably either a BigBlueButton issue or Greenlight issue, not related to the bbb-install script. If you're still able to reproduce the problem, I'd suggest using the community support resources: https://bigbluebutton.org/community-support/ to get help troubleshooting the issue, and reporting a bug on the appropriate component if you continue to have issues.
