### ISSUE TITLE
Hi, i have domain + ssl from namecheap can i use a subdomain?

### ISSUE THREAD

**Issue by Coinizy1** [bigbluebutton/bbb-install#44]
Hi, I am in some thinking. i have a domain name bought from namecheap can i use a subdomain for FQDN for bbb server? how will i do that?
Do i need to provide something while installing or do something after installing.
I can put an A record for the subdomain what else to do?
thanks

**Comment by Coinizy1** [comment]
actually i wanna use it with SSL so my subdomain and SSL (no lets encrypt)
how to do it?
thankss

**Comment by ffdixon** [comment]
We have the step-by-step instructions here http://docs.bigbluebutton.org/2.2/install.html, which includes links on how to configure BigBlueButton with a SSL certificate.

**Comment by Coinizy1** [comment]
ok after routing my domain to the ip then i can get a free certificate for my subdomain right? and then i dont have to use email (which you put white installing from script) right?
Thank you so much for helping everyone for almost a decade now.
thanks

**Comment by Coinizy1** [comment]
i ran this command
wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v xenial-220-beta -s sub.domain.com -t -g
but it says taht i still need lets encrypt email can i put any email for now?
Thanks

**Comment by ffdixon** [comment]
>but it says taht i still need lets encrypt email can i put any email for now?

Yes, you need to provide the `-e <email>` option as Let's Encrypt requires an e-mail to issue an SSL certificate.  See

  https://github.com/bigbluebutton/bbb-install#install-with-ssl
