### ISSUE TITLE
installation script: LETS_ENCRYPT_ONLY set but not used 

### ISSUE THREAD

**Issue by danielwujecki** [bigbluebutton/bbb-install#441]
I made an image for virtual machines to create multiple BBB nodes. To have a valid certificate I wanted to recreate one with the corresponding domain name using the -l option of the installation script (only install certificate, but not BBB itself). Then the script just returns the general usage info, because VERSION was not set by -v. It seems as LETS_ENCRYPT_ONLY isn't further used in the installation script after it is set by -l in the big while loop a the beginning of the main function.

**Comment by danielgolf** [comment]
Thanks again for your help! I guess I'll use a certbot + bbb-conf combination.
