### ISSUE TITLE
Can i change layout for all three? Admin, Moderator and Attendee?

### ISSUE THREAD

**Issue by Coinizy1** [bigbluebutton/bbb-install#45]
Hi, I want to change the default of all three described in the title
Is it possible?
thanks

**Comment by Coinizy1** [comment]
Also a problem i cannot see the webcam of the Safari ios
![image](https://user-images.githubusercontent.com/31903098/54430559-ca11f200-4745-11e9-89e6-b53f02a6c672.png)

**Comment by Coinizy1** [comment]
the webcam is working and showing my front camera on Safari(iOS) but doesnt show the webcam of the attendee on my panel (joined as admin) from wordpress.

**Comment by ffdixon** [comment]
This is more of a BigBlueButton question, not a `bbb-install.sh` question.  In the future, please post such questions to the bigbluebutton-dev mailing list, see https://bigbluebutton.org/support/.

The reason you don't see the webcams is media protocol between Flash (RTMP) and WebRTC (RTP over web sockets) is completely different.  In the HTML5 docs we specify that Flash users won't see webcams from HTML5 users (and vice-versa).

 http://docs.bigbluebutton.org/html/html5-overview.html#features-for-the-first-release

This will soon be moot -- we recommend you setup a BigBlueButton 2.2-beta server and configure it to only use HTML5, see

  http://docs.bigbluebutton.org/2.2/customize.html#make-the-html5-client-default

The HTML5 client implements almost all the features of the Flash client now and, for 2.2-beta, the HTML5 client can be the default client.

**Comment by Coinizy1** [comment]
can you please tell me the command to do that?
i mean full link 
thanks

**Comment by ffdixon** [comment]
Here's the link that describes how make the HTML5 client default the default client in BigBlueButton 2.2-beta.

  http://docs.bigbluebutton.org/html/html5-overview.html#features-for-the-first-release
