### ISSUE TITLE
Install bbb-install.sh script dont see red5

### ISSUE THREAD

**Issue by anhphan886** [bigbluebutton/bbb-install#456]
hi team .
i instaall bbb from bbb-install.sh script but when bbb-conf --check i dont see red5 active.
version i install 2.3.15

**Comment by ffdixon** [comment]
Is this a clean install or did you upgrade from a previous version?  There is no red5 in 2.3.x.

**Comment by GhaziTriki** [comment]
red5 is no more part of BigBlueButton.
