### ISSUE TITLE
Problem running wget and debugging tips

### ISSUE THREAD

**Issue by bijism** [bigbluebutton/bbb-install#457]
Hello dear friends

**We want to "re-install" a BigBlueButton server, but when the following installation command I run does not execute and does not give any error, I debugged it which shows the following information:**

`root@Domain:~# wget --debug -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v bionic-23 -s subdomain.domain.ir -e Domain@gmail.com -w -g

Setting --quiet (quiet) to 1

Setting --quiet (quiet) to 1

Setting --output-document (outputdocument) to -

Setting --output-document (outputdocument) to -

DEBUG output created by Wget 1.19.4 on linux-gnu.

Reading HSTS entries from /root/.wget-hsts

URI encoding = ‘UTF-8’

Caching ubuntu.bigbluebutton.org => 89.X.X.X

Created socket 5.

Releasing 0x00005612dcf26e60 (new refcount 1).

Initiating SSL handshake.

Handshake successful; connected socket 5 to SSL handle 0x00005612dcf270a0

certificate:

  subject: CN=ubuntu.bigbluebutton.org

  issuer:  CN=R3,O=Let's Encrypt,C=US

Closed 5/SSL 0x00005612dcf270a0

root@Domain:~#

`

**Now I executed the same command in the server that has no problem and received the following output**

`root@my:~# wget --debug -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v bionic-23 -s server2.domain.ir -

e info@domain.com -w

Setting --quiet (quiet) to 1

Setting --quiet (quiet) to 1

Setting --output-document (outputdocument) to -

Setting --output-document (outputdocument) to -

DEBUG output created by Wget 1.19.4 on linux-gnu.

Reading HSTS entries from /root/.wget-hsts

URI encoding = ‘UTF-8’

Caching ubuntu.bigbluebutton.org => 167.X.X.X

Created socket 5.

Releasing 0x0000564dc7f63c30 (new refcount 1).

Initiating SSL handshake.

Handshake successful; connected socket 5 to SSL handle 0x0000564dc7f64630

certificate:

  subject: CN=ubuntu.bigbluebutton.org

  issuer:  CN=R3,O=Let's Encrypt,C=US

X509 certificate successfully verified and matches host ubuntu.bigbluebutton.org

---request begin---

GET /bbb-install.sh HTTP/1.1

User-Agent: Wget/1.19.4 (linux-gnu)

Accept: */*

Accept-Encoding: identity

Host: ubuntu.bigbluebutton.org

Connection: Keep-Alive

---request end---

---response begin---

HTTP/1.1 200 OK

Server: nginx/1.14.0 (Ubuntu)

Date: Fri, 03 Dec 2021 18:15:47 GMT

Content-Type: application/octet-stream

Content-Length: 39473

Last-Modified: Thu, 30 Sep 2021 11:46:45 GMT

Connection: keep-alive

ETag: "6155a3a5-9a31"

Accept-Ranges: bytes

---response end---
`

**Comment by michi-80337** [comment]
The failing server has a problem with its certificate chain and can't verify the certificate from ubuntu.bigbluebutton.org. Maybe it has old root certificates. You will find further information on the Let's Encrypt homepage and in the openssl documentation.
