### ISSUE TITLE
INTALLATION OF BBB IN LOCAL

### ISSUE THREAD

**Issue by mta92** [bigbluebutton/bbb-install#458]
How can Install BBB on my local ubuntu 18 server for test?

**Comment by ffdixon** [comment]
If your server is connected to the internet and has an external IP address with a DNS name resolving to that IP address, then you can use `bbb-install.sh` to setup the server.  

We don't support offline install yet with `bbb-install.sh`.

**Comment by mta92** [comment]
I'm just connected on internet and  installing online. This is my problems
on the attachment. Thanks

**Comment by GhaziTriki** [comment]
If you have certificate and you can use the `-d` option then install the certificate manually, it works.
