### ISSUE TITLE
Requirements of BBB

### ISSUE THREAD

**Issue by mta92** [bigbluebutton/bbb-install#465]
What are the requirements (in terms of CPU, RAM, storage, bandwidth) of BBB according to the number of users connected simultaneously, number of meetings, the quality of video, recording enabled/disabled?

**Comment by ffdixon** [comment]
See https://docs.bigbluebutton.org/support/faq.html#how-many-simultaneous-users-can-bigbluebutton-support.  

In the future, please ask such questions in bigbluebutton-setup mailing list and, if we discover an problem with bbb-install, we'll open an issue here to track it.
