### ISSUE TITLE
No way to report bugs when executing documentation

### ISSUE THREAD

**Issue by archenemies** [bigbluebutton/bbb-install#466]
When executing your README a week ago, I encountered erroneous behavior (#464). I know that writing and debugging documentation is the most expensive task faced by most software projects, because documentation runs on human processors which are very valuable. I reported the error I encountered to the project team, so that the programmer of the documentation could be aware of its behavior when executed by humans. However, after several weeks my report has not been acknowledged. In response to my error message, I was both ignored and fed more documentation. The experience was not gratifying and I'm wondering how you plan to debug your documentation in the future, if you antagonize your users by preventing them from reporting any issues they encounter when running it. Is this software really related to education?

**Comment by ffdixon** [comment]
Don't install BigBlueButton on servers that have Apache2 (see my [comment](https://github.com/bigbluebutton/bbb-install/issues/464#issuecomment-1003716105)).

That check in `bbb-install.sh` to check for Apache2 is to specifically prevent administrators from encountering subtle conflicts with another web server running on their system.   Such conflicts are hard to debug, and we want to make sure admins are aware of the conflict and stop the installation from continuing.

**Comment by archenemies** [comment]
Yes, as I said you ignore the original issue and just feed me more documentation. The issue is simple, it is that your README fails to communicate the vital information that your project installs a web server and thus conflicts with other web servers. But you don't even acknowledge that you understand what difficulty I'm encountering, which makes it difficult to communicate about it with you. Your attitude is like that of a C programmer who, upon encountering a segmentation fault when running a program in the debugger, fixes an offending variable *in the debugger*, and then ships the buggy code without modification.

I understand, and agree with, your claim that linked document has the correct information - "buried in the fine print" I would say.

But just as the debugger is not the place to fix your variables, the Github issue tracker is not the place to document your code. The documentation should be part of the Git repo.

When someone comes to you having misunderstood the documentation, this is an error that must be fixed in the documentation rather than in the issue tracker.

I hope this is helpful.
