### ISSUE TITLE
fresh install of BBB 2.4 on Ubuntu 18.04 failing

### ISSUE THREAD

**Issue by falconict** [bigbluebutton/bbb-install#469]
I have a development-sized VPS (4vCPU/8GB) and a freshly installed Ubuntu 18.04.  After logging in the first time as root, I ran the script 

"wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v bionic-240 -s xxx.xxx.xxx -e yyy@yyy.yyy  -a -w".

Things start going wrong when the script complains about being unable to contact Redis on port 6379, and then reporting redis-server.service being disabled, and finally dpkg reporting that dependency problems or errors are preventing the configuration of bbb-record-core, bbb-web, bbb-playback-presentation, bbb-html5, bbb-libreoffice-docker, bbb-playback, bbb-config and bigbluebutton.

Running bbb-conf results in the message:
# BigBlueButton does not appear to be installed.  Could not
# locate: /etc/bigbluebutton/bigbluebutton-release

Also
dpkg -l | grep bbb-html5
iU  bbb-html5                              1:2.4.0-2478                                    amd64        The HTML5 components for BigBlueButton

What's interesting is that I can run redis-server manually, and the listening port is visibile using netstat -tulpn.

Previously I had done almost exactly the same steps with a freshly installed Ubuntu 18.04, with the script removing the '-w' switch to disable configuring ufw.  The same result had been achieved - see installation log.

What could be wrong?  I had installed BBB 2.2 on Ubuntu 16.04 without a hitch more than a year ago.

[20220117 installation log.2.txt](https://github.com/bigbluebutton/bbb-install/files/7894224/20220117.installation.log.2.txt)

**Comment by novastream** [comment]
Same problem here on a fresh Ubuntu 18.04 server with all pre-flight checks done. Seems like we are missing something in sources?

**Comment by ffdixon** [comment]
Hi there,

> See "systemctl status redis-server.service" and "journalctl -xe" for details.
> invoke-rc.d: initscript redis-server, action "start" failed.
> ● redis-server.service - Advanced key-value store

Just tried a new installation and it worked.  Nontheless, something is not working with redis.  Can you take a closer look at redis error logs and let us know what you find.

**Comment by novastream** [comment]
The issue is when installing on a server without IPV6. 

After the initial installation with errors, remove :: entry from bind here /etc/redis/redis.conf and run the installation again.

**Comment by ffdixon** [comment]
@novastream Thanks for sharing this!
