### ISSUE TITLE
how to change http port 80 to port  8002

### ISSUE THREAD

**Issue by shqlzx** [bigbluebutton/bbb-install#47]
my port 80 is used,i want to change it to 8002,so i modify this 4 files:
1./usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
2./etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: bbb.nono.tech
                              port: 8002, [::]:8002
3./var/www/bigbluebutton
4./var/lib/tomcat7/webapps/demo/bbb_api_conf 
now it works

**Comment by shqlzx** [comment]
now it works (flash mode),but when i enable mic ,its say "Detected the following WebRTC issue: Error 1002: Could not make a WebSocket connection. Do you want to try Flash instead?"
i have exec bbb-install.sh with -t,but it seems html5 is not install.what can i do?

**Comment by ffdixon** [comment]
We recommend you keep BigBlueButton listening on port 80 and 443.  For more information, see

  http://docs.bigbluebutton.org/support/faq.html#we-recommend-running-bigbluebutton-on-port-80
