### ISSUE TITLE
 issue with corporate certificates

### ISSUE THREAD

**Issue by flashycom** [bigbluebutton/bbb-install#472]
Hey folks, I'm having a serious problem with corporate certificates, I've tried so many options before opening the issue, but none of them worked.

![image_2022-01-24_17-05-43](https://user-images.githubusercontent.com/98357325/150865755-4c932b2f-e33a-41c9-95e8-ce46c83d6acf.png)

I installed BBB using this command:
wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -w -a -v bionic-24 -s bbb.myorg.ru -d -g

I intentionally skipped generating Let's Encrypt certificates as it is not in line with my organization's policy.
I provided the key -d (before I moved the Issuing + RootCA + nginx certificate of my organization to the /etc/ssl and /usr/local/share/ca-certificates/ directories and entered the update-ca-certificates command)

The installation was successful, I am attaching the output of the bbb-conf command:
![image_2022-01-24_17-02-53](https://user-images.githubusercontent.com/98357325/150867541-98ea43c3-cd79-4b4c-b2f2-2711d886ff11.png)

![image_2022-01-24_17-03-25](https://user-images.githubusercontent.com/98357325/150867566-7d752038-b1c7-46b8-a6c3-d14280ec0ca0.png)

![image_2022-01-24_17-03-55](https://user-images.githubusercontent.com/98357325/150867583-ceeb4ed7-8c9a-4a32-8adf-2ae64474033e.png)

In my opinion, the biggest mistake is this:
![image_2022-01-24_17-05-59](https://user-images.githubusercontent.com/98357325/150869071-8cc8c55b-9a11-4aab-ac04-947c711ea328.png)

I checked the values ​​from bbb-conf --secret, everything matched

I read a lot of tips on github, unfortunately they didn't help, so I'm asking here a few questions:
1) Do I need special edits in the /etc/hosts file? Do I need to edit the /etc/hosts file inside a Docker container?
2) The local IP address of my virtual machine is 10.66.66.60, my certificate for nginx contains the IP address 10.66.66.60 and the domain name bbb.myorg.ru Is this the correct setting?
3) There is some problem with the docker container, ping from the container to the docker0 interface, local IP and external IP is available. How can I check network connectivity and fix problems related to it?
4) I used my organization's certificates, what configuration files do I need to edit in order for everything to work perfectly?As far as I understand, this is the reason why my setup is not working.

Thank you very much for participating and please forgive me for my bad English.
Please let me know where I could be wrong. I can provide any screenshots or log files.

**Comment by michi-80337** [comment]
It looks to me as if you are trying to set up a BBB instance, that is available in the local intranet only. Your virtual machine and the containers running on it use the regular resolver on that virtual machine. So, if you are doing a `getent hosts bbb.myorg.ru` there, you should get `10.66.66.60` as answer. Same has to apply for all clients which want to connect to the server.
I would shy away from any container modifications and certificate tricks. Just put the server name into the certificate and ensure, that name resolution works inside your intranet. The only specific things about a private IP address are, that it is not routed in the Internet and that it is not unique in the Internet.

**Comment by flashycom** [comment]
Thanks, @michi-80337 
The problem was solved by using a Let's Encrypt certificate and setting up a corporate firewall (I removed the server location restriction for Let's Encrypt)
