### ISSUE TITLE
I'am facing issue in installing the bigbluebutton on my local machine KIndly help me out

### ISSUE THREAD

**Issue by codercode878** [bigbluebutton/bbb-install#476]
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator webroot, Installer None
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for bbb.danishkada.com
Using the webroot path /var/www/bigbluebutton-default for all unmatched domains.
Waiting for verification...
Cleaning up challenges
Failed authorization procedure. bbb.danishkada.com (http-01): urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for bbb.danishkada.com - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for bbb.danishkada.com - check that a DNS record exists for this domain

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: bbb.danishkada.com
   Type:   None
   Detail: DNS problem: NXDOMAIN looking up A for bbb.danishkada.com -
   check that a DNS record exists for this domain; DNS problem:
   NXDOMAIN looking up AAAA for bbb.danishkada.com - check that a DNS
   record exists for this domain
 - Your account credentials have been saved in your Certbot
   configuration directory at /etc/letsencrypt. You should make a
   secure backup of this folder now. This configuration directory will
   also contain certificates and private keys obtained by Certbot so
   making regular backups of this folder is ideal.
bbb-install: Let's Encrypt SSL request for bbb.danishkada.com did not succeed - exiting
root@dk-Precision-WorkStation-T3500:~#

**Comment by michi-80337** [comment]
Please check against the [install documentation](https://docs.bigbluebutton.org/2.4/install.html#minimum-server-requirements) for install requirements.

It is as the error message says: Let's Encrypt servers tried to verify your control over the host before issuing a certificate for it. As there is no A-Record for your host in the DNS, the servers did not find an IP address to connect to.

In case of further questions, you could take a look into the [bigbluebutton-setup Google group](https://groups.google.com/g/bigbluebutton-setup).

**Comment by codercode878** [comment]
> Please check against the [install documentation](https://docs.bigbluebutton.org/2.4/install.html#minimum-server-requirements) for install requirements.
> 
> It is as the error message says: Let's Encrypt servers tried to verify your control over the host before issuing a certificate for it. As there is no A-Record for your host in the DNS, the servers did not find an IP address to connect to.
> 
> In case of further questions, you could take a look into the [bigbluebutton-setup Google group](https://groups.google.com/g/bigbluebutton-setup).
> 
> (Duplicate of issue #458 )

sir, i have read all the documentation & a lot of tutorials but all in vain

**Comment by ffdixon** [comment]
As Michi pointed out, the hostname you provided doesn't resolve to any IP address (it has not A-record).  You can verify this yourself.

~~~
# ping bbb.danishkada.com
ping: bbb.danishkada.com: Name or service not known
~~~

**Comment by GhaziTriki** [comment]
You need to use an SSL certificate.
