### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by mhadieskandari** [bigbluebutton/bbb-install#48]
I can't install with install.sh . 
with error as below :
Last login: Tue May  7 01:45:56 2019
root@afra-2474-3334:~# wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v xenial-200
Reading package lists... Done
bash: line 394: /etc/apt/sources.list.d/bigbluebutton.list: No such file or directory
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 168, in <module>
    if not sp.add_source_from_shortcut(shortcut, options.enable_source):
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 768, in add_source_from_shortcut
    self.set_modified_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 492, in set_modified_sourceslist
    self.save_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 658, in save_sourceslist
    self.sourceslist.save()
  File "/usr/lib/python3/dist-packages/aptsources/sourceslist.py", line 413, in save
    files[source.file] = open(source.file, "w")
FileNotFoundError: [Errno 2] No such file or directory: '/etc/apt/sources.list.d/jonathonf-ubuntu-ffmpeg-4-xenial.list'
gpg: keyring `/tmp/tmp0b03epbr/secring.gpg' created
gpg: keyring `/tmp/tmp0b03epbr/pubring.gpg' created
gpg: requesting key F06FC659 from hkp server keyserver.ubuntu.com
gpg: /tmp/tmp0b03epbr/trustdb.gpg: trustdb created
gpg: key F06FC659: public key "Launchpad PPA for J Fernyhough" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
OK
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 168, in <module>
    if not sp.add_source_from_shortcut(shortcut, options.enable_source):
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 768, in add_source_from_shortcut
    self.set_modified_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 492, in set_modified_sourceslist
    self.save_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 658, in save_sourceslist
    self.sourceslist.save()
  File "/usr/lib/python3/dist-packages/aptsources/sourceslist.py", line 413, in save
    files[source.file] = open(source.file, "w")
FileNotFoundError: [Errno 2] No such file or directory: '/etc/apt/sources.list.d/rmescandon-ubuntu-yq-xenial.list'
gpg: keyring `/tmp/tmpajv6vmw6/secring.gpg' created
gpg: keyring `/tmp/tmpajv6vmw6/pubring.gpg' created
gpg: requesting key CC86BB64 from hkp server keyserver.ubuntu.com
gpg: /tmp/tmpajv6vmw6/trustdb.gpg: trustdb created
gpg: key CC86BB64: public key "Launchpad PPA for Roberto Mier Escandón " imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
OK
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
update-notifier-common is already the newest version (3.168.10).
grub-pc is already the newest version (2.02~beta2-36ubuntu3.22).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
Calculating upgrade...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
bbb-install: Unable to locate package: bigbluebutton

**Comment by mhadieskandari** [comment]
Hi @ffdixon  can you guide me what do i do with this error??

**Comment by ffdixon** [comment]
Hi,

> bash: line 394: /etc/apt/sources.list.d/bigbluebutton.list: No such file or directory

Can you try installing xenial-220-beta instead

~~~
wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v xenial-220-beta
~~~

and let us know if that gets you further.

**Comment by mhadieskandari** [comment]
i do what you said but yet i have some error as bellow :



root@afra-2474-3334:/etc/apt# wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v xenial-220-beta
0% [Working]
Hit:1 http://security.ubuntu.com/ubuntu xenial-security InRelease
Hit:2 http://cz.archive.ubuntu.com/ubuntu xenial InRelease          
Hit:3 http://ppa.launchpad.net/jonathonf/ffmpeg-4/ubuntu xenial InRelease
Hit:4 http://us.archive.ubuntu.com/ubuntu xenial InRelease          
Hit:5 http://us.archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:6 http://us.archive.ubuntu.com/ubuntu xenial-backports InRelease
Reading package lists... Done                     
gpg: keyring `/tmp/tmpouxbbxd0/secring.gpg' created
gpg: keyring `/tmp/tmpouxbbxd0/pubring.gpg' created
gpg: requesting key CC86BB64 from hkp server keyserver.ubuntu.com
gpg: /tmp/tmpouxbbxd0/trustdb.gpg: trustdb created
gpg: key CC86BB64: public key "Launchpad PPA for Roberto Mier Escandón " imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
OK
Hit:1 http://security.ubuntu.com/ubuntu xenial-security InRelease
Hit:2 http://ppa.launchpad.net/jonathonf/ffmpeg-4/ubuntu xenial InRelease                           
Hit:3 http://cz.archive.ubuntu.com/ubuntu xenial InRelease                                               
Hit:4 http://us.archive.ubuntu.com/ubuntu xenial InRelease                                               
Get:5 http://ppa.launchpad.net/rmescandon/yq/ubuntu xenial InRelease [18.0 kB]
Hit:6 http://us.archive.ubuntu.com/ubuntu xenial-updates InRelease                   
Hit:7 http://us.archive.ubuntu.com/ubuntu xenial-backports InRelease
Get:8 http://ppa.launchpad.net/rmescandon/yq/ubuntu xenial/main amd64 Packages [456 B]
Get:9 http://ppa.launchpad.net/rmescandon/yq/ubuntu xenial/main i386 Packages [456 B]               
Get:10 http://ppa.launchpad.net/rmescandon/yq/ubuntu xenial/main Translation-en [260 B]
Ign:11 https://ubuntu.bigbluebutton.org/xenial-220-beta bigbluebutton-xenial InRelease                   
Ign:12 https://ubuntu.bigbluebutton.org/xenial-220-beta bigbluebutton-xenial Release
Ign:13 https://ubuntu.bigbluebutton.org/xenial-220-beta bigbluebutton-xenial/main amd64 Packages
Ign:14 https://ubuntu.bigbluebutton.org/xenial-220-beta bigbluebutton-xenial/main i386 Packages
Ign:15 https://ubuntu.bigbluebutton.org/xenial-220-beta bigbluebutton-xenial/main all Packages
Ign:16 https://ubuntu.bigbluebutton.org/xenial-220-beta bigbluebutton-xenial/main Translation-en_US
Ign:17 https://ubuntu.bigbluebutton.org/xenial-220-beta bigbluebutton-xenial/main Translation-en
Ign:13 https://ubuntu.bigbluebutton.org/xenial-220-beta bigbluebutton-xenial/main amd64 Packages
Ign:14 https://ubuntu.bigbluebutton.org/xenial-220-beta bigbluebutton-xenial/main i386 Packages
Ign:15 https://ubuntu.bigbluebutton.org/xenial-220-beta bigbluebutton-xenial/main all Packages
Ign:16 https://ubuntu.bigbluebutton.org/xenial-220-beta bigbluebutton-xenial/main Translation-en_US
Ign:17 https://ubuntu.bigbluebutton.org/xenial-220-beta bigbluebutton-xenial/main Translation-en
Ign:13 https://ubuntu.bigbluebutton.org/xenial-220-beta bigbluebutton-xenial/main amd64 Packages
Ign:14 https://ubuntu.bigbluebutton.org/xenial-220-beta bigbluebutton-xenial/main i386 Packages
Ign:15 https://ubuntu.bigbluebutton.org/xenial-220-beta bigbluebutton-xenial/main all Packages
Ign:16 https://ubuntu.bigbluebutton.org/xenial-220-beta bigbluebutton-xenial/main Translation-en_US
Ign:17 https://ubuntu.bigbluebutton.org/xenial-220-beta bigbluebutton-xenial/main Translation-en
Ign:13 https://ubuntu.bigbluebutton.org/xenial-220-beta bigbluebutton-xenial/main amd64 Packages
Ign:14 https://ubuntu.bigbluebutton.org/xenial-220-beta bigbluebutton-xenial/main i386 Packages
Ign:15 https://ubuntu.bigbluebutton.org/xenial-220-beta bigbluebutton-xenial/main all Packages
Ign:16 https://ubuntu.bigbluebutton.org/xenial-220-beta bigbluebutton-xenial/main Translation-en_US
Ign:17 https://ubuntu.bigbluebutton.org/xenial-220-beta bigbluebutton-xenial/main Translation-en
Ign:13 https://ubuntu.bigbluebutton.org/xenial-220-beta bigbluebutton-xenial/main amd64 Packages
Ign:14 https://ubuntu.bigbluebutton.org/xenial-220-beta bigbluebutton-xenial/main i386 Packages
Ign:15 https://ubuntu.bigbluebutton.org/xenial-220-beta bigbluebutton-xenial/main all Packages
Ign:16 https://ubuntu.bigbluebutton.org/xenial-220-beta bigbluebutton-xenial/main Translation-en_US
Ign:17 https://ubuntu.bigbluebutton.org/xenial-220-beta bigbluebutton-xenial/main Translation-en
Err:13 https://ubuntu.bigbluebutton.org/xenial-220-beta bigbluebutton-xenial/main amd64 Packages
  gnutls_handshake() failed: The TLS connection was non-properly terminated.
Ign:14 https://ubuntu.bigbluebutton.org/xenial-220-beta bigbluebutton-xenial/main i386 Packages
Ign:15 https://ubuntu.bigbluebutton.org/xenial-220-beta bigbluebutton-xenial/main all Packages
Ign:16 https://ubuntu.bigbluebutton.org/xenial-220-beta bigbluebutton-xenial/main Translation-en_US
Ign:17 https://ubuntu.bigbluebutton.org/xenial-220-beta bigbluebutton-xenial/main Translation-en
Fetched 19.2 kB in 32min 13s (9 B/s)
Reading package lists... Done
W: The repository 'https://ubuntu.bigbluebutton.org/xenial-220-beta bigbluebutton-xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch https://ubuntu.bigbluebutton.org/xenial-220-beta/dists/bigbluebutton-xenial/main/binary-amd64/Packages  gnutls_handshake() failed: The TLS connection was non-properly terminated.
E: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
grub-pc is already the newest version (2.02~beta2-36ubuntu3.22).
update-notifier-common is already the newest version (3.168.10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
Calculating upgrade...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
bbb-install: Unable to locate package: bigbluebutton
root@afra-2474-3334:

**Comment by ffdixon** [comment]
Just touching base to see if you were able to resolve this issue with the help from the post in the previous comment?

**Comment by songmink** [comment]
Try to use your default user that you made when you installed Ubuntu with 'sudo bash ...' instead of 'root'.
`wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | sudo bash -s -- -v xenial-220-beta -s bbb.example.com -e info@example.com -g`

If it works fine, your root gpg was not set. Simply, use 'sudo'.
