### ISSUE TITLE
Child domain forward another folder

### ISSUE THREAD

**Issue by mustifanci** [bigbluebutton/bbb-install#483]
Hi every one. I install bigbluebutton and cyberpanel same server. i have domain like mydomain.xxx. i create child domain like live.mydomain.xxx but i must forward subdomain to /var/www/bigbluebutton-default. But cyberpanel create subfolder in mydomain.xxx. How can i forward childomain to /var/www/bigbluebutton-default folder.

**Comment by michi-80337** [comment]
The short answer is: Cyberpanel can not live on the same server as BigBlueButton.

The long answer is: While it might be possible to tweak the Cyberpanel configuration to do all the reverse proxy and web hosting stuff in a way BigBlueButton needs it, it is at least some remarkable effort to get things up and running. Cyperpanel deactivates a running web server and replaces it by its own homegrown server. There is another thing to consider: BigBlueButton needs some CPU and some network bandwidth to do its job. This will disturb your PHP based web applications and vice versa.

Please feel free to look into [BigBlueButton-Setup Google-Group](https://groups.google.com/g/bigbluebutton-setup) for further setup related questions.
