### ISSUE TITLE
Upgrading to BBB 2.5 from BBB 2.3 fails with bbb-install-2.5.sh

### ISSUE THREAD

**Issue by pielonet** [bigbluebutton/bbb-install#486]
Hi,

bbb-install-2.5.sh tests for the presence of the file `/etc/apt/sources.list.d/nodesource.list`
If it exists it won't be updated : https://github.com/bigbluebutton/bbb-install/blob/432ae1aa8f27f0bc0fb5ff6d2c07ee86c98d0e0d/bbb-install-2.5.sh#L242
Since it already exists in BBB 2.3 with a reference to node 12.x, installs fails since Node 16x can not be installed.

Kind regards,
Thierry

**Comment by ffdixon** [comment]
Got it -- will add more logic so it will check for the right version of node in `nodesource.list`

**Comment by antobinary** [comment]
We no longer support the "upgrade" to 2.5 since we have upgraded to a 2 years newer OS version (and lots more). We now use a different version of the install script which is ~20+% different -- bbb-install-2.5.sh
