### ISSUE TITLE
Updating bbb 2.4.1 to 2.4.4. has error with postgres 

### ISSUE THREAD

**Issue by schornhe** [bigbluebutton/bbb-install#488]
I want to update bbb from 2.4.1. to 2.4.4.

my procedure is 

bbb-conf stop
docker-compose down

wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -w -g -v bionic-24 -s xxxx.com -e xyz@domain.com

Status: Downloaded newer image for postgres:13-alpine
Creating greenlight_db_1 ... error

ERROR: for greenlight_db_1  Cannot start service db: driver failed programming external connectivity on endpoint greenlight_db_1 (50b7f7b1f3e16899c311ca667f7a304dd3430c74053939d1ac0a83eb0115087d): Error starting userland proxy: listen tcp4 127.0.0.1:5432: bind: address already in use

ERROR: for db  Cannot start service db: driver failed programming external connectivity on endpoint greenlight_db_1 (50b7f7b1f3e16899c311ca667f7a304dd3430c74053939d1ac0a83eb0115087d): Error starting userland proxy: listen tcp4 127.0.0.1:5432: bind: address already in use
ERROR: Encountered errors while bringing up the project.

Please advise

**Comment by devZer0** [comment]
this can be closed. further inspection showed it was an installation problem with docker

**Comment by ffdixon** [comment]
Thanks @devZer0
