### ISSUE TITLE
Regarding Voip Service in BBB

### ISSUE THREAD

**Issue by dnagraj** [bigbluebutton/bbb-install#49]
Hi Fred,
Can you please share documentation regarding Voip integration in BBB. And I am having doubt like, i installed BBB through script provided, installation was successfull.
Question:
Do i need to install freeswitch manually instead of script provided, or is it enough to leave the configuration as it is and acquire voip from service providers? after getting phone number, what steps do i need to follow, for successful integration of Voip in BBB.

Thanks in advance

**Comment by ffdixon** [comment]
Check out the docs at

  http://docs.bigbluebutton.org/2.2/customize.html#add-a-phone-number-to-the-conference-bridge

This should guide you through the steps of adding a dial-in number to your BigBlueButton (FreeSWITCH) server.

**Comment by dnagraj** [comment]
Do i need to install freeswitch manually instead of script provided, or is it enough to leave the configuration as it is and acquire voip from service providers?

**Comment by ffdixon** [comment]
You can leave the configuration as provided and make your changes to it.  Once you have it working, you'll want to put your changes into a script (such as one that overwrites the existing configuration files with you own).  That way, when you update to a newer version of BigBlueButton (which might include a newer version of FreeSWITCH), you can update and simply run your script to re-apply your custom changes.

**Comment by dnagraj** [comment]
Thank you Fred,
sorry to ask you again, need some clarification...
just placing the voip number in the current configuration file is enough? or is there any other additional configuration do i need to make, provided in the documentation, can you make clarify on this


**_Before you can configure FreeSWITCH to route the call to the right conference, you need to first obtain a phone number from a Internet Telephone Service Providers and configure FreeSWITCH accordingly to receive incoming calls via session initiation protocol (SIP) from that provider.

To route the incoming call to the correct BigBlueButton audio conference, you need to create a dialplan which, for FreeSWITCH, is a set of instructions that it runs when receiving an incoming call. When a user calls the phone number, the dialplan will prompt the user to enter a five digit number associated with the conference._**

**Comment by varma-nexge** [comment]
hi fried

i have a small question, im able to make incoming call to join conference successfully, may i know how to make outgoing call from bbb-conference

**Comment by jaws97** [comment]
https://docs.bigbluebutton.org/2.2/customize.html#add-a-phone-number-to-the-conference-bridge 

I tried the steps from the above link but my call did not reach the BBB server at all, it did not ask for a PIN. I'm using an Indian number which connects to a Singapore number
