### ISSUE TITLE
Error with bbb-libreoffice-docker package

### ISSUE THREAD

**Issue by ammama25** [bigbluebutton/bbb-install#492]
hi.
When installing BBB version 2.3, installation process almost completed BUT at installing one of the package (bbb-libreoffice-docker package), one of the links gets a 403 error and the whole installation process encounters problems!
This is the error:
http://deb.debian.org/debian/pool/main/m/mesa/mesa-vdpau-drivers_20.3.5-1_amd64.deb 403 Forbidden [IP: 199.232.138.132 80]
Other similar links  (repositories) are fine and were downloaded.

when i curl this link("http://deb.debian.org/debian/pool/main/m/mesa/mesa-vdpau-drivers_20.3.5-1_amd64.deb") with http it gives me this error: 
The page you requested has been blocked because it contains a banned word.
and when i try to curl with https its ok and there is no problem.
what can i do to install this package and all bigbluebutton?

**Comment by danimo** [comment]
Go talk to whoever runs your firewall. They have chosen to introspect plain text traffic and ignore encrypted traffic (which is harder). I assume you have hit some sort of profanity filter or deny list in the firewall.

Please ask your firewall administrator to put the IP address your BBB uses on a allow list for hosts that are not subject to those filters (this most certainly will cause further trouble down the line). This is not a BBB issue at all, and nothing that can be remedied short term on BBBs end. Eventually, BBB should not build the container but just download it, but this is not a practical workaround.
