### ISSUE TITLE
404 Not Found nginx

### ISSUE THREAD

**Issue by Kasperait** [bigbluebutton/bbb-install#495]
I install bigbluebutton for the first time, there was a problem with the site when entering it, there is a home page with the name input, but when entering the name, the site crashes with the error 404 Not Found. And I wanted to ask is it mandatory to use an ssl certificate or can I do without it ?
`curl: (7) Failed to connect to bbb.profite.ru port 443: Connection refused
.
`

**Comment by schrd** [comment]
Using an ssl certificate is required because browsers won't let you use their media APIs (access microphone and camera) on non encrypted websites.
