### ISSUE TITLE
There is any swith to make it work on 2GB ram?

### ISSUE THREAD

**Issue by rijotech** [bigbluebutton/bbb-install#5]
I have install BBB more than 3 times on various server but some times is hard to keep up with the steps to get it the way is supposed to work, now i see there is a 4GB memory ram restriction, in my personal opinion and knowledge 2GB has been working fine on my server, now there is any way or switch to make it install on a 2GB server?

**Comment by ffdixon** [comment]
Hi there,

If you want to remove the 4G restriction, you could modify the the number on the fly for the minimum, as in

~~~
wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | sed 's/3940/1/g' | bash -s -- -v xenial-200 
~~~

This way, you can use it without the memory limit :-)
