### ISSUE TITLE
2.5 install not allowing media

### ISSUE THREAD

**Issue by markginter31** [bigbluebutton/bbb-install#501]
2.4 fresh install will setup fine and work right away.  Doing an identically configured install (with the script) of 2.5 will allow audio and media on the local network but only audio works with a device connected over the Internet (no webcams/media). It looks to be a stun/turn server issue so I made sure the settings from the working 2.4/18.04 were the same in the 2.5/20.04 setup.  Identical settings don't allow for webcams/media use. Only audio. At a loss of where to look to try and fix it.

**Comment by ffdixon** [comment]
>  an identically configured install (with the script) of 2.5 will allow

Are you able to try https://test25.bigbluebutton.org/ and see webcams/media work?

**Comment by markginter31** [comment]
In /usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml  there were two options for "announcedIP" both were set to my local network (I'm behind NAT) so I changed them to my public facing IP -- now it works.  So it looks like (for me) the 2.5 install did fine except for setting those two announcedIP settings.  I'm now set up and testing :)

**Comment by markginter31** [comment]
Fix seems to be holding up. Closing.
