### ISSUE TITLE
File permission bbb-webrtc-sfu/production.yml

### ISSUE THREAD

**Issue by SamuelWei** [bigbluebutton/bbb-install#507]
I installed a fresh bbb v2.5 version but bbb-webrtc-sfu was failing.

**Install command**
```
sudo su
wget -qO- https://ubuntu.bigbluebutton.org/bbb-install-2.5.sh | bash -s -- -v focal-250 -d -w -s mydomain.tld
```

Error message with: `journalctl -u bbb-webrtc-sfu`

`Error: Config file /etc/bigbluebutton/bbb-webrtc-sfu/production.yml cannot be read. Error code is: EACCES. Error message is: EACCES: permission denied ....`

I checked the file permission of the bbb-webrtc-sfu folder. The server bbb-webrtc-sfu is run by the bigbluebutton user, but the file was only readable by root. 
```
/etc/bigbluebutton/bbb-webrtc-sfu# ls -la
total 12
drwxr-xr-x 2 root root 4096 Apr  6 14:07 .
drwxr-xr-x 4 root root 4096 Apr  6 08:49 ..
-rw------- 1 root root  170 Apr  6 08:49 production.yml
```

Chaning the permissions fixed the error for me.

Did I do something wrong during install or is this a bug?

**Comment by antobinary** [comment]
This points to https://github.com/bigbluebutton/bbb-install/pull/503/files

`chmod 600 "$BBB_WEBRTC_SFU_OVERRIDE_F"`
with a comment in the same area

> Permissions of the override file should be set. Otherwise permissions depend on the umask

Maybe @schrd or @prlanzarin have more info

**Comment by prlanzarin** [comment]
Hmm. I wonder if maybe we should've set the permissions to 644?

**Comment by schrd** [comment]
The override file contains the Freeswitch ESL password and should be owned by user `bigbluebutton`. The permission `0600` is IMHO correct

**Comment by prlanzarin** [comment]
This isn't fully fixed yet [1][2], so I suggest re-opening.

There must be a different path that bbb-install goes through which does not trigger the permission checks/overrides.
I suspect test25 is also borked due to this issue.

[1] https://github.com/bigbluebutton/bbb-install/issues/511 
[2] https://github.com/bigbluebutton/bigbluebutton/issues/14836

**Comment by SamuelWei** [comment]
> This isn't fully fixed yet [1][2], so I suggest re-opening.
> 
> There must be a different path that bbb-install goes through which does not trigger the permission checks/overrides. I suspect test25 is also borked due to this issue.
> 
> [1] #511 [2] [bigbluebutton/bigbluebutton#14836](https://github.com/bigbluebutton/bigbluebutton/issues/14836)

Just another question: Why is this functionality part of "install_ssl()"? Is this maybe called before the bigbluebutton user is created?

**Comment by prlanzarin** [comment]
> Just another question: Why is this functionality part of "install_ssl()"? Is this maybe called before the bigbluebutton user is created?

a) don't have an answer to that; b) I think the bigbluebutton user exists by that point. 

But it'd indeed be more sensible to move the etc/bbb-webrtc-sfu config generation to a dedicated method and invoke that on its own (ie closer to where "configure_HTML5" is invoked) to make that process less of a mess and maybe guarantee it's always run.

I will look into opening a PR with that, but I'm not intimate with bbb-install nor do I have an easy way to test it.
