### ISSUE TITLE
502 Bad Gateway (nginx) on fresh Ubuntu 18.04

### ISSUE THREAD

**Issue by DigitalTimK** [bigbluebutton/bbb-install#516]
**Describe the bug**
After fresh installation, the demo-page is loaded (https://bbb.myserver.com), but after "Join" on "try big blue button", I get an `502 Bad Gateway (nginx)` on URL `https://bbb.myserver.com/html5client/join?sessionToken=ider9oy1zijgkkkm`

**To Reproduce**

- Fresh installation on Ubuntu 18.04 64-bit (5.4.159-x86_64-jb1) // And same with 4.19.56-x86_64-jb1
- `bbb-conf --check` is free of issues, after `LXD-problem` had been solved with the recommend adaptation of `/lib/systemd/system/freeswitch.service`.

**Expected behavior**
Joining Meeting

**Actual behavior**
502 Bad Gateway

**BBB version:**
BigBlueButton Server 2.4.7 (3065)
                    Kernel version: 5.4.159-x86_64-jb1 // And same with 4.19.56-x86_64-jb1
                      Distribution: Ubuntu 18.04.6 LTS (64-bit)
                            Memory: 16393 MB
                         CPU cores: 8

**bbb-conf --status**
```shell
nginx —————————————————► [✔ - active]
freeswitch ————————————► [✔ - active]
redis-server ——————————► [✔ - active]
bbb-apps-akka —————————► [✔ - active]
bbb-fsesl-akka ————————► [✔ - active]
tomcat8 ———————————————► [✔ - active]
mongod ————————————————► [✔ - active]
bbb-html5 —————————————► [✔ - active]
bbb-webrtc-sfu ————————► [✔ - active]
kurento-media-server ——► [✔ - active]
bbb-html5-backend@1 ———► [✘ - failed]
bbb-html5-backend@2 ———► [✘ - failed]
bbb-html5-frontend@1 ——► [✘ - failed]
bbb-html5-frontend@2 ——► [✘ - failed]
etherpad ——————————————► [✔ - active]
bbb-web ———————————————► [✔ - active]
```

**Comment by ffdixon** [comment]
Did you get any errors during the install? Are you installing within LXD?  I think you may need to adjust the systemd files for bbb-html5-backend and bbb-html5-frontend.

Also, you will need to grant the LXC environment more privileges.  Try this (assuming your container is called `bbb-dev`).

```
lxc launch images:ubuntu/bionic/amd64 bbb-dev -c security.privileged=true -c security.nesting=true
```

Grant privileged mode to the container

```
lxc config set bbb-dev security.nesting true
lxc config set bbb-dev security.privileged true
cat <<EOT | lxc config set bbb-dev raw.lxc -
lxc.cgroup.devices.allow = a
lxc.cap.drop =
EOT
```

Restart the container

```
lxc restart bbb-dev
```

**Comment by DigitalTimK** [comment]
Hi Fred, thanks for supporting!

### 1) Using LXD
Well to be honest, I am not aware of using LXD, but my BBB is hosted on a virtual Server and the [troubleshoot-guide](https://docs.bigbluebutton.org/support/troubleshooting.html#running-within-an-lxd-container) removed the issue mentioned on the `bbb-conf --check`. That's why I mentioned LXD above. But for the rest I just can say I have no idea of LXD.

```txt
# Potential problems described below

#
# Error: Unable to connect to the FreeSWITCH Event Socket Layer on port 8021
#
...
# Warning: The API demos are installed and accessible from:
#
#    https://bbb.myserver.com
#
# and
#
#    https://bbb.myserver.com/demo/demo1.jsp
#
# These API demos allow anyone to access your server without authentication
# to create/manage meetings and recordings. They are for testing purposes only.
# If you are running a production system, remove them by running:
#
#    apt-get purge bbb-demo

# Error: FreeSWITCH failed to start with SETSCHEDULER error, see
#
#   https://docs.bigbluebutton.org/2.2/troubleshooting.html#freeswitch-fails-to-start-with-a-setscheduler-error
#
```

#### Status prior adaptation of `/lib/systemd/system/freeswitch.service` 
```text
root@j350011:~# sudo systemctl status freeswitch.service
● freeswitch.service - freeswitch
   Loaded: loaded (/lib/systemd/system/freeswitch.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2022-05-10 19:20:34 CEST; 14min ago
  Process: 11437 ExecStart=/opt/freeswitch/bin/freeswitch -u freeswitch -g daemon -ncwait $DAEMON_OPTS (code=exited, status=214/SETSCHEDULER)
 Main PID: 2664 (code=exited, status=0/SUCCESS)

May 10 19:20:34 j350011.servers.jiffybox.net systemd[1]: freeswitch.service: Service hold-off time over, scheduling restart.
May 10 19:20:34 j350011.servers.jiffybox.net systemd[1]: freeswitch.service: Scheduled restart job, restart counter is at 5.
May 10 19:20:34 j350011.servers.jiffybox.net systemd[1]: Stopped freeswitch.
May 10 19:20:34 j350011.servers.jiffybox.net systemd[1]: freeswitch.service: Start request repeated too quickly.
May 10 19:20:34 j350011.servers.jiffybox.net systemd[1]: freeswitch.service: Failed with result 'exit-code'.
May 10 19:20:34 j350011.servers.jiffybox.net systemd[1]: Failed to start freeswitch.
```


### 2) Problems during installation
Not sure, I was relying on the pre-checks, the installation script and `bbb-conf --check`. I can repeat the installation and check again. But as there are so many lines during the installation... what do you consider as an error? Any red-line?

### 3) Adjusting bbb-html5-backend & bbb-html5-frontend
Are you referring to [this](https://docs.bigbluebutton.org/support/troubleshooting.html#bbb-html5-fails-to-start-with-a-setscheduler-error) adjustment?

### 4) Kernel-choice
Are both Kernels fine?
- 5.4.159-x86_64-jb1
- 4.19.56-x86_64-jb1

**Comment by ffdixon** [comment]
Can you try installing on a different environment -- like Digital Ocean (just pay a few hours for a droplet).  Let us know if it installs there (we expect it should).  I suspect your virtualization environment is very restrictive and it's tripping up the running of BigBlueButton.

**Comment by DigitalTimK** [comment]
I created a droplet on Digital Ocean and ran the installation script. Everything is issue-free (see below). Also the demo is running smoothly and test-meetings are launched.
**Remark:** The above mentioned (failed) installation is done on the same server-type (and provider) as the current BBB 2.2 installation (running since 1.5 years) .

```text
Starting BigBlueButton

BigBlueButton Server 2.4.7 (3065)
                    Kernel version: 4.15.0-175-generic
                      Distribution: Ubuntu 18.04.6 LTS (64-bit)
                            Memory: 8167 MB
                         CPU cores: 4


[...]



# Potential problems described below
.............
# Warning: The API demos are installed and accessible from:
#
#    https://bbb.myserver.com
#
# and
#
#    https://bbb.myserver.com/demo/demo1.jsp
#
# These API demos allow anyone to access your server without authentication
# to create/manage meetings and recordings. They are for testing purposes only.
# If you are running a production system, remove them by running:
#
#    apt-get purge bbb-demo

No journal files were found.
Failed to add filter for units: No data available
root@bbb-test:~# bbb-conf --status
nginx —————————————————► [✔ - active]
freeswitch ————————————► [✔ - active]
redis-server ——————————► [✔ - active]
bbb-apps-akka —————————► [✔ - active]
bbb-fsesl-akka ————————► [✔ - active]
tomcat8 ———————————————► [✔ - active]
mongod ————————————————► [✔ - active]
bbb-html5 —————————————► [✔ - active]
bbb-webrtc-sfu ————————► [✔ - active]
kurento-media-server ——► [✔ - active]
bbb-html5-backend@1 ———► [✔ - active]
bbb-html5-backend@2 ———► [✔ - active]
bbb-html5-frontend@1 ——► [✔ - active]
bbb-html5-frontend@2 ——► [✔ - active]
etherpad ——————————————► [✔ - active]
bbb-web ———————————————► [✔ - active]
```

**Comment by ffdixon** [comment]
> I created a droplet on Digital Ocean and ran the installation script. Everything is issue-free (see below).

Nice!

>                             Memory: 8167 MB
>                         CPU cores: 4

Two servers -- one works, one does not. You can start comparing errors, log files, and configurations.    Maybe bbb-install.sh made an error in configuring the 1st server.  If you can check each configuration and process, you should be able to spot the differences.

Digital ocean does not run within LXC, so it looks like your first server has a more restrictive VM environment.  It might be possible to overcome, but you'd need to dig into the errors to find the differences. 

Of course, if you could just use Digital Ocean, your life will be easy :-).

**Comment by DigitalTimK** [comment]
Hi Fred, comparing BBB 2.2 with BBB 2.4? Does this makes sense?
I installed BBB 2.2 with a lot of manual commands and followed the instructions on the website (if I remember well there was no `bbb-install.sh`-script). Any hint how to compare those? Where to look?

# BBB 2.2
```text
BigBlueButton Server 2.2.9 (1891)
Kernel version: 5.4.159-x86_64-jb1
Distribution: Ubuntu 16.04.6 LTS (64-bit)
Memory: 8182 MB
CPU cores: 4
[...]

$ bbb-conf --status
nginx —————————————————► [✔ - active]
freeswitch ————————————► [✔ - active]
redis-server ——————————► [✔ - active]
bbb-apps-akka —————————► [✔ - active]
bbb-transcode-akka ————► [✔ - active]
bbb-fsesl-akka ————————► [✔ - active]
red5 ——————————————————► [✔ - active]
mongod ————————————————► [✔ - active]
bbb-html5 —————————————► [✔ - active]
bbb-webrtc-sfu ————————► [✔ - active]
kurento-media-server ——► [✔ - active]
etherpad ——————————————► [✔ - active]
bbb-web ———————————————► [✔ - active]
```

# BBB 2.4
```text
BigBlueButton Server 2.4.7 (3065)
Kernel version: 5.4.159-x86_64-jb1 // And same with 4.19.56-x86_64-jb1
Distribution: Ubuntu 18.04.6 LTS (64-bit)
Memory: 16393 MB
CPU cores: 8
[...]

$ bbb-conf --status
nginx —————————————————► [✔ - active]
freeswitch ————————————► [✔ - active]
redis-server ——————————► [✔ - active]
bbb-apps-akka —————————► [✔ - active]
bbb-fsesl-akka ————————► [✔ - active]
tomcat8 ———————————————► [✔ - active]
mongod ————————————————► [✔ - active]
bbb-html5 —————————————► [✔ - active]
bbb-webrtc-sfu ————————► [✔ - active]
kurento-media-server ——► [✔ - active]
bbb-html5-backend@1 ———► [✘ - failed]
bbb-html5-backend@2 ———► [✘ - failed]
bbb-html5-frontend@1 ——► [✘ - failed]
bbb-html5-frontend@2 ——► [✘ - failed]
etherpad ——————————————► [✔ - active]
bbb-web ———————————————► [✔ - active]
```

**Comment by ffdixon** [comment]
> Hi Fred, comparing BBB 2.2 with BBB 2.4? Does this makes sense?

You are going too far back in versions.  We strongly recommend (due to the bug fixes, security fixes, new features, and built on Ubuntu 18.04) that you stop using 2.2 and upgrade to the latest build of 2.4.

**Comment by DigitalTimK** [comment]
Hey Fred,
you don't read my messages (correctly).
My BBB 2.2 is running since 2 years without problems.
Now I try to install on the same kind of server to install BBB 2.4.
You have ask to compare both... not me!

Cheers!

**Comment by miladamoie** [comment]
> $ bbb-conf --status
> nginx —————————————————► [✔ - active]
> freeswitch ————————————► [✔ - active]
> redis-server ——————————► [✔ - active]
> bbb-apps-akka —————————► [✔ - active]
> bbb-fsesl-akka ————————► [✔ - active]
> tomcat8 ———————————————► [✔ - active]
> mongod ————————————————► [✔ - active]
> bbb-html5 —————————————► [✔ - active]
> bbb-webrtc-sfu ————————► [✔ - active]
> kurento-media-server ——► [✔ - active]
> bbb-html5-backend@1 ———► [✘ - failed]
> bbb-html5-backend@2 ———► [✘ - failed]
> bbb-html5-frontend@1 ——► [✘ - failed]
> bbb-html5-frontend@2 ——► [✘ - failed]
> etherpad ——————————————► [✔ - active]
> bbb-web ———————————————► [✔ - active]

Hello, dear friend, I have the same problem, of course, version 2.5 with Ubuntu 20, did you solve the problem?

**Comment by sergeyshaklein** [comment]
hi. I have the same problem
![Снимок экрана 2023-02-26 в 18 44 55](https://user-images.githubusercontent.com/14212080/221420813-324e75de-ba58-4e16-a135-5b87a6915fee.png)

![Снимок экрана 2023-02-26 в 18 45 37](https://user-images.githubusercontent.com/14212080/221420845-2caa9b5e-5c48-490d-9148-5023e69e90f7.png)


> 

did you solve the problem?

**Comment by ffdixon** [comment]
Can you try installing BigBlueButton 2.6-rc.5 and let us know if you encounter the same issue.  Also, what is the output of 

```
journalctl -u bbb-html5-backend@1
```

**Comment by sergeyshaklein** [comment]
> Can you try installing BigBlueButton 2.6-rc.5 and let us know if you encounter the same issue. Also, what is the output of
> 
> ```
> journalctl -u bbb-html5-backend@1
> ```

hi
![Снимок экрана 2023-02-27 в 09 23 19](https://user-images.githubusercontent.com/14212080/221489702-7dde7868-91fc-4151-8896-5707838d71a4.png)

i tried https://docs.bigbluebutton.org/support/troubleshooting.html#html5-server

>>BigBlueButton 2.6-rc.5  
I'll install it today

**Comment by sergeyshaklein** [comment]
BigBlueButton Server 2.6.0-rc.5 (924)
![Снимок экрана 2023-02-27 в 10 45 43](https://user-images.githubusercontent.com/14212080/221503899-f3a3477e-5f2a-44bc-a5ac-11764b5eb42d.png)
![Снимок экрана 2023-02-27 в 10 45 58](https://user-images.githubusercontent.com/14212080/221503951-e95d4c61-2862-4d31-afc4-30f7f88845bc.png)
![Снимок экрана 2023-02-27 в 10 46 25](https://user-images.githubusercontent.com/14212080/221504033-f42ab096-d957-4758-974d-710268dfd4b6.png)

**Comment by ffdixon** [comment]
The error message is in red -- remove `SETSCHDULER` from the systemd unit file for `bbb-html5-backend@1`, do `systemctl daemon-reload && systemctl restart bigbluebutton.target` and then `sudo bbb-conf --check`.

**Comment by sergeyshaklein** [comment]
> The error message is in red -- remove `SETSCHDULER` from the systemd unit file for `bbb-html5-backend@1`, do `systemctl daemon-reload && systemctl restart bigbluebutton.target` and then `sudo bbb-conf --check`.

thx. 
after I used the recommendations for /usr/lib/systemd/system/bbb-html5-frontend@.service and /usr/lib/systemd/system/bbb-html5-frontend@.service 
![Снимок экрана 2023-02-27 в 18 01 20](https://user-images.githubusercontent.com/14212080/221598924-fe231c08-7a16-420d-8394-785a45c3b408.png)

I got a working bbb

![Снимок экрана 2023-02-27 в 18 02 02](https://user-images.githubusercontent.com/14212080/221599108-e5f43ea4-ee8c-42f3-b048-9443b66f65eb.png)
