### ISSUE TITLE
Install and use coTURN during BBB installation

### ISSUE THREAD

**Issue by debuglevel** [bigbluebutton/bbb-install#525]
The docs suggest the following steps to install BBB with coTURN:

1. Install BBB without using coTURN
2. Install coTURN
3. Reinstall BBB using coTURN

I guess this would also be possible:
1. Install coTURN
2. Install BBB using coTURN

As 2.5 is using Ubuntu 20.04, I assume we don't need another machine to run coTURN. Therefore it would be great to combine these steps into one simple call:
1. Install BBB and coTURN

**Comment by debuglevel** [comment]
Oh, would coTURN and nginx on one server even be possible? I just saw that `turnserver` binds on `https`/`443`. I always thought we needed a separate machine only because BBB needed Ubuntu 18.04 while coTURN needed Ubuntu 20.04 😅

**Comment by Seb35** [comment]
If I’m not mistaken, this was fixed in December 2022 in the following commits: 34f1805a mainly, and 5c71501a, d1e45726, 5e9e5377, 46eefaa9, cc6f5e44, 4e69eaa0, acb1e181, and it is available in version 2.7 under Ubuntu 20.04.

**Comment by debuglevel** [comment]
That's correct!
