### ISSUE TITLE
How can i change the layout of HTML bbb?

### ISSUE THREAD

**Issue by MrMed** [bigbluebutton/bbb-install#53]
I just need to show the webcam image when start and only that. I don't want the whiteboard and others stuffs. I need only the webcam video, How can i do this?

**Comment by ffdixon** [comment]
Can you post this question to our bigbluebutton-dev mailing list.  We'll help you there (this issue tracker is for questions specific to bbb-install.sh).  See: https://bigbluebutton.org/support.
