### ISSUE TITLE
./bbb-install-2.5.sh: line 209: [: missing `]'

### ISSUE THREAD

**Issue by Commifreak** [bigbluebutton/bbb-install#558]
https://github.com/bigbluebutton/bbb-install/blob/72932163b3c4cf8e0c6801d0aadbd288e93d3d23/bbb-install-2.5.sh#L209

In exact this version of the script, I get `./bbb-install-2.5.sh: line 209: [: missing `]'` when executing (it runs further but want to note it).

Ubuntu 20.04.

Regards,

**Comment by antobinary** [comment]
Thank you @Commifreak ! Fixed and updated in the ubuntu bigbluebutton org repo + European mirror
