### ISSUE TITLE
bbb-install for 2.5 messes up greenlight

### ISSUE THREAD

**Issue by lonesomewalker** [bigbluebutton/bbb-install#560]
After installing and for the next BBB version to upgrade by the same command, bbb-install replaces safe host and BBB API URL by the servers ip address.

This causes "a little bit" trouble...

**Comment by antobinary** [comment]
Hi @lonesomewalker 
Could you provide a bit more info: did you pass `-g` to install GL? Did this work correctly for you in a previous 2.5 installation? Could you point to a file + specific config which got misconfigured? Any chance you could copy-paste the exact command you ran? (feel free to mask email / website/...)
