### ISSUE TITLE
problem with installation: Depends: bbb-config but it is not going to be installed

### ISSUE THREAD

**Issue by mehdiMj-ir** [bigbluebutton/bbb-install#570]
Hi, I have problem installing BBB from documentation on freshly installed Ubuntu 20.04 and I thought I should report an issue:

`os-release` and `uname` are:
```bash
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

Linux bbb 5.4.0-128-generic #144-Ubuntu SMP Tue Sep 20 11:00:04 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

I just `wget https://ubuntu.bigbluebutton.org/bbb-install-2.5.sh` and `bash bbb-install-2.5.sh -s -- -v focal-250 -s webinar.novin.dev -e info@novin.dev -a -w -g` with `root` user and at the end had following error:
```bash
The following packages have unmet dependencies:
 bigbluebutton : Depends: bbb-config but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 bbb-html5 : Depends: bbb-pads but it is not going to be installed
             Depends: bbb-webrtc-sfu but it is not going to be installed
             Depends: bbb-web but it is not going to be installed
             Depends: yq (>= 3) but it is not installable
             Depends: yq (< 4) but it is not installable
E: Unable to correct problems, you have held broken packages.
.....
```

**Comment by jamesii-b** [comment]
Still in 2024, I having the same Error. Haven't BBB solved it yet?

**Comment by michi-80337** [comment]
It should work without any problems if you use a fresh Ubuntu installation from original images. Having a system as it is, you can look for held packages and similar problems. This is the yq used by BBB 2.7.4:
```
# apt list yq
Listing... Done
yq/focal,now 3.4.1bbb1 amd64 [installed,automatic]
#
```
Current BBB version are 2.6.16 and 2.7.4 by the way. ;-)

Here are the [Release Notes](https://github.com/bigbluebutton/bigbluebutton/releases).

**Comment by mehdiMj-ir** [comment]
You know, I installed exact script from another server out side of Iran, It worked fine, I think the problem was our filternet!

**Comment by naeemjawaid** [comment]
> Still in 2024, I having the same Error. Haven't BBB solved it yet?

I have the same error. I'm running Ubuntu 20.04 and installing BBB 2.7. How do we resolve this?
