### ISSUE TITLE
libcurl3 or libculr4

### ISSUE THREAD

**Issue by crsthn23** [bigbluebutton/bbb-install#58]
Hi,

I was trying install Bigbluebutton 2.2 and found a conflit in library libcurl:
bbb-freeswich-core require libcurl3
mongodb require libcurl3
bbb-record-core require libcul4
I cant install libcurl3 and libcurl4 in same time.
Could change all components to same version of libcurl ?

**Comment by ffdixon** [comment]
Can you double-check that your server meets the minimum requirements at http://docs.bigbluebutton.org/2.2/install.html#minimum-server-requirements.

**Comment by crsthn23** [comment]
Thanks for reply.
Ok. Sorry, but my version is not the old 16.04.
If Bigbluebutton 2.2 is new, in my opinion, need upgrade Ubuntu too.
I like what a same project use a default library for all.

**Comment by ffdixon** [comment]
We do plan to update the installer to Ubuntu 18.04.  BigBlueButton 2.2-beta will likely be the last version on Ubuntu 16.04.
