### ISSUE TITLE
Ruby 2.5 fails rubygems-update on ubuntu 18.04.6 LTS

### ISSUE THREAD

**Issue by paolovannini** [bigbluebutton/bbb-install#587]
Hi,

during install in my ubuntu 18.04 I have problem with ruby 2.5 during the rubygems-update that requires requires Ruby version >= 2.6.0.

I solve adding this repo:

sudo apt-add-repository ppa:brightbox/ruby-ng

and installing before bbb-install.sh this package:

sudo apt install ruby2.6 ruby2.6-dev

so if you have experince some problem with other installation you can make this changes to your script.

Thanks,
Paolo

**Comment by ffdixon** [comment]
The latest version of BigBlueButton is 2.5, and it requires Ubuntu 20.04.  See

  https://docs.bigbluebutton.org./2.5/install.html#minimum-server-requirements

**Comment by paolovannini** [comment]
Hi,

I had this problem installing versione 2.4 on ubuntu 18.04 here mi packages and server version,

![Screenshot_20230102_094511](https://user-images.githubusercontent.com/113533384/210209773-d90bedb7-1300-4306-b4c6-59decac3fce5.png)

I do the same installation 3 weeks ago without problem,

thanks for your attention,
Paolo

**Comment by ffdixon** [comment]
Looking at this.  It seems there is an error with updating `rubygems-update`

```
# gem install rubygems-update
ERROR:  Error installing rubygems-update:
	The last version of rubygems-update (>= 0) to support your Ruby & RubyGems was 3.3.26. Try installing it with `gem install rubygems-update -v 3.3.26`
	rubygems-update requires Ruby version >= 2.6.0. The current ruby version is 2.5.0.
```
If you try the suggested command

```
# gem install rubygems-update -v 3.3.26
```

and re-run your `bbb-install.sh` command, the installation will finish.

We recommend you install BigBlueButton 2.5, our latest supported release, instead of BigBlueButton 2.4.
