### ISSUE TITLE
Server fails to reboot after installation using bbb-install.sh

### ISSUE THREAD

**Issue by tony-h** [bigbluebutton/bbb-install#59]
I tried installing BBB using `bbb-install.sh` several times, but I could not access the VPS after a reboot, which required reinstalling the OS. The VPS and BBB operated as expected until the server was rebooted. Following a reboot, the VPS would not respond to a ping. Either the IP config was lost, or bootloader didn't initialize correctly.  I think the server final responded on the fourth attempt after I commented out the forced GRUB and firmware update from `bbb-install.sh`. However, I can't tell if that was the issue or if there was something else because I couldn't even access the VPS using the emergency console. Perhaps one of the packages or PPA is modifying the IP config or init sequence?

Any ideas?

In my opinion, forcing a bootloader update using the maintainer's version without user interaction is dangerous because VPS providers can have a specific config. At the very least, the user should have the chance to accept any conflicting changes. I've encountered a VPS from OVH that would not reboot after upgrading grub. It prompted me to view the differences and then choose which config version to keep. Consider performing a version check and then require the user to update the firmware and bootloader as needed before running the installer file again.

- [https://unix.stackexchange.com/questions/113732/a-new-version-of-configuration-file-etc-default-grub-is-available-but-the-vers](https://unix.stackexchange.com/questions/113732/a-new-version-of-configuration-file-etc-default-grub-is-available-but-the-vers)
- [https://www.linode.com/community/questions/17018/grub-updated-its-configuration-and-now-there-are-issues](https://www.linode.com/community/questions/17018/grub-updated-its-configuration-and-now-there-are-issues)

`apt-get -y -o DPkg::options::="--force-confdef" -o DPkg::options::="--force-confold" install grub-pc update-notifier-common`

**Regarding the setup**:
We installing it using command:
`bash bbb-install.sh -g -v xenial-220-beta -s bbb.example.com -c turn.example.com:11111111 -e user@example.com`

Here is the status log following the installation:
```
Starting BigBlueButton


BigBlueButton Server 2.2.0-beta-17 (1256)
                    Kernel version: 4.4.0-131-generic
                      Distribution: Ubuntu 16.04.6 LTS (64-bit)
                            Memory: 16432 MB
                         CPU cores: 4

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://bbb.example.com
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: bbb.example.com
                              port: 80, [::]:80
                              port: 443 ssl
                    bbb-client dir: /var/www/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://bbb.example.com
                              red5: bbb.example.com
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: xx.xx.132.29
                   external_rtp_ip: stun:stun.freeswitch.org
                   external_sip_ip: stun:stun.freeswitch.org

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: :5066
                       wss-binding: xx.xx.132.29:7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: bbb.example.com
                 playback_protocol: https
                            ffmpeg: 4.1.3-0york1~16.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: xx.xx.132.29

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: xx.xx.132.29
                       kurento.url: ws://bbb.example.com:8888/kurento
                    localIpAddress: xx.xx.132.29
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 601
                        kurentoUrl: wss://bbb.example.com/bbb-webrtc-sfu
                  enableListenOnly: true


** Potential problems described below **
# Warning: API URL IPs do not match host:
#
#                                IP from ifconfig: xx.xx.132.29
#  /var/lib/tomcat7/demo/bbb_api_conf.jsp: bbb.example.com

bbb-conf --status
red5 ——————————————————► [✔ - active]
nginx —————————————————► [✔ - active]
freeswitch ————————————► [✔ - active]
redis-server ——————————► [✔ - active]
bbb-apps-akka —————————► [✔ - active]
bbb-transcode-akka ————► [✔ - active]
bbb-fsesl-akka ————————► [✔ - active]
tomcat7 ———————————————► [✔ - active]
mongod ————————————————► [✔ - active]
bbb-html5 —————————————► [✔ - active]
bbb-webrtc-sfu ————————► [✔ - active]
kurento-media-server ——► [✔ - active]
etherpad ——————————————► [✔ - active]
bbb-web ———————————————► [✔ - active]

docker ps
CONTAINER ID        IMAGE                         COMMAND             CREATED             STATUS              PORTS                    NAMES
b1e753f1778f        bigbluebutton/greenlight:v2   "bin/start"         8 minutes ago       Up 8 minutes        127.0.0.1:5000->80/tcp   greenlight-v2
```

**Comment by ffdixon** [comment]
Thanks for sharing this -- we added the grub-pc options early on when we were testing on various servers and found that the update to grub would block the script.

It looks like the options are to (a) not update grub (pin it to the current version when running `bbb-install.sh`, (b) add an option to disable updating gub, (c) update grub and let the maintainer choose, or (d) detect the environment where updating grub is going to lead to such issues and do (a).

Can you share with VPS you are using (linode?) and we can try it ourselves.

**Comment by tony-h** [comment]
@ffdixon, thanks for the response back. I'm using the Linux 16 VPS at https://www.time4vps.com/linux-vps/.

I was going to run the grub and firmware update commands to see which one might cause the issue, but the VPS came to back after rebooting.

- (b) is probably the easiest, but still carries the risk of someone bricking their VPS using the default install options.
- (d) could be a better long-term solution because it keeps `bbb-install.sh` fully automated and changes grub when needed.

Thanks for the work on developing the installer! 🙂

**Comment by trs80** [comment]
Could you also account for different grubs - I'm installing in to azure vms and they have `grub-efi-amd64` and `grub-efi-amd64-signed` which are removed and replaced by `grub-pc` which isn't really what I want. They do still boot OK though.

**Comment by GhaziTriki** [comment]
BigBlueButton 2.2 went out of support. Please open if relevant in newer supported versions.
