### ISSUE TITLE
Upgrading from 2.5 to 2.6-turn

### ISSUE THREAD

**Issue by dashohoxha** [bigbluebutton/bbb-install#590]
I used the script `bbb-install-2.6-turn.sh` to upgrade an existing BBB-2.5, as described here:
https://docs.bigbluebutton.org/2.6/install.html#upgrading-from-bigbluebutton-25

I had some small problems with nginx. I had to remove these (duplicate) files, before nginx could start:

```bash
rm /usr/share/bigbluebutton/nginx/greenlight.nginx
rm /usr/share/bigbluebutton/nginx/greenlight-redirect.nginx
```

Maybe the script can be fixed to avoid these issues. I am not sure if the same issue is present at the script `bbb-install-2.6.sh`.

@ffdixon

**Comment by ffdixon** [comment]
Thanks for the feedback -- the location of the greenlight nginx files did change in the 2.6 release.  Digging deeper ....

**Comment by ffdixon** [comment]
HI @dashohoxha, just noticed you closed this.  Would this still be an issue?

**Comment by dashohoxha** [comment]
For me it is not an issue, I have already completed the migration.  
It might be an issue for people who try to migrate (if some have not done so yet).  
You can open it again if you wish.
