### ISSUE TITLE
Any way to remove the 4GB limitation?

### ISSUE THREAD

**Issue by rijotech** [bigbluebutton/bbb-install#6]
There is a way  to remove the 4GB limitation? it does work fine on a server with xeon 2 cores, ssd and 2GB.

**Comment by ffdixon** [comment]
Yes, if you modify the command to run bbb-install.sh to

~~~
wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | sed 's/3940/1/g' | bash -s -- -v xenial-200 
~~~

Then it will invalidate the memory check.
