### ISSUE TITLE
bigbluebutton building bbb-libreoffice docker image stuck in step 4.

### ISSUE THREAD

**Issue by YouAreALegend** [bigbluebutton/bbb-install#624]
Server Configuration:
Ubuntu 20.04 64-bit
Latest version of docker installed
16 GB of memory with swap enabled
8 CPU cores, with high single-thread performance
100 GB of free disk space

I've tried reinstalling it several times and it's stuck in this step.
I am located in China. Is this due to network issues?
![微信截图_20230330092330](https://user-images.githubusercontent.com/28858204/228703932-9c979679-9c89-4242-87c2-5f61b1e5a85f.png)

**Comment by ffdixon** [comment]
The docker container is running apline and `apk` is the alpine package manager.  You can open a docker container at the last step of its build (see https://www.joyfulbikeshedding.com/blog/2019-08-27-debugging-docker-builds.html) and try running the command interactively.

Still, it's a good bet that the access to the remote server is blocked.  If you can get access to a server that isn't blocked, install BigBlueButton, and then copy the resulting docker image, that should get you past the step to setup the libreoffice docker image and the installation should continue.

**Comment by arrmmmiin** [comment]
I ran into the same issue, that was why I filed

https://github.com/bigbluebutton/bbb-install/pull/620 to you :)

Maybe you decide what we will adjust in the script ?

Regards :)

**Comment by ffdixon** [comment]
@arrmmmiin Just looking at your comment.  We already merged in #620 for `bbb-install-2.6.sh`, so is there any more action to take?

**Comment by arrmmmiin** [comment]
Hey @ffdixon, thx for the reply :)
Provided that a proxy is used and was set using the -p option, it has to make its way to URLs, i.e. on **line 260** in **bbb-install-2.5.sh**

**Comment by ffdixon** [comment]
We now use https by default (whether or not you use -p).  Does this work?

  https://github.com/bigbluebutton/bbb-install/blob/master/bbb-install-2.5.sh#L260

**Comment by arrmmmiin** [comment]
it depends on the command.
For example, to GIT or WGET the proxy-settings need to be provided seperately.

**Comment by ffdixon** [comment]
Could you possibly send us a pull request with the needed changes to https://github.com/bigbluebutton/bbb-install so we can review (and possibly merge)?

**Comment by support-criegerde** [comment]
We have a fresh Server operating on Ubuntu 20.04.6 LTS x64Bit and tried to install BBB several times.

```
root@graz-v01:/home/crieger# lsb_release -ar

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal

root@graz-v01:/home/crieger# uname -ar
Linux graz-v01 5.4.0-148-generic #165-Ubuntu SMP Tue Apr 18 08:53:12 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
root@graz-v01:/home/crieger#

root@graz-v01:/home/crieger# systemctl show-environment
LANG=en_US.UTF-8
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin

root@graz-v01:/home/crieger# docker --version
Docker version 24.0.0, build 98fdcd7
```

Unfortunately the installation hangs at step 4:
![grafik](https://github.com/bigbluebutton/bbb-install/assets/134060911/ad6a6c93-874a-4893-8017-a6b7f5ce5b50)

We set the language as required and run the following command to install BBB v.2.6:
`wget -qO- https://ubuntu.bigbluebutton.org/bbb-install-2.6.sh | bash -s -- -v focal-260 -s xyz.domain.com -e mail@domain.com -w`

Please let me know if you are interest in e.g. logs or something else - we are able to reproduce the issue if you want.

Looking forward to your assistance.
Carsten

**Comment by support-criegerde** [comment]
Might be fixed with:

`vi /etc/docker/daemon.json`

add
```
{
	  "mtu": 1450
}
```

![grafik](https://github.com/bigbluebutton/bbb-install/assets/134060911/ce55d329-a360-419d-a2f4-d1bc5d1a6109)

**Comment by support-criegerde** [comment]
mkdir /var/log/redis
mkdir /var/lib/redis
chown -R redis:redis /var/lib/redis
chown -R redis:redis /var/log/redis
chmod -R u+rwX,g+rwX,u+rx /var/log/redis
chmod +r /etc/redis/redis.conf
systemctl start redis-server.service

Re-run the bbb-installation-skript and everything works as expected.

**Comment by YouAreALegend** [comment]
Works for me.Thanks~
[https://github.com/bigbluebutton/bbb-install/issues/624#issuecomment-1490044565](url)

**Comment by YouAreALegend** [comment]
Works for me.Thanks~

https://github.com/bigbluebutton/bbb-install/issues/624#issuecomment-1490044565

**Comment by Song0013** [comment]
大哥你是怎么解决的
