### ISSUE TITLE
Unable to join room

### ISSUE THREAD

**Issue by Michal78900** [bigbluebutton/bbb-install#626]
Hello, I have an issue with a fresh install of BigBlueButton 2.6.

I've used this script with these parameters
```
wget -qO- https://ubuntu.bigbluebutton.org/bbb-install-2.6.sh | bash -s -- -v focal-260 -s bbb.mydomain.local -g -d
```

The site itself (Greenlight) works, I can go to my profile, manage settings etc. however I can't join any meeting.
I'm getting "The action can't be completed error".
![image](https://user-images.githubusercontent.com/75911188/230685581-861d4a28-06a5-442c-91eb-9c151a7b28a2.png)

Click the `Start` button sends a JSON POST request with 400 error and no extra error info:
![image](https://user-images.githubusercontent.com/75911188/230685806-2dfb0e12-9866-4c2b-ac26-7f26fee25f3d.png)

`Administrator Panel > Server Rooms` seems to be broken too. The list tries to loads and fails to do so. In ends up with a page error after a while.
![image](https://user-images.githubusercontent.com/75911188/230686089-40ea69eb-4997-439f-95cf-fa579af1c953.png)
![image](https://user-images.githubusercontent.com/75911188/230686105-5e3f0534-8ebf-4be8-9ed1-3301d1300119.png)

Now, the interesting thing is that the BigBlueButton itself seems to be working. I know it because the Mate API, that I can get from `bbb-conf --secret`, allows me to join as a random user.
![image](https://user-images.githubusercontent.com/75911188/230686273-6061fb7d-dbdb-424d-b6f8-7b3ec2425c9f.png)

So the frontend seems to not work. I've checked logs (/var/log) and I haven't found anything useful. I will appreciate any help. Thanks.

**Comment by ffdixon** [comment]
We just tried a fresh install and it worked, but we didn't use the `-d` parameter.  Instead, we let Let's Encrypt generate the certificates.

Check the contents of `/root/greenlight-v3/.env` and ensure the value for `BIGBLUEBUTTON_ENDPOINT` is using https.

**Comment by Michal78900** [comment]
`BIGBLUEBOTTON_ENDPOINT` is indeed using https. I don't want to use Let's Encrypt because he have our own certificate from other party, so I don't see a reason to use both Let's Encrypt and that other party at the same time as we also have other services.

I've put my certificates into `/local/certs` and the site itself works, but as I said earlier I can't join any rooms. For me it is kinda strange that it works to you while the only difference being that we both use different SSL certificate provider.

**Comment by ffdixon** [comment]
Hmm .. something is tripping it up.  Are you able to check the logs in Greenlight to see if there are any error messages

  https://docs.bigbluebutton.org/greenlight/v2/install#troubleshooting-greenlight

**Comment by Michal78900** [comment]
> Docker is always running on a production environment, so the logs will be located in `log/production.log` from the `~/greenlight` directory.

There is no such file, also the link you gave me is for Greenlight v2, while the script installs v3. The v3 page doesn't mention where are logs stored.

**Comment by ffdixon** [comment]
Your right!  I took a quick look myself and didn't see where the log files were store for v3.  Will need to dig deeper -- it should be possible to view the log files and see what error messages are thrown.

**Comment by Michal78900** [comment]
> Will need to dig deeper -- it should be possible to view the log files and see what error messages are thrown.

I can tell you that I already dug deeper, lol. I was monitoring the entire `/var/log` to see if anything is logged but it's not (I mean when clicking the start button, there is literally no interaction noted)

I am just pretty annoyed at this point, I spent over a week trying to make it work and I'd like to know anything that I can try to fix this problem. Right now since it's Easter I don't work on production machine, but I recreated the exact same environment and got the same result.

**Comment by ffdixon** [comment]
> I am just pretty annoyed at this point, I spent over a week trying to make it work and I'd like to know anything that I can try to fix this problem. 

Hi @Michal78900, we all volunteer our time here.  We spent over 8 months of development to rewrite GreenLight, and we've been constantly improving BigBlueButton over the years.

If you are unable to wait, I recommend you reach out to any of the companies that provide commercial support (see https://bigbluebutton.org/commercial-support/).  This way, you get a faster response, they earn revenue, and that revenue helps to improve BigBlueButton for everyone.

**Comment by Michal78900** [comment]
I understand that you spend your free time developing this project. I myself have an open-source project from which I don't get any money so I get it that not everything may work properly in some niche scenarios like my own (probably not many people choose to use their own certificate).
I really appreciate your work, I heard that your project is used by big institutions all around the globe. Didn't want to attack you there in any way.

I've tried installing BBB v2.5 and got a different issue (invalid endpoint and secret, both are set correctly) and trying to install v2.7 results in `bbb-install: Unable to locate packages for focal-270 at ubuntu.bigbluebutton.org.`

So my last option is trying to install v2.6 with Let's Encrypt - the exact same way you did. I hope it will work this time.

Thank you for all of your help, I hope you've spent Easter well.

**Comment by ffdixon** [comment]
Appreciate your response (and that your a fellow open source enthusiast).  I think you'll get there if you leverage Let's Encrypt.  Let us know if that path gets you to success.

**Comment by Michal78900** [comment]
@ffdixon Everything works with Let's Encrypt certificate. Thank you very much.

**Comment by smvelo** [comment]
How did you do  Let's Encrypt certificate? I am getting the same error and I am on greenlight v3 just installed and then interacted with the site but starting a room is not working. Please kindly assist... @ffdixon @Michal78900
