### ISSUE TITLE
Unable to locate packages for focal-270 at ubuntu.bigbluebutton.org

### ISSUE THREAD

**Issue by Lunixfan** [bigbluebutton/bbb-install#627]
I wanted to install the new bbb-install-2.7.sh on my Ubuntu 20.04 machine. Every time I try to install it, I get the error: 'bbb-install: Unable to locate packages for focal-270 at ubuntu.bigbluebutton.org.' What's going on there?

The bbb-install-2.6.sh works perfectly fine, but unfortunately not the 2.7 version, which is disappointing. Please provide prompt assistance as I have been trying to manually install focal-270, but I can't find the correct package.

**Comment by ffdixon** [comment]
Hi Linuxfan,

There is no 2.7 version yet as we're only starting development on it.  It will be a few months before you'll have anything to try out.  We'll announce to bigbluebutton-dev when there is an alpha or beta version to test. Until then, we recommend using 2.6.

**Comment by Lunixfan** [comment]
Alright, then it's a matter of waiting. I thought that since there is a bbb-install-2.7.sh, there might already be a newer version available. Hopefully, the 2.7 version will address the microphone recognition issues on Mac, as some users have reported problems with it. Nevertheless, thank you for the prompt response.

**Comment by ffdixon** [comment]
> Alright, then it's a matter of waiting. I thought that since there is a bbb-install-2.7.sh, there might already be a newer version available. Hopefully, the 2.7 version will address the microphone recognition issues on Mac, as some users have reported problems with it. Nevertheless, thank you for the prompt response.

Can you expand on this -- such as with steps to reproduce.

**Comment by john1726** [comment]
Please note that I have been following the directions on https://github.com/bigbluebutton/bbb-install using this command:

`root@Grieg:/home/rmoore/Install# wget -qO- https://raw.githubusercontent.com/bigbluebutton/bbb-install/v2.7.x-release/bbb-install.sh | bash -s -- -w -v focal-27 -s mydomain.org -e email@example.com`

But it is still giving me this error:

`bbb-install: Unable to locate packages for focal-270 at ubuntu.bigbluebutton.org.`

Is focal-270 available now?  My focal-260 stopped working.

Do you have any suggestions?   TIA.
