### ISSUE TITLE
Greenlight fails to build using -g flag

### ISSUE THREAD

**Issue by mkenny** [bigbluebutton/bbb-install#63]
I'm using an EC2 instance (c5.2xlarge) with 4 cores and 8Gb RAM and I have opened all of the required security groups and the instance is bound to an elastic IP that's picked up on Route 53.  When I run the command:

`wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v xenial-220-beta -s bbb.example.com -e john.doe@example.com -g`

I'm getting the error:

`docker: failed to register layer: Error processing tar file(exit status 1): write /usr/share/locale/mr/LC_MESSAGES/glib20.mo: no space left on device.
See 'docker run --help'.
Unable to find image 'bigbluebutton/greenlight:v2' locally`

I'm also seeing the error :

`ERROR: Top level object in '/root/greenlight/docker-compose.yml' needs to be an object not '<class 'NoneType'>'.`

From a cursory read I'm understanding that this is down to a memory issue with docker

`$ docker -v` 

> Docker version 19.03.1, build 74b1e89e8a

Running the script without the `-g` flag builds BBB perfectly, this is just a Greenlight issue

**Comment by ffdixon** [comment]
The default amount of disk space you get on an EC2 instance is 8G, which isn't enough to install BigBlueButton + GreenLight.  

Recommend setting up a new instance with (at least) 500G of disk space if you are going to do lots of recordings.

  http://docs.bigbluebutton.org/support/faq.html#what-is-the-disk-space-usage-for-storing-1-hour-of-recordings

Alternatively, you could setup about 100G on the root (which should be enough for log files and temporary files) and set up a large EBS storage. You'll need to map `/var/bigbluebutton` to a directory on the external storage.

**Comment by mkenny** [comment]
Thank you Fred, that solved the issue
