### ISSUE TITLE
certbot renew

### ISSUE THREAD

**Issue by dashohoxha** [bigbluebutton/bbb-install#633]
This command is supposed to renew the letsencrypt certificate(s). It is run automatically and periodically in BBB but can also be tried manually. I noticed that it fails in my installation.

I had to fix manually the nginx configuration to make it work. In the file `/etc/nginx/sites-available/bigbluebutton` I modified the first server definition from:

``` nginx
server {
  listen 80;
  listen [::]:80;
  server_name bbb.example.org;

  return 301 https://$server_name$request_uri; #redirect HTTP to HTTPS

}
```

to:

``` nginx
server {
  listen 80;
  listen [::]:80;
  server_name bbb.example.org;

  location ^~ / {
    return 301 https://$server_name$request_uri; #redirect HTTP to HTTPS
  }

  location ^~ /.well-known/acme-challenge/ {
    allow all;
    default_type "text/plain";
    root /var/www/bigbluebutton-default;
  }

  location = /.well-known/acme-challenge/ {
    return 404;
  }
}
```

I am updating from `bbb-install-2.6-turn.sh` to `bbb-install-2.6.sh` and I think that I had the same problem with the previous installation as well.

After running `bbb-install-2.6.sh` again my manual modifications are overwritten.

**Comment by ffdixon** [comment]
Thanks for the (excellent) issue and the recommended fix.  We've just updated `bbb-install-2.6.sh` with your suggestions.

We welcome any other suggestions you have to improving the installer.
