### ISSUE TITLE
Migrating external accounts from greenlight to greenlight-v3

### ISSUE THREAD

**Issue by dashohoxha** [bigbluebutton/bbb-install#634]
I followed the instructions at https://docs.bigbluebutton.org/greenlight/v3/migration/ and everything worked well. However most of the user accounts are based on Google authentication and cannot login anymore on greenlight-v3. There are no instructions on the docs what to do with these accounts: https://docs.bigbluebutton.org/greenlight/v3/migration/#after-the-migration

Is there any way to convert these external accounts to normal accounts, so that they can reset the password and be able to login?

**Comment by ffdixon** [comment]
Can we get you to post this issue to the GreenLight issue tracker and we'll follow-up there, https://github.com/bigbluebutton/greenlight/issues.  Thanks!

**Comment by dashohoxha** [comment]
Moved to https://github.com/bigbluebutton/greenlight/issues/5147
