### ISSUE TITLE
LTI Not Install

### ISSUE THREAD

**Issue by ApuRed** [bigbluebutton/bbb-install#643]
I have installed with the command "wget -qO- https://ubuntu.bigbluebutton.org/bbb-install-2.6.sh | bash -s -- -v focal-260 -s bbb.example.com -e info@example .com -w -g -k -t MY_KEY:MY_SECRET" but the lti server doesn't work, I even used the command to just install LTI without success, am I doing something wrong?

OS: Ubuntu 20.00
RAM: 16Gb
vCPU: 8cores
Disk: 300Gb

I don't generate an error or anything, just that I don't see LTI but the rest of the applications do, and the program works normally.

**Comment by ffdixon** [comment]
Please try running it again -- it should now install the LTI components when you re-run the `bbb-install-2.6.sh` command.

You should now see as part of the install

```
bbb-install: starting BBB LTI framework services...
Creating network "bbb-lti_default" with the default driver
Creating bbb-lti_redis_1    ... done
Creating bbb-lti_postgres_1 ... done
Creating bbb-lti_broker_1   ... done
Creating bbb-lti_rooms_1    ... done
bbb-install: Waiting for the LTI broker to start...
bbb-lti_postgres_1 is up-to-date
bbb-lti_broker_1 is up-to-date
bbb-install: LTI broker is ready!
....
```
