### ISSUE TITLE
Letsencrypt update challenge fails in BBB 2.6 when upgraded from BBB 2.5

### ISSUE THREAD

**Issue by pielonet** [bigbluebutton/bbb-install#649]
Hi,

We recently upgraded our BBB 2.5 server to BBB 2.6 using bbb-install-26.

Letsencrypt renewal failed since `/etc/letsencrypt/renewal/mydomain.example.com.conf`  contains the following webroot map : `/var/www/bigbluebutton-default/`

This directory was the one used by BBB 2.5 whereas it should be `/var/www/bigbluebutton-default/assets` for BBB 2.6.

Changing webroot to `/var/www/bigbluebutton-default/assets`  in `/etc/letsencrypt/renewal/mydomain.example.com.conf` and running certbot renew fixes the issue.

I guess bbb-install-26 should take this into consideration.

Here is the fixed version of our renewal file :

```
# renew_before_expiry = 30 days
version = 0.40.0
archive_dir = /etc/letsencrypt/archive/mydomain.example.com
cert = /etc/letsencrypt/live/mydomain.example.com/cert.pem
privkey = /etc/letsencrypt/live/mydomain.example.com/privkey.pem
chain = /etc/letsencrypt/live/mydomain.example.com/chain.pem
fullchain = /etc/letsencrypt/live/mydomain.example.com/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 06ec78bab46d8e627ac0ce2774c75f6d
rsa_key_size = 4096
renew_hook = systemctl reload nginx
authenticator = webroot
webroot_path = /var/www/bigbluebutton-default/assets,
server = https://acme-v02.api.letsencrypt.org/directory
[[webroot_map]]
mydomain.example.com = /var/www/bigbluebutton-default/assets
```

**Comment by sebastianschlauderer** [comment]
Thanks a lot for posting this, had the same issue and your solution worked fine. Just a small addition, I also had to adjust the last line from /var/www/bigbluebutton-default/ to /var/www/bigbluebutton-default/assets

**Comment by salytwo** [comment]
which command do you used to upgrade to  BBB 2.6, I am going to upgrade too, please advise
