### ISSUE TITLE
Unable to locate packages for xenial-220-beta

### ISSUE THREAD

**Issue by frollog** [bigbluebutton/bbb-install#65]
Hello there!
 Im trying to use bbb-install script, but i have an error: 
"Unable to locate packages for xenial-220-beta"
It looks like server with bbb repo is blocked in my country (Russia) 
https://isitblockedinrussia.com/?host=bigbluebutton.org
Im newbie with Ubuntu so what is possible solution for my problem?
Thanks in advance for your reply

**Comment by frollog** [comment]
Well, ive just set up TOR and all is OK.

**Comment by weltchmerz** [comment]
Приветствую, frollog!
Застряла при установке BBB на той же ошибке, что была у вас. Тор установила, torify не помог. Не могли бы вы написать, какие команды выполняли в ssh?

**Comment by ffdixon** [comment]
Can you try using this repository `packages-eu.bigbluebutton.org` instead of bigbluebutton.org and let us know you can install.

**Comment by motad333** [comment]
> Can you try using this repository `packages-eu.bigbluebutton.org` instead of bigbluebutton.org and let us know you can install.

thank ffdixon
it work for me
