### ISSUE TITLE
Redirect loop with haproxy setup

### ISSUE THREAD

**Issue by dimitrihof** [bigbluebutton/bbb-install#658]
I am getting a redirect loop on certificate renewal with haproxy and letsencrypt.

Happened on multiple machines installed about 3 month ago. I get an error 400 from the webserver, when the /.well-known/... url is tried to access from letsencrypt.

Can anyone else confirm this?

I had no time yet to look at the issue in detail.

**Comment by ffdixon** [comment]
Can you re-run `bbb-install-2.6.sh` with your original parameters.  We fixed an issue related to this last week: https://github.com/bigbluebutton/bbb-install/pull/650.

**Comment by dmtrhfr** [comment]
Thanks fred, already did that. Didn't see the issue. I will close this one then.
