### ISSUE TITLE
error run in VMinstance google cloud

### ISSUE THREAD

**Issue by traithon9x** [bigbluebutton/bbb-install#66]
` wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v xenial-200 -s *******.xyz
-e ********@gmail.com

..
Reading package lists...
Building dependency tree...
Reading state information...
apt-transport-https is already the newest version (1.2.32).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
..
Reading package lists...
Building dependency tree...
Reading state information...
dnsutils is already the newest version (1:9.10.3.dfsg.P4-8ubuntu1.14).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
bash: line 268:  4031 Terminated              nc -l 80 > /dev/null 2>&1
bbb-install: DNS lookup for *****.xyz resolved to 35.1xx.xxx.171 but didn't match local 10.148.0.2.`

**Comment by SolutionsDEV** [comment]
I have the same issue and it does not continue, while on the instructions page it tells under server choices that on Google Cloud VM it detects the IP and continues, but apparently it breaks the automatic installation.

Any ideas to fix this?

Thanks,

**Comment by rizkyekoputra** [comment]
got same issue here, bbb installed on private ip

**Comment by ffdixon** [comment]
Hmmm ... this line should be detecting the GCE external IP address
  
  https://github.com/bigbluebutton/bbb-install/blob/master/bbb-install.sh#L283

can you the above command the prompt and let us know if it is working on your instance.  Also found this

  https://stackoverflow.com/questions/23362887/can-you-get-external-ip-address-from-within-a-google-compute-vm-instance

**Comment by ffdixon** [comment]
I just tested the scrip on a GCE VM and it worked.  Can you try running the following

~~~bash
!/bin/bash
if [ -r /sys/firmware/dmi/tables/smbios_entry_point ] && which dmidecode > /dev/null && dmidecode -s bios-vendor | grep -q Google; then
    # Google Compute Cloud
    external_ip=$(wget -O - -q "http://metadata/computeMetadata/v1/instance/network-interfaces/0/access-configs/0/external-ip" --header 'Metadata-Flavor: Google')
    echo "External IP: $external_ip"
fi
~~~

on you GCE VM and tell me if it correctly prints your public IP address.

**Comment by ffdixon** [comment]
@traithon9x @SolutionsDEV @rizkyekoputra Could you try installing BigBlueButton 2.2-beta on a GCE VM and let me know if it works now.

**Comment by ffdixon** [comment]
You also need to add a firewall rule to allow incoming UDP on ports 16384-32768

![image](https://user-images.githubusercontent.com/290351/65390403-5a9c4100-dd2c-11e9-9f35-7a0d8584e59a.png)

**Comment by mtahle** [comment]
> @traithon9x @SolutionsDEV @rizkyekoputra Could you try installing BigBlueButton 2.2-beta on a GCE VM and let me know if it works now.

Hi,

I'm trying to install BBB on GCE, the installation process has no problem, BBB starts and I can join meeting using the demo API but Audio/Video and screen share not working 

I'm using Mac OS Mojave, I have tested with Safari, FireFox, and Chrome. Also, I have tried to connect using Android Chrome, iOS Safari with the same error everywhere 

GCE instance specs are:  8 vCPU VM with 16 GiB RAM ubuntu 16.04, BBB-2.2-beta
I have done all the configuration of NAT/ Firewall  here http://docs.bigbluebutton.org/2.2/configure-firewall.html

error msg
https://prnt.sc/pcie8b

**Comment by ffdixon** [comment]
@mtahle Would it be possible to give us a closer look at your server (reach out to me at the e-mail in my GitHub profile)?
