### ISSUE TITLE
Error during install --> .curl: (60) SSL certificate problem: certificate has expired

### ISSUE THREAD

**Issue by ankushnayak** [bigbluebutton/bbb-install#666]
When updating my BBB installation from 2.6.0 to 2.6.10 with greenlight using bbb-install.sh I am getting the following error:

```
# Potential problems described below
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
.curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html
```
I've used the following installation command:
```
wget -qO- https://ubuntu.bigbluebutton.org/bbb-install-2.6.sh | bash -s -- -v focal-260 -s <domain-name> -e <admin-email> -w -g -c <turn-server>:<password>
```
Shouldn't bbb-install automatically install/renew any expired SSL certificates? Unable to understand why I am getting this error. Please help.

**Comment by ffdixon** [comment]
I think we fixed this issue earlier with https://github.com/bigbluebutton/bbb-install/pull/648, but it doesn't automatically overwrite the `/etc/nginx/sites-available/bigbluebutton` file (and based on the above, maybe it should).

If you apply the following changes to the file, then try doing a `certbot renew`, let us know if it successfully renews.

**Comment by ankushnayak** [comment]
The paths in `/etc/nginx/sites-available/bigbluebutton` were already updated to include `/assets` but I found that this was missing in the webroot path mentioned in `/etc/letsencrypt/renewal/<domain-name>.conf`. Updated the webroot path there manually to include `/assets` and then performed `certbot renew` and it worked! Thanks @ffdixon for nudging me in the right direction!
