### ISSUE TITLE
BBB 2.6 not available, but BBB 2.7 not usable for production

### ISSUE THREAD

**Issue by lonesomewalker** [bigbluebutton/bbb-install#686]
It would be nice as long as BBB 2.7 is not stable enough for production to have the possibility to install / update 2.6 installations.

This fails due the fact that etherpad now needs nodejs 18 or higher:
```
 bbb-pads : Depends: bbb-etherpad but it is not going to be installed
            Depends: nodejs (>= 18)
```

Thx

**Comment by antobinary** [comment]
Hi, please check the release notes of 2.6.14 https://github.com/bigbluebutton/bigbluebutton/releases/tag/v2.6.14

Upgrade NodeJS to v18 and you're good to go...

https://raw.githubusercontent.com/bigbluebutton/bbb-install/master/bbb-install-2.6.sh also contains an upgrade path which I've tested before releasing 2.6.14 and there were no issues I could spot.

Please specify what is the obstacle for your setup to upgrade to 2.6.14 once NodeJS is v18 on your system? (NodeJS 16 is EOL)
