### ISSUE TITLE
Cannot install bbb 2.7

### ISSUE THREAD

**Issue by muimid** [bigbluebutton/bbb-install#687]
For some reason I cannot get BBB to install onto my server (Ubuntu 20.04 LTS, clean install) using the bbb-install.sh script. Fails for both version 2.6 and 2.7

I'm using the commands below:

$ wget -qO- https://ubuntu.bigbluebutton.org/bbb-install-2.6.sh | bash -s -- -w -v focal-260 -s ***.ke -e info@*** -g

OR

$ wget -qO- https://raw.githubusercontent.com/bigbluebutton/bbb-install/v2.7.x-release/bbb-install.sh | bash -s -- -w -v focal-270 -s ***.ke -e info@*** -g

In both situations I end up with:

The following packages have unmet dependencies:
 bigbluebutton : Depends: bbb-config but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 bbb-html5 : Depends: bbb-pads but it is not going to be installed
             Depends: bbb-webrtc-sfu but it is not going to be installed
             Depends: bbb-export-annotations but it is not going to be installed
             Depends: bbb-web but it is not going to be installed
             Depends: yq (< 4) but 4.16.2 is to be installed
E: Unable to correct problems, you have held broken packages.
.......................................................................................................................................................................................................................................................................................................................................................................................................................................

***

Please help?

**Comment by ffdixon** [comment]
Hi there,

Just did a new install of BigBlueButton of 2.7 on Digital Ocean and it installed.  Here are the details of `yq` install.

```
~# apt show yq
Package: yq
Version: 3.4.1bbb1
Priority: optional
Section: devel
Maintainer: Roberto Mier Escandón <rmescandon@gmail.com>
Original-Maintainer: Roberto Mier Escandón <rmescandon@gmail.com>
Installed-Size: 6221 kB
Depends: libc6 (>= 2.4)
Download-Size: 1549 kB
APT-Manual-Installed: no
APT-Sources: http://ppa.launchpad.net/bigbluebutton/support/ubuntu focal/main amd64 Packages
Description: lightweight and portable command-line YAML processor
 .
 The aim of the project is to be the
 [jq](https://github.com/stedolan/jq) or sed of yaml files.
```

**Comment by lonesomewalker** [comment]
You ran in the same problem as me: #686  (i bet ;-) )
Problem is that you want to install 2.6 and nodejs has to be changed from 16 to 18...

**Comment by naeemjawaid** [comment]
Hi, my version of node is v18.20.1, however, I still get the same error:
```
The following packages have unmet dependencies:
 bbb-html5 : Depends: bbb-pads but it is not going to be installed
             Depends: bbb-webrtc-sfu but it is not going to be installed
             Depends: bbb-export-annotations but it is not going to be installed
             Depends: bbb-web but it is not going to be installed
             Depends: yq (< 4) but 4.16.2 is to be installed
E: Unable to correct problems, you have held broken packages.
```
Please help me resolve this.
