### ISSUE TITLE
Cannot upgrade from 2.6.6 to 2.7

### ISSUE THREAD

**Issue by Heinivb** [bigbluebutton/bbb-install#704]
I have a dedicated linux server setup with BBB 2.6.6, 

When I run 
 wget -qO- https://raw.githubusercontent.com/bigbluebutton/bbb-install/v2.7.x-release/bbb-install.sh | bash -s -- -w -v focal-270 -s <my server address> -e <my email>-g -w
 
 There is no output, if I echo $? result is 0, I have stopped the running bbb-conf but still no success.
 
Current setup:
BigBlueButton Server 2.6.6 (1185)
Kernel version: 5.4.0-148-generic
Distribution: Ubuntu 20.04.6 LTS (64-bit)
Memory: 16370 MB
CPU cores: 8

I have tried downloading the script and executing it directly where output then is:
```bbb-install: Unable to locate packages for focal-270 at ubuntu.bigbluebutton.org.```

**Comment by antobinary** [comment]
Hi! Could you confirm you pass a valid email address after `-e` and a valid domain url after `-s`?
I just used focal-270 from that repo server, it is there, right permissions, everything.

**Comment by Heinivb** [comment]
Hi Anto, yes it is valid email and server address, when I run wget with debug turned on I get

Setting --quiet (quiet) to 1
Setting --quiet (quiet) to 1
Setting --output-document (outputdocument) to -
Setting --output-document (outputdocument) to -
DEBUG output created by Wget 1.20.3 on linux-gnu.

Reading HSTS entries from /root/.wget-hsts
URI encoding = ‘UTF-8’
Caching raw.githubusercontent.com => 185.199.109.133 185.199.108.133 185.199.110.133 185.199.111.133 2606:50c0:8002::154 2606:50c0:8003::154 2606:50c0:8001::154 2606:50c0:8000::154
Created socket 3.
Releasing 0x00005611a8bd71f0 (new refcount 1).
Initiating SSL handshake.
Handshake successful; connected socket 3 to SSL handle 0x00005611a8bd7530
certificate:
  subject: CN=*.github.io,O=GitHub\\, Inc.,L=San Francisco,ST=California,C=US
  issuer:  CN=DigiCert TLS RSA SHA256 2020 CA1,O=DigiCert Inc,C=US
Closed 3/SSL 0x00005611a8bd7530

**Comment by Heinivb** [comment]
Its working now, was a missing ssl certificate on my server

**Comment by antobinary** [comment]
Thanks for commenting back with the reason for the issue!
