### ISSUE TITLE
Unable to locate packages for focal-270 at ubuntu.bigbluebutton.org

### ISSUE THREAD

**Issue by john1726** [bigbluebutton/bbb-install#705]
Please note that I have been following the directions on https://github.com/bigbluebutton/bbb-install using this command to install bbb-install-2.7.sh on my Ubuntu 20.04 machine:

`root@Grieg:/home/rmoore/Install# wget -qO- https://raw.githubusercontent.com/bigbluebutton/bbb-install/v2.7.x-release/bbb-install.sh | bash -s -- -w -v focal-27 -s mydomain.org -e email@example.com`

But it is still giving me this error:

`bbb-install: Unable to locate packages for focal-270 at ubuntu.bigbluebutton.org.`

Is focal-270 available now? My focal-260 stopped working.

Please note that I checked https://github.com/bigbluebutton/bbb-install/issues/627 but the README on bbb-install.sh says to use focal-270 now.

Do you have any suggestions? TIA.

**Comment by antobinary** [comment]
Hi @john1726 

Please use `focal-270`, not `focal-27`.

Where did you find this `focal-27` option? It looks like a typo but I am not finding it. Share a link please.

**Comment by john1726** [comment]
Thank you!  Now I am getting "You have been removed from the conference" when I try to start an online meeting.

**Comment by antobinary** [comment]
Hi again!

Based on your logs it looks like you are upgrading from 2.5 to 2.7 or 2.5->2.6->2.7... I see remnants of bbb-demo package https://docs.bigbluebutton.org/2.6/new-features#we-have-retired-the-bbb-demo-api-demos-development-only-package
I also see logs of some other application on the same server... It's difficult to assist when there are other apps.
Please try the url in `bbb-conf --salt` in the browser. Then use it to create a meeting and if you're able to join it as a moderator.

**Comment by john1726** [comment]
Do you mean go to this URL?

[https://mconf.github.io/api-mate/#server=https://tuberedu.ca/bigbluebutton/&sharedSecret=vnCtrLiwICcPVs3ETYPdneRnauYfDAkZv4BVSNLKzg]

How do I then create a meeting?

**Comment by antobinary** [comment]
@john1726 I have deleted your post because it gives access to your BigBlueButton. I just created a meeting and joined it. It worked normally.

Please change the secret now `bbb-conf --setsecret <some new hash secret>`

Anyway, using the link you shared - I clicked on the Create meeting URL, got an xml confirmation.
Clicked on the Join as moderator link, the client opened, all fine.

Please play around with it a bit. Be careful with exposing the secret of your server.

I will close this issue now as your installation worked fine, it was just a typo in the initial command.

**Comment by john1726** [comment]
So from now on we need to call API Mate instead of calling the BBB server directly?

**Comment by john1726** [comment]
Not sure what was giving me that "You have been removed from the conference" message, but I ended up re-installing Ubuntu 20.04 from scratch along with BBB 2.70, so now it is working for me.  See also https://github.com/bigbluebutton/bbb-install/issues/706

**Comment by antobinary** [comment]
Happy to hear you were able to figure it out!
