### ISSUE TITLE
bbb-install.sh error

### ISSUE THREAD

**Issue by khanv66** [bigbluebutton/bbb-install#714]
Greetings!
I am trying to perform the following installation:
wget -qO- https://raw.githubusercontent.com/bigbluebutton/bbb-install/v3.0.x-release/bbb-install.sh | bash -s -- -v jammy-300 -s bbb.testdomain.com -e info@testdomain.com

I get the following error:
+ DISTRO=jammy
+ wget -qS --spider https://ubuntu.bigbluebutton.org/jammy-300/dists/bigbluebutton-jammy/Release.gpg
+ err 'Unable to locate packages for jammy-300 at ubuntu.bigbluebutton.org.'

Is the path on the server exactly correct?

**Comment by ffdixon** [comment]
We haven't released the alpha for 3.0 yet.  Keep an eye on the [bigbluebutton-dev](https://groups.google.com/g/bigbluebutton-dev) mailing list for the announcement.

When it's announced, it will include steps to install.

**Comment by nasilaj** [comment]
Hello Dixon,
I am Dr Nasila. the one for whom you loaded SPSS and AMos. My number is
0788444821.
Please get in touch with me.
Yours sincerely
Dr JS Nasila

**Comment by ffdixon** [comment]
3.0-alpha-1 is out!

https://groups.google.com/g/bigbluebutton-dev/c/qjNLIaKQNJc
