### ISSUE TITLE
Installation: Problem with dependencies

### ISSUE THREAD

**Issue by smartkwadrat** [bigbluebutton/bbb-install#718]
Hi Team,

Im trying to install BigBlueButton on my VM on Proxmox where I have Ubuntu Server 22.04.3 LTS
![image](https://github.com/bigbluebutton/bbb-install/assets/154097394/be5345cc-95f2-45dc-bbc0-f8d0f5fdfb67)

When Im trying to install BBB using your script: 
sudo wget -qO- https://raw.githubusercontent.com/bigbluebutton/bbb-install/v2.7.x-release/bbb-install.sh | sudo bash -s -- -w -v focal-270 -s bbb.amadeuszjakobczak.pl -e admin@smartkwadrat.com

I have this problem:
![image](https://github.com/bigbluebutton/bbb-install/assets/154097394/8eaa113a-4ec7-49ea-8c0f-f62e250460a5)

I was seaching everywhere how to solve it but I faild to find solution.
I do not understand how for example yq is not installable, for me my yq is fine:
![image](https://github.com/bigbluebutton/bbb-install/assets/154097394/4d5399d2-246a-49dc-8798-23ea4998af37)

Please help me.

**Comment by ffdixon** [comment]
See answer to this issue

  https://github.com/bigbluebutton/bbb-install/issues/716

Regards,... Fred
