### ISSUE TITLE
BigBlueButton and cloudflare tunnel

### ISSUE THREAD

**Issue by d8rt8v** [bigbluebutton/bbb-install#723]
Hi! 

I'm trying to setup bbb Version 2.7.4 through [clodflare tunneling service](https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/). 
When i connect to my url i get default hello ngnix web page, not a bbb welcome screen,
Tried both  --setip with my hostname and local ip, addtionally tried to edit hosts with my desired host. 

Is it even possible to tunnel bbb?

**Comment by idhamari** [comment]
I was able to install it and make the interface work via Docker Compose, but it seems Cloudflare Tunnel does not support UDP
