### ISSUE TITLE
W: Failed to fetch https://ubuntu.bigbluebutton.org/-s/dists/bigbluebutton-/InRelease  Could not connect to ubuntu.bigbluebutton.org:443

### ISSUE THREAD

**Issue by john1726** [bigbluebutton/bbb-install#730]
Does anyone know why I am receiving these errors?  Does anyone have any suggestions?  TIA.

```
W: Failed to fetch https://ubuntu.bigbluebutton.org/-s/dists/bigbluebutton-/InRelease  Could not connect to [ubuntu.bigbluebutton.org:443](http://ubuntu.bigbluebutton.org:443/) (167.99.180.121). - connect (113: No route to host)
W: Some index files failed to download. They have been ignored, or old ones used instead.
...
E: Unable to locate package bigbluebutton
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package bbb-html5
```

What happened to https://ubuntu.bigbluebutton.org?

See also https://github.com/bigbluebutton/bbb-install/issues/729 for more details.

**Comment by john1726** [comment]
Ended up installing BBB 2.6

**Comment by ffdixon** [comment]
> https://ubuntu.bigbluebutton.org/-s/dists/bigbluebutton-/InRelease

that does not look correct.  What what parameters did you pass to bbb-install command?

**Comment by antobinary** [comment]
`lsb-core` was not available, see https://github.com/bigbluebutton/bbb-install/issues/729#issuecomment-1948667923
