### ISSUE TITLE
bbb-install: Unable to locate packages for focal-270 at ubuntu.bigbluebutton.org

### ISSUE THREAD

**Issue by emoxam** [bigbluebutton/bbb-install#733]
./bbb-install.sh -v focal-270 -s bbb.example.com -e admin@example.com

Gives me 
bbb-install: Unable to locate packages for focal-270 at ubuntu.bigbluebutton.org

What to do ?

**Comment by ffdixon** [comment]
Just did a quick test now and the parameter `-v focal-270` is working.  Can you share where in the world the server is located that you are trying to install BigBlueButton?

Also, can you test access to the package repository from the server

```
$ wget -qO- https://ubuntu.bigbluebutton.org/test.html
BigBlueButton Package Server
```

**Comment by emoxam** [comment]
Russia

**Comment by paulmenzel** [comment]
@emoxam, were you able to solve the issue? Just to make sure, it’s not the same issue as issue https://github.com/bigbluebutton/bbb-install/issues/735, do you have *wget* installed?

**Comment by emoxam** [comment]
@paulmenzel If i remember right i fix it by running wget command with a system-wide proxy... Seems Russian ips is blocked.

**Comment by paulmenzel** [comment]
Thank you for your quick reply. Just to confirm, if they are still blocked, can you please run:

    wget -qO- https://ubuntu.bigbluebutton.org/test.html

**Comment by emoxam** [comment]
@paulmenzel works well

wget -qO- https://ubuntu.bigbluebutton.org/test.html
`BigBlueButton Package Server`

**Comment by paulmenzel** [comment]
Thank you for testing this. Then it must have been a temporary problem. Currently your IP address (block) does not seem to be blocked. If you agree, could you please close the issue?

**Comment by emoxam** [comment]
yes! thanks!

**Comment by ffdixon** [comment]
Yay!
