### ISSUE TITLE
[Unconfirmed] ubuntu.bigbluebutton.org slower than usual?

### ISSUE THREAD

**Issue by Ithanil** [bigbluebutton/bbb-install#737]
# Original report
My original report was this:

At least since yesterday, 12.04., bbb-install for 2.7 seems to be hanging indefinitely when trying to get the bbb-web package:

`Get:319 https://ubuntu.bigbluebutton.org/focal-270 bigbluebutton-focal/main amd64 bbb-web amd64 1:2.7-47 [203 MB]`

## To reproduce
1) `wget -v https://raw.githubusercontent.com/bigbluebutton/bbb-install/v2.7.x-release/bbb-install.sh`
2) `http_proxy=http://ourproxy:1234/ https_proxy=http://ourproxy:1234/ bash -x bbb-install.sh -v focal-270 -s $(hostname -f) -d -w`

# Correction
After waiting for nearly 10 minutes, the command actually went through, but only to spend a lot of time again on other BBB packages. So I come to the conclusion that the BBB repository is very slow at the moment.

**However, it seems like other people can't reproduce this.**

**Comment by Ithanil** [comment]
The issue is resolved now, the exact cause remains unclear.

**Comment by ffdixon** [comment]
Just did a quick test on our end for a new install and confirmed it installed without issue.
