### ISSUE TITLE
`E: The repository 'https://ubuntu.bigbluebutton.org/jammy-300 bigbluebutton-jammy InRelease' is not signed.`

### ISSUE THREAD

**Issue by paulmenzel** [bigbluebutton/bbb-install#738]
https://github.com/bigbluebutton/bbb-install/blob/9e0691bb9e3576a58d764a8fd406054b3d58bb95/bbb-install.sh#L552-L576

Adding the key like this does not work anymore in Ubuntu 22.04, and results in:

    Err:11 https://ubuntu.bigbluebutton.org/jammy-300 bigbluebutton-jammy InRelease
      The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 37B5DD5EFAB46452
    Get:13 https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0/multiverse amd64 Packages [58.2 kB]
    Get:14 https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0/multiverse arm64 Packages [55.1 kB]
    Reading package lists... Done
    W: GPG error: https://ubuntu.bigbluebutton.org/jammy-300 bigbluebutton-jammy InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 37B5DD5EFAB46452
    E: The repository 'https://ubuntu.bigbluebutton.org/jammy-300 bigbluebutton-jammy InRelease' is not signed.
    N: Updating from such a repository can't be done securely, and is therefore disabled by default.
    N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by paulmenzel** [comment]
Closing for now, until I have the full logs to check again.

**Comment by paulmenzel** [comment]
Looks similar to issue https://github.com/bigbluebutton/bbb-install/issues/414.

**Comment by Ramziddin-ice** [comment]
bbb-install: Unable to locate packages for jammy-300 at ubuntu.bigbluebutton.org.
+ exit 1 ??
