### ISSUE TITLE
greenlight missing

### ISSUE THREAD

**Issue by AnasAfawzy** [bigbluebutton/bbb-install#756]
i try install bigbluebutton on my own local server using this command :
![Screenshot from 2024-10-19 02-03-57](https://github.com/user-attachments/assets/9d259588-88b1-4a0a-831b-f610beb47702)

wget -qO- https://raw.githubusercontent.com/bigbluebutton/bbb-install/v2.7.x-release/bbb-install.sh | bash -s -- -w -v focal-270 -s 192.168.1.199 -w -g -k

![Screenshot from 2024-10-19 02-04-28](https://github.com/user-attachments/assets/ff80f64f-7f91-4efe-be4b-2d18941637df)
i cant access greenlight ???

**Comment by ffdixon** [comment]
You need to setup a domain name for your server with a valid SSL certificate.  Using an IP address won't work. See

 https://github.com/bigbluebutton/bbb-install?tab=readme-ov-file#getting-ready

**Comment by AnasAfawzy** [comment]
Thanks for your response 
Do I have to use a certificate and my server is local only to try connecting with Laravel?

**Comment by ffdixon** [comment]
> Do I have to use a certificate

Yes, it won't work without a domain name + certificate.

**Comment by AnasAfawzy** [comment]
Thanks a lot
