### ISSUE TITLE
ubuntu.bigbluebutton.org Certificate Expired

### ISSUE THREAD

**Issue by aogilvie** [bigbluebutton/bbb-install#78]
```
wget https://ubuntu.bigbluebutton.org/bbb-install.sh
--2019-10-23 07:58:52--  https://ubuntu.bigbluebutton.org/bbb-install.sh
Resolving ubuntu.bigbluebutton.org (ubuntu.bigbluebutton.org)... 167.99.180.121
Connecting to ubuntu.bigbluebutton.org (ubuntu.bigbluebutton.org)|167.99.180.121|:443... connected.
ERROR: cannot verify ubuntu.bigbluebutton.org's certificate, issued by ‘CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US’:
  Issued certificate has expired.
To connect to ubuntu.bigbluebutton.org insecurely, use `--no-check-certificate'.
```

If you are using similar scripts to lets encrypt cert setup with bigbluebutton, as we discussed already, the post hook to restart nginx might not be triggering (although in this case I am not referring to your repo server).

**Comment by ffdixon** [comment]
Thanks for pointing this out -- we've renewed the certificate on https://ubuntu.bigbluebutton.org/.

> If you are using similar scripts to lets encrypt cert setup with bigbluebutton, as we discussed already, the post hook to restart nginx might not be triggering (although in this case I am not referring to your repo server).

We did some work on this over the weekend.  In `bbb-install.sh`, we added `--deploy-hook "systemctl restart nginx"` to the `certbot` command.  

See https://github.com/bigbluebutton/bbb-install/blob/master/bbb-install.sh#L684

If you run the above command manually for your server (provide the $HOST name), it will renew your certificate and in the associated configuration file for your host, such as for `bbb.example.com`

~~~
  /etc/letsencrypt/renewal/bbb.example.com.conf
~~~

You should now see

~~~
renew_hook = systemctl restart nginx
~~~

`certbot` already uses a `systemd` timer to poll for renewal, so we removed the creation of the cron job.

If you can try the above Ally and let us know if on your BigBlueButton server you see the `renew_hook` command in the configuration file for your server.

**Comment by andycgn42** [comment]
Hey, Thank you **ffdixon** for the fast support and the great work on bbb!

**Comment by AlphaDE** [comment]
The intermediate cert of ubuntu.bigbluebutton.org is again expired "Fri, 16 Jul 2021 02:22:50 GMT"

**Comment by ffdixon** [comment]
We've renewed the certificate for ubuntu.bigbluebutton.org (sorry about that).  Checking to see why the auto-renewal didn't work.

**Comment by AlphaDE** [comment]
@ffdixon Thx for that. It does work. Don't you use some monitoring for that, usually (at least for my certs) the renewal is 30 days ahead of the expiration leaving enough time to react (if there's some monitoring)

**Comment by ffdixon** [comment]
Agreed.  We'll put monitoring in place so this doesn't happen again (https://geekflare.com/monitor-ssl-certificate-expiry/).

**Comment by carlosr279** [comment]
Hello. this afternoon this problem appeared on all my BBB servers: Server Error Invalid BigBlueButton Endpoint and Secret.

When I tried to renew the certificate but nothing happens.

I followed this steps: https://docs.bigbluebutton.org/2.2/install.html#using-lets-encrypt but says that ubuntu.bigbluebutton.org Certificate has Expired. So I don't know if it is working properly.

And when I run docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check

Checking environment: Passed
Checking Connection: Failed
Error connecting to BigBlueButton server - SSL_connect returned=1 errno=0 state= SSLv3 read server certificate B: certificate verify failed (certificate has expired)

My certificates are updated but the error remains, so... just asking if it has somwthing to do with ubuntu.bigbluebutton.org certificate ???

**Comment by Palubas** [comment]
Hello.
Same problem happened yesterday Server error Invalid BigBlueButton endpoint and secret.

I get the same error:
Checking environment: Passed
Checking Connection: Failed
Error connecting to BigBlueButton server - SSL_connect returned = 1 errno = 0 state = SSLv3 read server certificate B: certificate verify failed (certificate has expired).

Did you manage to solve the problem?

**Comment by Palubas** [comment]
> Hello. Same problem happened yesterday. Check BigBlueButton endpoint and secret.
> 
> I get the same error: Checking environment: Passed Checking Connection: Failed Error connecting to BigBlueButton server - SSL_connect returned = 1 errno = 0 state = SSLv3 read server certificate B: certificate verify failed (certificate has expired).
> 
> Did you manage to solve the problem?



> UPDATE:
> 
> I tried this and worked: #432
> 
> Now everything is working fine with my BBB servers.
> 
> Hello. this afternoon this problem appeared on all my BBB servers: Server Error Invalid BigBlueButton Endpoint and Secret.
> 
> When I tried to renew the certificate but nothing happens.
> 
> I followed this steps: https://docs.bigbluebutton.org/2.2/install.html#using-lets-encrypt but says that ubuntu.bigbluebutton.org Certificate has Expired. So I don't know if it is working properly.
> 
> And when I run docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check
> 
> Checking environment: Passed Checking Connection: Failed Error connecting to BigBlueButton server - SSL_connect returned=1 errno=0 state= SSLv3 read server certificate B: certificate verify failed (certificate has expired)
> 
> My certificates are updated but the error remains, so... just asking if it has somwthing to do with ubuntu.bigbluebutton.org certificate ???

**Comment by Palubas** [comment]
Hello.

Got the same error yesterday.  Server error Check BigBlueButton Endpoint and Secret.

Checking environment: Passed Checking
Connection: Failed Error connecting to BigBlueButton server - SSL_connect returned=1 errno=0 state= SSLv3 read server certificate B: certificate verify failed (certificate has expired)

Managed to solve the problem?

**Comment by AlphaDE** [comment]
Do you guys use Let's Encrypt certificates? The old root certs used by Let's Encrypt (IdentTrust DST Root CA X3) expired as of 9/30 and that caused various issues on my server because the trust chain contained valid and expired certs. Perhaps that's the reason for the trouble?

**Comment by Palubas** [comment]
Yes, I am using Let's Encrypt.
I found how to solve this problem.
Thanks everyone

**Comment by gilPts** [comment]
Hello @Palubas , 
Please could you share in details how you solve your issue ? 
Thanks in advance

**Comment by coffeduong** [comment]
Credit for ghazi.n...@gmail.com and emadbagheri96

```
sudo apt-get remove certboat
sudo apt-get install snapd
sudo snap install --classic certbot
sudo certbot renew --force-renewal --cert-name mybbb.server.com --preferred-chain "ISRG Root X1"
sudo /etc/init.d/nginx restart 
```

**Comment by gilPts** [comment]
Thanks, those helps :)
