### ISSUE TITLE
bbb-install: You must unisntall apache2 first

### ISSUE THREAD

**Issue by neutron92** [bigbluebutton/bbb-install#8]
bbb-install: You must unisntall apache2 first

but i'm using apache because i have other prod porjects in the same server

**Comment by ffdixon** [comment]
We recommend not running BigBlueButton on a server that has apache2 due to potential resource conflicts.  Both are going to want to bind to port 443, which is going to be a problem.

Is it an option for you to install BigBlueButton on a server that does not have apache2?

**Comment by neutron92** [comment]
@ffdixon in the server we are using the apache and nginx the apache is not pointed in the 80 port

**Comment by ffdixon** [comment]
There is likely subtle resource conflicts with other applications that are causing the errors you are seeing.  

Give a try installing on a clean server and let us know if you still get the same error.

**Comment by neutron92** [comment]
@ffdixon the conflict is with redis server can you tell me what is the port of redis-server?

**Comment by Vertux** [comment]
> We recommend not running BigBlueButton on a server that has apache2 due to potential 
> resource conflicts. Both are going to want to bind to port 443, which is going to be a problem.

@ffdixon Isn't it possible to run BBB under a subdomain with apache2 ? I guess everyone who owns a powerful server, which hosts a couple of applications would not like to spend additional money for a seperate BBB only server. This topic is pretty old so I would like to know if your statement is still valid?

**Comment by ozkan** [comment]
> @ffdixon Isn't it possible to run BBB under a subdomain with apache2 ? I guess everyone who owns a powerful server, which hosts a couple of applications would not like to spend additional money for a seperate BBB only server. This topic is pretty old so I would like to know if your statement is still valid?


hi, have you been able to find a solution for this problem?

**Comment by Vertux** [comment]
> > @ffdixon Isn't it possible to run BBB under a subdomain with apache2 ? I guess everyone who owns a powerful server, which hosts a couple of applications would not like to spend additional money for a seperate BBB only server. This topic is pretty old so I would like to know if your statement is still valid?
> 
> hi, have you been able to find a solution for this problem?

Unfortunately not, it is pretty disappointing.

**Comment by DocEpsilon** [comment]
I get the message I should remove Apache2 even though it was never installed.
```
root@cloudserv-me:~# wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -w -a -v bionic-24 -s meet.mydomain.com -e post@mydomain.com
Hit:1 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu bionic InRelease                                                            
Hit:3 http://us.archive.ubuntu.com/ubuntu bionic-updates InRelease                                                    
Hit:4 http://us.archive.ubuntu.com/ubuntu bionic-backports InRelease                                                  
Hit:5 https://esm.ubuntu.com/infra/ubuntu bionic-infra-security InRelease                                             
Get:6 https://ubuntu.bigbluebutton.org/bionic-24 bigbluebutton-bionic InRelease [2,533 B]
Hit:7 https://esm.ubuntu.com/infra/ubuntu bionic-infra-updates InRelease              
Get:8 https://ubuntu.bigbluebutton.org/bionic-24 bigbluebutton-bionic/main i386 Packages [1,593 B]
Get:9 https://ubuntu.bigbluebutton.org/bionic-24 bigbluebutton-bionic/main amd64 Packages [37.7 kB]
Fetched 41.8 kB in 1s (34.7 kB/s)     
Reading package lists... Done
Warning: apt-key output should not be parsed (stdout is not a terminal)
bbb-install: You must uninstall the Apache2 server first
root@cloudserv-me:~# apt --purge remove apache2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package 'apache2' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@cloudserv-me:~# ```

The Sever was freshly migrated from Ubuntu 16.04 to 18.04 LTS. Earlier versions of BBB (2.2.x) have been purged.

**Comment by DocEpsilon** [comment]
Solved my earlier issue. Checked the [Script-Source](https://github.com/bigbluebutton/bbb-install/blob/master/bbb-install.sh) and learned that `apt --purge remove apache2-bin` ought to do the trick. Which it did.

**Comment by grafnull** [comment]
Thank you, DocEpsilon. Apache2 was preinstalled on my ubuntu server. 
`apt --purge remove apache2-bin` solved the issue for me.
