### ISSUE TITLE
Use existing certificates for HTTPS if provided

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bbb-install#82]
In some cases we need to use the provided SSL certificates that are already provided. Doing the HTTPS configuration can be long in not automated.

**Comment by ffdixon** [comment]
Agreed!  Need to add an option to let the user reference local certificates instead of using Let's Encrypt.

**Comment by ak4t0sh** [comment]
This issue has been partially fixed by #84 (but reverted in #85) which allow to provide existing certs.
IMO #84 should be extended to allow cert path customization

**Comment by ffdixon** [comment]
@ak4t0sh I think the code for this is in master -- the #85 only reverted out the description in the help text.

Please take a second look at master and let us know if it looks good for supporting `-d`.

**Comment by ak4t0sh** [comment]
Thanks @ffdixon !
I misread changes from #85 and though code was reverted too but you are right it was only doc.
So not tested but seems OK :+1:

**Comment by hex-m** [comment]
For others searching for this: if you use the `-d` option, those files will be used:
```
/local/certs/fullchain.pem
/local/certs/privkey.pem
```

**Comment by mk-hs** [comment]
The logic supporting the use of existing certificates and keys in /local/certs/ has been removed with https://github.com/bigbluebutton/bbb-install/commit/3a505eeab5de7caeb5327a710bb2ab854dc316fd
It's now necessary to manually link your certificates to 
`/etc/letsencrypt/live/$HOST/fullchain.pem` and
`/etc/letsencrypt/live/$HOST/privkey.pem`

Perhaps it was removed by mistake? @ffdixon

**Comment by ffdixon** [comment]
Thanks for pointing this out -- it was an error.  Fixed.
