### ISSUE TITLE
control certbot exit code

### ISSUE THREAD

**Issue by mikhailnov** [bigbluebutton/bbb-install#89]
scripts does not control exit code of certbot and does not give errro if certbot fails:

```
root@frkbturn:~# certbot certonly --standalone --preferred-challenges http --deploy-hook "systemctl restart coturn" -d domain.tld
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for domain.tld
Cleaning up challenges
Problem binding to port 80: Could not bind to IPv4 or IPv6.
root@frkbturn:~# echo $?
1
root@frkbturn:~# 
```

**Comment by ffdixon** [comment]
Do you have anything else binding to port 80 (such as Apache)?

**Comment by mikhailnov** [comment]
No. The problem was in capabilities: https://github.com/systemd/systemd/issues/14383
I reported this issue because the script should not have told be that coturn server has been set up correctly and is ready to use.
