### ISSUE TITLE
Bionic

### ISSUE THREAD

**Issue by oliroux** [bigbluebutton/bbb-install#94]
Hi,
The name of the 18.04 version of ubuntu appear in the script but when I try to run bbb-install.sh I received the message:
bbb-install: Unable to locate packages for bionic-220 at ubuntu.bigbluebutton.org.
Thanks for your helps

**Comment by ffdixon** [comment]
Hi there,

We're working on updating `bbb-install.sh` to work with Bionic 18.04, but it's still work in progress.  For now, use it for installation on 16.04 and we'll be making an announcement to [bigbluebutton-dev](https://groups.google.com/forum/#!forum/bigbluebutton-dev) when we have the installation ready for others to try on 18.04.

**Comment by h0jeZvgoxFepBQ2C** [comment]
Any updates on this? The docs still show that you need a 16.04 server?

**Comment by ffdixon** [comment]
We're hoping to get an early beta of BigBlueButton 2.3 (Ubuntu 18.04) out shortly.
