### ISSUE TITLE
Install BBB in AWS EC2

### ISSUE THREAD

**Issue by dhaval-bhimani** [bigbluebutton/bbb-install#96]
DNS lookup for [domain-name] resolved to XX.XX.XX.XXX but didn't match local IP

When I ping with domain name it gives elastic IP of EC2

**Comment by ffdixon** [comment]
You can ignore that message as it is only __potential warnings__.

Other that the above, did the install work?

**Comment by dhaval-bhimani** [comment]
No install not work
It stop after that message

**Comment by ffdixon** [comment]
Can you check that the output for 

~~~
  wget -qO- http://169.254.169.254/latest/meta-data/public-ipv4
~~~

matches the output for

~~~
  dig +short <domain-name> @resolver1.opendns.com | grep '^[.0-9]*$' | tail -n1)
~~~

where `<domain-name>` is the domain name for your server.

**Comment by dhaval-bhimani** [comment]
Both outputs are the same it gives IP address
