### ISSUE TITLE
bbb-install.sh  "Not running: tomcat7 or grails LibreOffice"

### ISSUE THREAD

**Issue by dk1507** [bigbluebutton/bbb-install#98]
Hi Guys,
Tried the demo site and was impressed. Nice work, guys.

Then I have tried to install the lasted version using the bbb-install.sh method to give the BBB system a try. But the https installation did not work out.

The method I have tried with the result.

1, wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v xenial-220
1.1 on local VM with 192.168.x.x IP: works fine
1.2 on Cloud VM with public IP only: works fine
1.3 manually add the https support to use html5 client: not working with internal error 500

$bbb-conf --check
"""
# Potential problems described below
# Not running:  tomcat7 or grails LibreOffice
................................................................................
# Error: Could not connect to the configured hostname/IP address
"""

2, wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v xenial-220 -s bbb.example.com -e info@example.com -g
2.1 same cloud VM with public IP as 1.2
(of course, with my own domain and email address)
installation process works fine.  can show the Greenlight login page, any click goes to, 

Server Error
Invalid BigBlueButton Endpoint and Secret

$bbb-conf --check
"""
# Potential problems described below
# Not running:  tomcat7 or grails LibreOffice
................................................................................
# Error: Could not connect to the configured hostname/IP address
"""

Any ideas?

Thanks,

David

**Comment by ffdixon** [comment]
Hi David,

Did you substitute your domain name for `bbb.example.com`?  Did you get any errors when running the script?

**Comment by dk1507** [comment]
Thanks

1, did all the substitutes on top of the IP/http version manually, duble checked. no problem.
2, use the bbb-install.sh with all the substitutes, installation have no problem,
 with bbb-conf --restart
"""
Restarting BigBlueButton 2.2.0-rc-5 ...
Stopping BigBlueButton
Starting BigBlueButton



# Potential problems described below
# Not running:  tomcat7 or grails LibreOffice
................................................................................
# Error: Could not connect to the configured hostname/IP address
#
#    https://gtbbb.freshblue.xyz/
#
# If your BigBlueButton server is behind a firewall, see FAQ.

# Warning: found only 2 cores, whereas this server should have (at least) 4 CPU cores
# to run BigBlueButton in production.
#
#   https://docs.bigbluebutton.org/install/install.html#minimum-server-requirements
#
"""

**Comment by ffdixon** [comment]
It might be that `tomcat7` takes a longer time to startup (with only 2 CPU cores, your server is underpowered).  Try doing `sudo bbb-conf --check` again.  

If it doesn't start, try checking the log file `/var/log/tomcat7/catalina.out` for errors.

Is it an option for you to install on a server with 4 CPU cores?

**Comment by jranke** [comment]
Hi, I just ran bbb-install.sh with the greenlight option on a fresh Ubuntu 16.04 image and a public domain with associated IP address, and got in the end (hostname anonymised):

```
# Potential problems described below
# Not running:  tomcat7 or grails LibreOffice
................................................................................
# Error: Could not connect to the configured hostname/IP address
#
#    https://bbb.my_host.xyz/
#
# If your BigBlueButton server is behind a firewall, see FAQ.
```

In addition, when I try to create an account in greenlight, I get a message saying that my bbb endpoint and secret are not valid.

**Comment by jranke** [comment]
I wonder if this is related to the fact that when I query the secret, the endpoint returned is as follows:

```
~# bbb-conf --secret

    URL: https://bbb.my_domain.xyz/bigbluebutton/
    Secret: xxxxxxxxxxxxxxxxxxxx
```
I would expect the endpoint to be https://bbb.my_domain.xyz, but of course this is just a thought, as I do not know the internals.

**Comment by jranke** [comment]
I am still commenting in this issue, because I think that the problem of @dk1507 is not related to tomcat7, but to the message

```
Error: Could not connect to the configured hostname/IP address
```
which I am getting as well, wether I use bbb-install.sh or install manually.

**Comment by jranke** [comment]
In my case, another symptom is that if I check the greenlight `.env` file, I get

```
~/greenlight# docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check

Checking environment: Passed
Checking Connection: Failed
Could not get a valid response from BigBlueButton server - <html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.10.3 (Ubuntu)</center>
</body>
</html>
```

Nginx is up and running, and the greenlight login page is visible. Again, this happens regardless of using bbb-install.sh or doing a manual installation.

**Comment by dk1507** [comment]
Thanks guys,

Followed your instruction did a check. My fault, the script actually installed openjdk-9. After **replacing java9 with java8**, everything works now!

Thanks,

David

> It might be that `tomcat7` takes a longer time to startup (with only 2 CPU cores, your server is underpowered). Try doing `sudo bbb-conf --check` again.
> 
> If it doesn't start, try checking the log file `/var/log/tomcat7/catalina.out` for errors.
> 
> Is it an option for you to install on a server with 4 CPU cores?

**Comment by jranke** [comment]
@dk1507: How exactly did you replace java9 with java8?

**Comment by jranke** [comment]
OK, tomcat7 installs after installation of openjdk-8-jre-headless, and removal of openjdk-9-jre-headless. Thanks

**Comment by dk1507** [comment]
#sudo apt-get install openjdk-8-jdk
#update-alternatives --config java

**Comment by jranke** [comment]
Ah - thanks a bunch - that does the trick!!!

**Comment by ffdixon** [comment]
Thanks for sharing this!

**Comment by dk1507** [comment]
Hi, Fred and Johannes,

Great work as the result of co-working!

David

**Comment by jranke** [comment]
Well, it seems to me that finally Linux on a desktop client is a first class citizen in the videoconferencing world! And I will try go get by with 2 vCPUs and 4GB of RAM on my production system :) Cheers, Johannes

**Comment by vahid75** [comment]
i had the same issue during installation process  . and i removed it by increasing my cpu cores from 1 to 4 cores and error dissappeared . also keep in mind that running the ./bbb-install.sh as root user couse the whole process failed. add a non root user and add it to sudoers . hope it helps :))
